### PR TITLE
Remove jlogfiles and postmsg from JJOBS.

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- removes references for `jlogfile` and `postmsg` from the Global GSI J-Jobs.

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
These changes are required by NCO.   Modifications look OK to me.   Real test is to execute these j-jobs and confirm the correct behavior.

**Review by KateFriedman-NOAA — APPROVED** [review]
Removal of jlogfile references looks good, thanks for making @aerorahul !

**Comment by KateFriedman-NOAA** [comment]
I'll update my working clone on Dogwood after this goes in and will be running a new test with the updates.

**Comment by RussTreadon-NOAA** [comment]
DA j-jobs run on WCOSS2 with PR #275.   Jobs successfully run to completion without reference to postmsg or jlogfile.  This is an expected result.

**Comment by aerorahul** [comment]
@MichaelLueken-NOAA 
Can we  please get a review and action on this PR?

**Comment by aerorahul** [comment]
@MichaelLueken-NOAA is on leave and this is critical to make the deadline. 
I will merge to this PR given the SME have approved this change.

**Pull request merged**
