### PR TITLE
Improve gsi.x error message for missing ensemble background

### LINKED ISSUE #492: Improve gsi.x error messages for missing ensemble backgrounds
NCO bugzilla [#1196](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1196) requires improvements to error messages when gsi.x encounters a missing high resolution or ensemble background file.

This issue is opened to document addition of the requested changes for use in GFS v17 and later implementations.   Issue #491 documents the addition of requested changes for use in GFS v16.x implementations.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
This PR updates `src/gsi/cplr_gfs_ensmod.f90` to generate a more informative error message in the event of `gsi.x` attempting to read a non-existent ensemble member forecast.    This change is requested by NCO bugzilla [#1196](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1196).

Fixes #492

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@ShunLiu-NOAA or @hu5970 , do either of you have time to review this PR?

**Comment by RussTreadon-NOAA** [comment]
@CoryMartin-NOAA , do you have time to review this PR?  Changes are made to one file, `src/gsi/cplr_gfs_ensmod.f90`, to improve error checking and error messages when processing ensemble files as per NCO's request.

**Review by hu5970 — APPROVED** [review]
Looks good.

**Comment by RussTreadon-NOAA** [comment]
> Looks good.

Thank you, @hu5970 .  For some reason the PR is still requesting a review ... even after your approval.   Let me request your review and see what happens when you approve again.

**Review by hu5970 — APPROVED** [review]

**Comment by hu5970** [comment]
@RussTreadon-NOAA If you still cannot merge the code, you may need to add me as "reviewers with write access".

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , Rahul set up the NOAA-EMC/GSI repository.  I have not yet found a way for me to add your as "reviewers with write access".   We can wait until next week.   Thank you for your help!

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
Changes look straightforward to me, approved!

**Pull request merged**
