### PR TITLE
Port OznMon's non-operational components to wcoss2

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Ported components include build, developer data extraction/copy, image generation, and file transfer scripts.  

Note that operational portions of package were previously ported to wcoss2 under #227.

### CODE REVIEW

**Comment by EdwardSafford-NOAA** [comment]
@DavidHuber-NOAA if you have a moment can you take a look at these changes?  Thanks.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA in light of PR #327 it probably makes sense to close this PR.  I can integrate my changes once #327 is merged and then reevaluate things.

**Comment by MichaelLueken-NOAA** [comment]
@EdwardSafford-NOAA speaking with Rahul on Friday, he said that it wouldn't be an issue to go ahead and merge this work to the master.  However, after seeing your comments on PR #327, I do see that there could be additional cleanup work for the monitoring packages.  So, if you would prefer to close this PR for the time being and readdress it after PR #327 is merged to the authoritative repository, that is fine.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA Yes, I'd prefer to close this PR and reissue it after the cleanup and retesting.  Not trying to rush you, but when do you anticipate #327 will be merged into the repository?

**Comment by MichaelLueken-NOAA** [comment]
@EdwardSafford-NOAA Right now, there is an update out to the review committee that will be merged to the authoritative repository tomorrow - PR #328.  After that, the GFS v16.x changes will take priority.  There are currently two updates that will need to go in for GFS v16.x - PR #345 and PR #350.  Once these two have been merged, then I will work on PR #327.  Having said that, Andrew is also working on an update for GFS v16.x, which will take priority if he creates a PR before #345 and #350 have been merged to the authoritative repository.  So, anywhere between two and three weeks, depending on if Andrew creates a PR, otherwise, two weeks for the review committee to review the two GFS v16.x changes.

**Comment by EdwardSafford-NOAA** [comment]
Per discussion above I'm closing this PR and will integrate and retest following the implementation of PR #327.

**Pull request closed without merging**
