### PR TITLE
Turn off enspread reg

### LINKED ISSUE #634: remove "write_ens_sprd=.true."
In cplr_get_fv3_regional_ensperts.f90, "write_ens_sprd=.true." is hard-coded and overwrites the values in namelist. 
write_ens_sprd=.true." should be removed.

### PR DESCRIPTION
**Pull request by ShunLiu-NOAA**
**Description**

 In cplr_get_fv3_regional_ensperts.f90, "write_ens_sprd=.true." is hard-coded and overwrites the values in namelist.
write_ens_sprd=.true." should be removed.

Fixes #634 

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Review by TingLei-NOAA — APPROVED** [review]

**Review by RussTreadon-NOAA — APPROVED** [review]
Straight forward change which restores user control of `write_spread_ens` for fv3_regional via `HYBRID_ENSEMBLE` namelist.

**Comment by ShunLiu-NOAA** [comment]
@TingLei-NOAA and @RussTreadon-NOAA, thank you for approving this PR. I am going to start regression test.

**Review by xyzemc — APPROVED** [review]

**Comment by hu5970** [comment]
The regression tests on Hera:

```
Test project /scratch1/BMC/wrfruc/mhu/gsi/GSI/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf


1/9 Test #7: rrfs_3denvar_glbens ..............***Failed  673.07 sec
2/9 Test #5: hwrf_nmm_d3 ......................   Passed  683.88 sec
3/9 Test #4: hwrf_nmm_d2 ......................   Passed  731.31 sec
4/9 Test #8: netcdf_fv3_regional ..............   Passed  731.36 sec
5/9 Test #9: global_enkf ......................   Passed  1092.91 sec
6/9 Test #6: rtma .............................   Passed  1454.80 sec
7/9 Test #3: global_4denvar ...................   Passed  1729.82 sec
8/9 Test #2: global_4dvar .....................   Passed  1865.74 sec
9/9 Test #1: global_3dvar .....................   Passed  1969.45 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) = 1969.47 sec

The following tests FAILED:
	  7 - rrfs_3denvar_glbens (Failed)

```
The failure of rrfs_3denvar_glbens is "Failed the scalability test". This is not a fatal failure.
The regression test passed on Hera

**Comment by ShunLiu-NOAA** [comment]
Test project /lfs/h2/emc/lam/noscrub/emc.lam/Shun.Liu/gsi_regression/GSI/build
    Start 1: global_3dvar
1/9 Test #1: global_3dvar .....................   Passed  1672.98 sec
    Start 2: global_4dvar
2/9 Test #2: global_4dvar .....................   Passed  1685.60 sec
    Start 3: global_4denvar
3/9 Test #3: global_4denvar ...................   Passed  1495.32 sec
    Start 4: hwrf_nmm_d2
4/9 Test #4: hwrf_nmm_d2 ......................   Passed  727.12 sec
    Start 5: hwrf_nmm_d3
5/9 Test #5: hwrf_nmm_d3 ......................   Passed  492.70 sec
    Start 6: rtma
6/9 Test #6: rtma .............................   Passed  1208.46 sec
    Start 7: rrfs_3denvar_glbens
7/9 Test #7: rrfs_3denvar_glbens ..............   Passed  605.06 sec
    Start 8: netcdf_fv3_regional
8/9 Test #8: netcdf_fv3_regional ..............***Failed  483.17 sec
    Start 9: global_enkf
9/9 Test #9: global_enkf ......................   Passed  1107.32 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) = 9477.82 sec

The following tests FAILED:
          8 - netcdf_fv3_regional (Failed)
Errors while running CTest

The failure of netcdf_fv3_regional is "Failed the scalability test". This is not a fatal failure.
The regression test passed on WCOSS2

**Pull request merged**
