### PR TITLE
Update the QC for the enhanced high-resolution GOES-R mesoscale floater AMVs

### PR DESCRIPTION
**Pull request by JingCheng-NOAA**
**Description**
This is an update of the QC process for the enhanced high-resolution GOES-R mesoscale floater AMVs to resolve the issue #713.
As mentioned in the issue, enhanced AMV data are derived from IR band, which turns out to be not reliable in the mid-layer of atmosphere. Adding additional QC process to remove data in those layers are necessary and proved to enhance the Hurricane intensity forecast.

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**
This change has been tested with GSI regression test on Hera.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Review by yonghuiweng — APPROVED** [review]

**Review by XuLu-NOAA — APPROVED** [review]

**Comment by JingCheng-NOAA** [comment]
Thank you all for the quick response.

Jing

**Comment by ShunLiu-NOAA** [comment]
@JingCheng-NOAA Could you please start the regression test? 
@RussTreadon-NOAA Do you know if GDAS is or will be using "CIMISS(enhanced AMV) winds"? If yes, do you have somebody in mind to review this change?

**Comment by RussTreadon-NOAA** [comment]
[`global_convinfo.txt`](https://github.com/NOAA-EMC/GSI-fix/blob/develop/global_convinfo.txt) has `-1` (monitor) for type `241`
```
 uv       241    0   -1     3.0      0      0      0   2.5   6.1   1.4   2.5  0.000100     0    0.     0.      0    0.     0.    0    0
```
I do not know if the GDAS will assimilate this data type in the future.  Let me ask around.

**Comment by JingCheng-NOAA** [comment]
The test cases on Orion all passed except the case `global_4denvar`, which is the same reason as I mentioned in Ting's PR, no access to a prepbufr file `/work/noaa/da/rtreadon/CASES/regtest/gfs/prod/gdas.20240223/00/obs/gdas.t00z.prepbufr` that requires `rstprod` permission that I don't have.

**Comment by ADCollard** [comment]
@ShunLiu-NOAA @RussTreadon-NOAA We do not have short-term plans to use these data in the global system.   It will need further testing and the observation density will probably cause issues without a super-obbing or similar strategy.

**Comment by ShunLiu-NOAA** [comment]
@JingCheng-NOAA Could you please sync with "develop" and run regression test? Thank you.

**Comment by JingCheng-NOAA** [comment]
I've merged my code with the latest update of develop. Below are the regression test results on Orion:
`Test project /work/noaa/hwrf/save/jcheng/GSIversions/GSIamv/build
    Start 1: global_4denvar
1/7 Test #1: global_4denvar ...................   Passed  1847.94 sec
    Start 2: rtma
2/7 Test #2: rtma .............................   Passed  970.05 sec
    Start 3: rrfs_3denvar_glbens
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  609.23 sec
    Start 4: netcdf_fv3_regional
4/7 Test #4: netcdf_fv3_regional ..............   Passed  484.12 sec
    Start 5: hafs_4denvar_glbens
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  1340.99 sec
    Start 6: hafs_3denvar_hybens
6/7 Test #6: hafs_3denvar_hybens ..............   Passed  1102.21 sec
    Start 7: global_enkf
7/7 Test #7: global_enkf ......................   Passed  1166.04 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 7520.65 sec
`

**Comment by JingCheng-NOAA** [comment]
Regression test results on Hera:
`Test project /scratch1/NCEPDEV/hwrf/save/Jing.Cheng/GSIversions/GSIamv/build
    Start 1: global_4denvar
1/7 Test #1: global_4denvar ...................   Passed  2997.06 sec
    Start 2: rtma
2/7 Test #2: rtma .............................   Passed  972.68 sec
    Start 3: rrfs_3denvar_glbens
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  490.11 sec
    Start 4: netcdf_fv3_regional
4/7 Test #4: netcdf_fv3_regional ..............   Passed  486.46 sec
    Start 5: hafs_4denvar_glbens
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  1283.28 sec
    Start 6: hafs_3denvar_hybens
6/7 Test #6: hafs_3denvar_hybens ..............   Passed  1101.74 sec
    Start 7: global_enkf
7/7 Test #7: global_enkf ......................***Failed  1453.42 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 8786.37 sec

The following tests FAILED:
          7 - global_enkf (Failed)
`

Rerun of the  test case #7 passed
`Test project /scratch1/NCEPDEV/hwrf/save/Jing.Cheng/GSIversions/GSIamv/build
    Start 7: global_enkf
1/1 Test #7: global_enkf ......................   Passed  2856.53 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 2856.59 sec
`

**Comment by JingCheng-NOAA** [comment]
Below are the regression test results on WCOSS2, which are provided by Yonghui
`Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/HAFSamv2/build
    Start 1: global_4denvar

    Start 2: rtma

    Start 3: rrfs_3denvar_glbens

    Start 4: netcdf_fv3_regional

    Start 5: hafs_4denvar_glbens

    Start 6: hafs_3denvar_hybens

    Start 7: global_enkf

1/7 Test #7: global_enkf ......................***Failed   60.27 sec

2/7 Test #1: global_4denvar ...................***Failed   60.38 sec

3/7 Test #4: netcdf_fv3_regional ..............   Passed  483.29 sec

4/7 Test #3: rrfs_3denvar_glbens ..............   Passed  613.04 sec

5/7 Test #6: hafs_3denvar_hybens .............   Passed  1093.06 sec

6/7 Test #2: rtma .............................   Passed  1209.79 sec

7/7 Test #5: hafs_4denvar_glbens .............   Passed  1277.31 sec

71% tests passed, 2 tests failed out of 7
Total Test time (real) = 1277.46 sec`

Rerun of `global_enkf` and `global_4denvar` still failed. And the reason was `The ensemble files are linked to /lfs/h2/emc/da/noscrub/russ.treadon/CASES/regtest/gfs/prod/enkfgdas.20221108/18/mem010/model_data/atmos/history/, but the actual files are in /lfs/h2/emc/da/noscrub/russ.treadon/CASES/regtest/gfs/prod/enkfgdas.20221108/18/atmos/mem010.`

**Comment by ShunLiu-NOAA** [comment]
@RussTreadon-NOAA Is there a directory location change for test cases on WCOSS2?

**Comment by yonghuiweng** [comment]
> @RussTreadon-NOAA Is there a directory location change for test cases on WCOSS2?

The test cases are changed, but the secripts are different. For example, in global_4denvar.sh of this PR,
 64 dathis=$COMROOTgfs/$dumpges.$PDYg/${cycg}/model_data/atmos/history
But in other PR (i.e., toff_fix), this line is,
64 datges=$COMROOTgfs/$dumpges.$PDYg/${cycg}/atmos.

**Comment by yonghuiweng** [comment]
> @RussTreadon-NOAA Is there a directory location change for test cases on WCOSS2?

The test cases are not changed, but the secripts are different. For example, in global_4denvar.sh of this PR,
64 dathis=$COMROOTgfs/$dumpges.$PDYg/${cycg}/model_data/atmos/history
But in other PR (i.e., toff_fix), this line is,
64 datges=$COMROOTgfs/$dumpges.$PDYg/${cycg}/atmos.

**Comment by RussTreadon-NOAA** [comment]
I checked `/lfs/h2/emc/hur/noscrub/yonghui.weng/regression/HAFSamv`.  File `regression/regression_var.sh` contains the following local modifications
```
diff --git a/regression/regression_var.sh b/regression/regression_var.sh
index 31502867..9013e0de 100755
--- a/regression/regression_var.sh
+++ b/regression/regression_var.sh
@@ -30,7 +30,9 @@ else
 fi
 
 # Determine the machine
-if [[ -d /scratch1 ]]; then # Hera
+if [[ -d /glade ]]; then # Cheyenne
+  export machine="Cheyenne"
+elif [[ -d /scratch1 ]]; then # Hera
   export machine="Hera"
 elif [[ -d /mnt/lfs4 || -d /jetmon || -d /mnt/lfs1 ]]; then # Jet
   export machine="Jet"
@@ -64,25 +66,39 @@ case $machine in
     export check_resource="no"
     export accnt="nggps_emc"
   ;;
+  Cheyenne)
+    export queue="regular"
+    export noscrub="/glade/scratch/$LOGNAME/noscrub"
+    export group="global"
+    if [[ "$cmaketest" = "false" ]]; then
+      export basedir="/glade/scratch/$LOGNAME"
+    fi
+    export ptmp="/glade/scratch/$LOGNAME/$ptmpName"
+
+    export casesdir="/glade/work/epicufsrt/contrib/GSI_data/CASES/regtest"
+
+    export check_resource="no"
+    export accnt="NRAL0032"
+  ;;
   wcoss2)
-      export local_or_default="${local_or_default:-/lfs/h2/emc/da/noscrub/$LOGNAME}"
+      export local_or_default="${local_or_default:-/lfs/h2/emc/hur/noscrub/$LOGNAME}/"
       if [ -d $local_or_default ]; then
           export noscrub="$local_or_default/noscrub"
       elif [ -d /lfs/h2/emc/global/noscrub/$LOGNAME ]; then
-          export noscrub="/lfs/h2/emc/global/noscrub/$LOGNAME/noscrub"
+          export noscrub="/lfs/h2/emc/hur/noscrub/$LOGNAME/noscrub"
       fi
 
       export queue="${queue:-dev}"
-      export group="${group:-global}"
+      export group="${group:-hur}"
       if [[ "$cmaketest" = "false" ]]; then
-         export basedir="/lfs/h2/emc/da/noscrub/$LOGNAME/gsi"
+         export basedir="/lfs/h2/emc/hur/noscrub/$LOGNAME/gsi"
       fi
       export ptmp="${ptmp:-/lfs/h2/emc/ptmp/$LOGNAME/$ptmpName}"
 
       export casesdir="/lfs/h2/emc/da/noscrub/russ.treadon/CASES/regtest"
 
       export check_resource="no"
-      export accnt="${accnt:-GFS-DEV}"
+      export accnt="${accnt:-HAFS-DEV}"
   ;;      
   Orion | Hercules)
       export local_or_default="${local_or_default:-/work/noaa/da/$LOGNAME}"
@@ -190,7 +206,7 @@ export savdir="$ptmp"
 export JCAP="62"
 
 # Case Study analysis dates
-export global_adate="2024022300"
+export global_adate="2022110900"
 export rtma_adate="2020022420"
 export fv3_netcdf_adate="2017030100"
 export rrfs_3denvar_glbens_adate="2021072518"
```

The date for the global case , `global_adate`, has been changed from `2024022300` to `2022110900`.  Why?

The 2022110900 case is obsolete.  It does not use the operational directory structure.  It also does not contain GMI data.  GSI PR #692 added GMI assimilation.  The global case was updated to process GMI observations.   Please revert `global_adate="2022110900"` back to `global_adate="2024022300"`.

**Comment by yonghuiweng** [comment]
It's my fault, I copied the file regression_var.sh from previous PR test.
The re-test on WCOSS2  passed all cases.

Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/HAFSamv3/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  1023.99 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  1146.03 sec
3/7 Test #7: global_enkf ......................   Passed  1272.13 sec
4/7 Test #6: hafs_3denvar_hybens ..............   Passed  1513.33 sec
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  1634.25 sec
6/7 Test #2: rtma .............................   Passed  2233.55 sec
7/7 Test #1: global_4denvar ...................   Passed  2464.00 sec

100% tests passed, 0 tests failed out of 7

**Comment by JingCheng-NOAA** [comment]
> It's my fault, I copied the file regression_var.sh from previous PR test. The re-test on WCOSS2 passed all cases.
> 
> Test project /lfs/h2/emc/hur/noscrub/yonghui.weng/regression/HAFSamv3/build Start 1: global_4denvar Start 2: rtma Start 3: rrfs_3denvar_glbens Start 4: netcdf_fv3_regional Start 5: hafs_4denvar_glbens Start 6: hafs_3denvar_hybens Start 7: global_enkf 1/7 Test #4: netcdf_fv3_regional .............. Passed 1023.99 sec 2/7 Test #3: rrfs_3denvar_glbens .............. Passed 1146.03 sec 3/7 Test #7: global_enkf ...................... Passed 1272.13 sec 4/7 Test #6: hafs_3denvar_hybens .............. Passed 1513.33 sec 5/7 Test #5: hafs_4denvar_glbens .............. Passed 1634.25 sec 6/7 Test #2: rtma ............................. Passed 2233.55 sec 7/7 Test #1: global_4denvar ................... Passed 2464.00 sec
> 
> 100% tests passed, 0 tests failed out of 7

Thank you for the udpates!

**Review by ShunLiu-NOAA — APPROVED** [review]

**Pull request merged**
