### PR TITLE
Update calc_analysis.fd/CMakeLists.txt to use w3emc_4 (#478)

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
Correct bug in the release/gfsda.v16.3.0 build of `calc_analysis.x`.    Please see #478 for details.

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Thanks for the quick fix @RussTreadon-NOAA

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
I can create a companion PR in `GSI-utils/develop`.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , `GSI-utils/develop` is OK.   It uses `w3emc_4`.

https://github.com/NOAA-EMC/GSI-utils/blob/develop/src/netcdf_io/calc_analysis.fd/CMakeLists.txt

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA Thanks for fixing the bug.  What was the impact of this bug?

**Comment by emilyhcliu** [comment]
> @RussTreadon-NOAA Thanks for fixing the bug. What was the impact of this bug?

@RussTreadon-NOAA @aerorahul 
I read more e-mails related to this.  This PR fixed the erroneous time records found in the grib2 forecast files, and the source of error was from the calc_analysis.x.  Do I understand the issue and the fix correctly?

**Comment by RussTreadon-NOAA** [comment]
> > @RussTreadon-NOAA Thanks for fixing the bug. What was the impact of this bug?
> 
> @RussTreadon-NOAA @aerorahul I read more e-mails related to this. This PR fixed the erroneous time records found in the grib2 forecast files, and the source of error was from the calc_analysis.x. Do I understand the issue and the fix correctly?

Yes, @emilyhcliu , your understanding of the problem is correct.  calc_analysis.x was being built with the wrong w3emc library.  As a result the analysis date calculation in calc_analysis.x generated the wrong value.   This was not due to a code problem but rather building with the wrong w3emc library.   This fix was simple:  build the calc_analysis.x code with the correct w3emc library.

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA @aerorahul 
Does this bug fix only fix the time issue, and the rest of the analysis fields stay the same? 
In other words, does this bug fix change the analysis fields and, thus, the subsequent forecasts?
We also use w3emc_d in other parts of the GSI (per communication with Lin).  Is it sufficient to fix the calc_analysis.x only?

**Comment by RussTreadon-NOAA** [comment]
The bug in question pertains specifically to calc_analysis.x.   Compiling calc_analysis with the correct w3emc library only alters the time written to the output analysis file, atmanl.nc.   The use of w3emc_d, w3emc_4, or w3emc_8 depends on which w3emc routines are used and which arguments are passed.   If you are concerned about which w3emc is used in various parts of the DA cycle, you can compare w3emc use in current operational DA apps with the use in gfsda.v16.3.0.   If you are concerned about the impact of the change in the w3emc used to build calc_analysis.x on the cycled system, we can run a parallel with the bug and compare output with Lin's corrected parallel.

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA Thanks for your explanation.  I understand that switching to w3emc_4 for calc_analysis only alters the time stamp.  Based on my understanding, I do not think we need to run with the bug to compare with Lin's corrected parallel.

**Pull request merged**
