### PR TITLE
changes to allow GSI to compile on GAEA

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
**Description**

The modulefile and build logic for GAEA are out-of-date, so GSI cannot compile there. This PR updates the gsi_gaea.lua modulefile to use the same libraries as the ufs-weather-model. Also, it disables MKL on GAEA by default, to avoid a link-time error when Cray libsci conflicts with MKL. Only the build.sh disables it by default; the default in CMakeLists.txt is unchanged.

This is a draft because I cannot run jobs on GAEA. Until I can, I have no way to know if this build actually works.

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

All I know is that it compiles; I don't know if it runs. That's why this is still a draft. I'm still waiting for access to a project that lets me submit jobs on GAEA.

I don't know how to run the GSI regression tests, so I haven't done that either. Only GAEA-specific parts of the scripts have changed. It should be impossible for these changes to break other platforms. The impossible has been known to happen, so it would be best to test anyway.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by natalie-perlin** [comment]
@SamuelTrahanNOAA - 
Please note that the [PR-571](https://github.com/NOAA-EMC/GSI/pull/571) has the updates for Gaea for the Intel/2022 compilers. Regression tests were run as well.

**Comment by RussTreadon-NOAA** [comment]
@SamuelTrahanNOAA  , is this PR still relevant now that PR #571 has been merged into develop? If this PR contains changes we need in develop, please update `SamuelTrahanNOAA:features/compile-on-gaea` and I'll work with you to get the changes in.

**Comment by SamuelTrahanNOAA** [comment]
> is this PR still relevant now that PR https://github.com/NOAA-EMC/GSI/pull/571

Unfortunately, neither this PR nor the GAEA support in #571 are useful at all. They both port GSI to the obsolete GAEA C4, not GAEA C5. I'm working on a C5 port now.

**Comment by RussTreadon-NOAA** [comment]
Thank you @SamuelTrahanNOAA  for the quick reply.  Shall we close this draft PR?  You can open a new PR when the C5 port is ready for review.

**Pull request closed without merging**
