### PR TITLE
fix for zero total ozone pressure in EnKF (issue #625)

### PR DESCRIPTION
**Pull request by jswhit**
The fix involves setting the pressure to 0.001Pa for ozone obs that have zero pressure (to avoid Inf when log(p) calculated), and turning off ob-space vertical localization.  Has no effect on current operational setup which uses model-space vertical localization (modelspace_vloc=T).

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Clone `jswhit:fixtotoz` on Hera, Orion, and WCOSS2 (Cactus).  Build `gsi.x` and `enkf.x`.  Since this PR only alters `src/enkf/enkf_obsmod.f90`, only run `global_enkf` ctest.    Test passes on Hera, Orion, and WCOSS2.   This is an expected result since the `global_enkf` ctest runs with `modelspace_vloc=T`.

**Review by RussTreadon-NOAA — APPROVED** [review]
Change looks good.  Approve pending peer review

**Review by HaixiaLiu-NOAA — APPROVED** [review]
changes were discussed and expected. Approved

**Review by jack-woollen — APPROVED** [review]

**Comment by wx20jjung** [comment]
Changes are as expected. Approved.

**Comment by RussTreadon-NOAA** [comment]
Thank you @HaixiaLiu-NOAA , @jack-woollen , and @wx20jjung for your quick approvals.  I'll coordinate merger with the GSI Handling Review team.

**Pull request merged**
