### PR TITLE
Ref #225

### LINKED ISSUE #225: Port MinMon to wcoss2
Port MinMon DA package to wcoss2.  

Initially I'd planned to remove the version numbers from the MinMon package (as I've done in the other *Mon packages).  But after re-reading the directions for porting to wcoss2, it's clear that that change does not fall under the directions to make changes only as required for porting to the platform.  So I'll wait on restructuring the package.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Added  changes for MinMon port to wcoss2.  This completes #225.

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
These changes look good.   Assuming they have been tested on WCOSS2 and another machine (e.g., WCOSS_D) and work as intended, this PR should be merged into `feature/gfsda.v16.1.5_wcoss2_port`.   These changes are needed to finish the GFS DA WCOSS2 port.

**Comment by MichaelLueken-NOAA** [comment]
Since Russ has approved these changes, I will now move forward with merging these changes to the authoritative feature/gfsda.v16.1.5_wcoss2_port branch.

**Comment by RussTreadon-NOAA** [comment]
As a test I ran the gfs and gdas minmon driver scripts on WCOSS_D and WCOSS2.  Both the WCOSS_D and WCOSS2 gfs and gdas minmon jobs reproduced operational output.

Besides editing paths in the driver scripts to correspond to my installation, the following additional changes were necessary.

`gdas.v1.0.0/driver/test_jgdas_vminmon_wcoss_d.sh`
```
-$JOBGLOBAL/JGDAS_VMINMON
+$JOBGLOBAL/JGDAS_ATMOS_VMINMON
```

`gfs.v1.0.0/driver/test_jgfs_vminmon_wcoss_d.sh`
```
-$JOBGLOBAL/JGFS_VMINMON
+$JOBGLOBAL/JGFS_ATMOS_VMINMON

```
The WCOSS_D drivers need to update the name of the MinMon j-job.    A similar comment applies to drivers for cray, hera, theia (obsolete), and the non-machine specific `test_j{gdas,gfs}_vminmon`.

`gdas.v1.0.0/driver/test_jgdas_vminmon_wcoss2.sh`
```
 module load prod_util/2.0.10
+module load intel/19.1.3.304
 module load util_shared/1.4.0
```
`gfs.v1.0.0/driver/test_jgfs_vminmon_wcoss2.sh`
```
 module load prod_util/2.0.10
+module load intel/19.1.3.304
 module load util_shared/1.4.0
```
WCOSS2 module `util_shared/1.4.0` has `intel/19.1.3.304` as a prerequisite.

The above comments do not alter the approve status of my review.   These comments are FYI.   They could be addressed in this PR or a subsequent PR.  

PR #225 works as advertised.  It reproduces operational output on WCOSS_D and WCOSS2.

**Comment by EdwardSafford-NOAA** [comment]
My plan is to correct the issues noted above within the GSI/master branch in order to keep the changes to feature/gfsda.v16.1.5_wcoss2_port to bare minimum.  I was planning on a MinMon maintenance update and will add include this work to it.

**Comment by RussTreadon-NOAA** [comment]
Sounds like a good plan.   Thanks, Ed.

**Pull request merged**
