### PR TITLE
Feature/files for jedi

### PR DESCRIPTION
**Pull request by HaixiaLiu-NOAA**
This pull request is for JEDI AOP project. The BottomLevelPressure written out in setupoz.f90 has wrong values for instruments OMI, GOME and OMPS total column. The bug was fixed in this branch

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@HaixiaLiu-NOAA I don't think we want this merged into GSI master, do we? I think @emilyhcliu  wanted my feature/files_for_jedi fork to be the one to use, but I'm open to having someone else host it. https://github.com/CoryMartin-NOAA/GSI/tree/feature/files_for_jedi

**Comment by emilyhcliu** [comment]
@HaixiaLiu-NOAA I think you should only have one file (**setupoz.f90**) change to be merged to feature/files_for_jed, correct?

**Comment by HaixiaLiu-NOAA** [comment]
Yes, only setupoz.f90 was modified. 

Did I do this pull request wrong? How should I fix it? This is not going into GSI master, just Cory's branch feature/files_for_jedi. How should I do this?

**Comment by emilyhcliu** [comment]
@HaixiaLiu-NOAA I think you will need to submit this PR under Cory's forked GSI.  
You can check out a fresh new feature/files_for_jedi from Cory's forked GSI again (following the notes I put on the ZenHub), and then modify the setupoz.f90. This is probably easier than trying to undo things in your current feature/files_for_jedi.  After that, you do "git status" and you should only see one file change (setupoz.f90).  Then you should be good to submit a PR under Cory's forked GSI for his review.

**Comment by CoryMartin-NOAA** [comment]
Issue the PR from your branch but choose my fork CoryMartin-NOAA:feature/files_for_jedi and not NOAA-EMC:master

**Comment by HaixiaLiu-NOAA** [comment]
command like this???

git push --set-upstream CoryMartin-NOAA feature/hliu_O3UFO_omi

instead of 

git push --set-upstream origin feature/hliu_O3UFO_omi

**Comment by HaixiaLiu-NOAA** [comment]
Or command line??

git push --set-upstream CoryMartin-NOAA feature/files_for_jedi

???

**Comment by emilyhcliu** [comment]
@HaixiaLiu-NOAA Just copy the line "git push --set-upstream CoryMartin-NOAA feature/files_for_jedi" at your command line and hit return.

**Comment by CoryMartin-NOAA** [comment]
@HaixiaLiu-NOAA did you clone my fork? or are you using your own fork? You probably won't have write permission to push to my fork.

**Comment by HaixiaLiu-NOAA** [comment]
Encountered the following error.

[Haixia.Liu@hfe06 GSI]$ git push --set-upstream CoryMartin-NOAA feature/files_for_jedi
remote: Permission to CoryMartin-NOAA/GSI.git denied to HaixiaLiu-NOAA.
fatal: unable to access 'https://github.com/CoryMartin-NOAA/GSI/': The requested URL returned error: 403

Below is what I did.

git clone --recursive gitfork:GSI  
cd GSI
git remote add upstream github:GSI
git remote add CoryMartin-NOAA https://github.com/CoryMartin-NOAA/GSI
git remote -v    (check remote repositories)
git remote update    (fetch and update all remote repositories)
git checkout -b feature/files_for_jedi CoryMartin-NOAA/feature/files_for_jedi
git checkout -b feature/files_for_jedi_o3merge
git push --set-upstream origin feature/files_for_jedi_o3merge

**Comment by CoryMartin-NOAA** [comment]
@HaixiaLiu-NOAA you need to push your commit to your fork and then on GitHub issue the PR to my branch. You won't be able to push to my repository unless I explicitly add you.

**Comment by HaixiaLiu-NOAA** [comment]
Cory, I think I did it wrong. It seems I issued a PR to your master rather than your branch feature/files_for_jedi.

**Pull request closed without merging**
