### PR TITLE
GitHub Issue NOAA-EMC/GSI#370: use nf90_inq_varid to set integer addresses for lon and lat variables

### LINKED ISSUE #370: unsafe interp_inc.fd/driver.f90 assumption
As currently coded `interp_inc.fd/driver.f90` assumes variables `lon` and `lat` are have the same integer addresses as dimensions `lon` and `lat` in the input netCDF file.  This is shown in the following block of code from `driver.f90` which loads the longitude array:

```
 error = nf90_inq_dimid(ncid_in, 'lon', id_dim)
 call netcdf_err(error, 'inquiring lon dimension for file='//trim(infile) )
 error = nf90_inquire_dimension(ncid_in, id_dim, len=lon_in)
 call netcdf_err(error, 'reading lon dimension for file='//trim(infile) )
 allocate(longitude_in(lon_in))
 error = nf90_get_var(ncid_in, id_dim, longitude_in)
 call netcdf_err(error, 'reading longitude_in for file='//trim(infile) )
```

We should not assume `id_dim` for the `lon` dimension is identical to `id_dim` for the `lon` variable.    Instead, we should query the location of variable `lon` prior to getting `lon`.   This is done by adding a call to `nf90_inq_varid` for variable `lon` prior to getting `lon`.

```
 error = nf90_inq_varid(ncid_in, 'lon', id_dim)
 call netcdf_err(error, 'inquiring var lon dimension for file='//trim(infile) )
 error = nf90_get_var(ncid_in, id_dim, longitude_in)
 call netcdf_err(error, 'reading longitude_in for file='//trim(infile) )
```

This issue is opened to document this problem and its resolution.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
Update `interp_calc.fd/driver.f90` to remove unsafe assumption described in issue #370.

**Problem**
The JEDI-GDAS atmospheric analysis increment has variables ordered:  `lev`, `pfull`, `ilev`, `hyai`, `hybi`, `lon`, `lat`, `u_inc`, etc.  GSI-GDAS parallels order analysis increment variables as `lon`, `lat`, `lev`, `pfull`, ilev`, `hyai`, 'hybi`, `u_inc`. etc.     The original `driver.f90` assumes the `lon` and `lat` dimensions are in the same order as variables `lon` and `lat`.  This is true for GSI-GDAS atminc.nc files.  It is not true for JEDI-GDAS atminc.nc files.  

When a GSI-GDAS based `interp_inc.x` processes a JEDI-GDAS atminc.nc file, the code fails with
```
 FATAL ERROR: reading longitude_in for file=siginc.nc.06:
 NetCDF: Start+count exceeds dimension bound
 STOP.
999
```

**Solution**
The solution is simple:  use `nf90_get_var` to retrieve the integer address for the target variable.

**Test**
This change was committed to [`feature/interp`](https://github.com/RussTreadon-NOAA/GSI/tree/feature/interp) at 83a8249.  The same JEDI-GDAS atminc.nc file was passed through the updated `interp_inc.x`.   The executable successfully ran to completion.    As an additional test the updated `interp_inc.x` was used to process a GSI-GDAS atminc file.   `interp_inc.x` ran to completion as expected.   The updated `driver.f90` no longer assumes dimensions and variables are in a particular order.

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]
Thank you @RussTreadon-NOAA for finding and fixing this. Additions look good to me.

**Comment by MichaelLueken** [comment]
@RussTreadon-NOAA I have merged the update that was out to the review committee.  Please update your PR to the latest develop in the authoritative repository using the following [guidance](https://github.com/NOAA-EMC/GSI/wiki/GSI-GitHub-General-User-Information#how-to-rebase-the-develop-branch-into-your-active-pr).  If you have any questions, please let me know.

**Comment by RussTreadon-NOAA** [comment]
@MichaelLueken-NOAA.   Thank you for the guidance.   The forked `feature/interp` has been updated to the current head of `develop` in the authoritative repository.

**Comment by MichaelLueken** [comment]
Since there are no changes to the source code and @CoryMartin-NOAA has reviewed these changes, I will now give final approval and merge this work to the authoritative repository.

**Pull request merged**
