### PR TITLE
update NMC_bkerror utility to handle netcdf gaussian grid history files

### PR DESCRIPTION
**Pull request by jswhit**
closes issue #53

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
Hi Jeff,

Since the changes in this PR can be merged to the master without going out to the review committee: 

1) Please squash merge the contents of jswhit/GSI/feature/NMC_Bkerror_ncio into a temporary fresh branch of the master.
2) Please have the following in the commit message:
    GitHub Issue NOAA-EMC/GSI#53.  Update NMC_bkerror utility to handle netcdf gaussian grid history files.
3) Please create a new PR from this new temporary branch.
4) I will approve the merge and get these changes in.

If you have any questions, please let me know.

Thanks,

Mike

**Comment by jswhit2** [comment]
@MichaelLueken-NOAA I have updated my fork to NOAA-EMC/master and have added your suggested commit message.

**Comment by aerorahul** [comment]
@jswhit 
The utilities have been moved to https://github.com/NOAA-EMC/GSI-utils
I can open a PR with these source code changes in that repository if you would like.  Is there someone you would like to ask to review?
The shell scripts added seem very specific to your user space.

**Comment by aerorahul** [comment]
Obsolete.
Closing.

**Pull request closed without merging**
