### PR TITLE
Turn on Met-10 AMVs

### PR DESCRIPTION
**Pull request by ADCollard**
Turns on Met-10 AMVs.  This is type 57 in global_convinfo.txt.  This is due to an emergency switch of Meteosat satellites scheduled for March 20 2023.

To actually access the changes the following commands must be executed:
```
git clone --recursive https://github.com/ADCollard/GSI.git -b release/gfsda.v16
git submodule sync
git submodule update
cd fix
```

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Not at all - as we have no test data.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
The change to the fix submodule hash brings in a change to `global_convinfo.txt`.   The following usage flags are changed

- uv 243 57 usage is changed from -1 to 1
- uv 253 57 usage is changed from -1 to 1
- uv 254 57 usage is changed from -1 to 1

According to ObsProc table [_Satellite and radar data used by Global GFS/GDAS, NAM and Rapid Refresh/High-Resolution Rapid Refresh GSI analysis_](https://www.emc.ncep.noaa.gov/emc/pages/infrastructure/obs-data/prepbufr.doc/table_18.php), report types [243, 253, 254], subtype 57 are METEOSAT-10.

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , the change to the fix hash and specifically, `global_convinfo.txt` looks correct.   I'll approve and merge after @ilianagenkova and/or @BrettHoover-NOAA approve this PR.

Comparison of `ADCollard:release/gfsda.v16` with `/lfs/h1/ops/prod/packages/gfs.v16.3.6/sorc/gsi.fd` found another difference.

NCO's copy of `scripts/exglobal_atmos_analysis.sh` does **NOT** include the commenting out of `GMI1CRBF`.   This is odd but a more careful check shows that `/lfs/h1/ops/prod/packages/gfs.v16.3.6/scripts/exglobal_atmos_analysis.sh` contains the change.   I guess NCO used `cp` to update `scripts` but failed to also update `sorc/gsi.fd/scripts/exglobal_atmos_analysis.sh`.

When NCO installs the updated GFS package `exglobal_atmos_analysis.sh` will be consistent between the two locations.

**Comment by ADCollard** [comment]
@RussTreadon-NOAA Thanks for this.

Just to be clear, the update to gfs.v16.3.6 did absolutely nothing to operations?  I should have checked the final implementation, I guess, but I assumed that if the package contained the change it would be in the final location too.  Should we highlight this to NCO, or just check extra carefully next time?

@BrettHoover-NOAA @ilianagenkova I consider this good to go, but would like conformation from one of you that this is correct.

**Comment by BrettHoover-NOAA** [comment]
@ADCollard @RussTreadon-NOAA is there a way for me to actually view the changes? When I go to the `Files Changed` tab all I see is this:
Screenshot 2023-03-03 at 9 27 31 AM

**Comment by ADCollard** [comment]
@BrettHoover-NOAA Unless @RussTreadon-NOAA knows a trick that I do not, the only way I am aware of is to go through the following process:
```
git clone --recursive https://github.com/ADCollard/GSI.git -b release/gfsda.v16
git submodule sync
git submodule update
cd fix

```

**Comment by RussTreadon-NOAA** [comment]
@BrettHoover-NOAA , I followed the procedure @ADCollard outlined.   I'm unable to pull up GSI-fix branches in Vlab.

**Comment by BrettHoover-NOAA** [comment]
Yeah, I just tried to follow Andrew's instructions for both his branch and the base branch, and the global_convinfo.txt files are identical

**Comment by BrettHoover-NOAA** [comment]
The change to the fix submodule hash that @RussTreadon-NOAA describes in the thread looks right to me, in this instance is it advisable to to provide a review recommendation based on that alone?

**Comment by ADCollard** [comment]
> Yeah, I just tried to follow Andrew's instructions for both his branch and the base branch, and the global_convinfo.txt files are identical

This should not be.  Type 57 should be off in the base version and on in my fork.  Let me double check.....

**Comment by BrettHoover-NOAA** [comment]
I got it: it turns out that the git clone has to explicitly specify the branch, otherwise it's reverting to cloning develop. So
```
git clone --recursive https://github.com/ADCollard/GSI.git -b release/gfsda.v16
git submodule sync
git submodule update
cd fix
```
appears to work. Differences are below:
`<` == base branch
`>` == new branch

```
125c125
<  uv       243   57   -1     3.0      0      0      0   1.5  15.0   1.4   1.5  0.055000     1  200.   100.      0    0.     2.   15   -8
---
>  uv       243   57    1     3.0      0      0      0   1.5  15.0   1.4   1.5  0.055000     1  200.   100.      0    0.     2.   15   -8
175c175
<  uv       253   57   -1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
---
>  uv       253   57    1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
181c181
<  uv       254   57   -1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
---
>  uv       254   57    1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
```

If this is the extent of the differences, things look good to me.

**Review by BrettHoover-NOAA — APPROVED** [review]
Based on examination of the global_convinfo.txt file, presuming no other changes have taken place

**Comment by ADCollard** [comment]
> I got it: it turns out that the git clone has to explicitly specify the branch, otherwise it's reverting to cloning develop. So
> 
> ```
> git clone --recursive https://github.com/ADCollard/GSI.git -b release/gfsda.v16
> git submodule sync
> git submodule update
> cd fix
> ```
> 
> appears to work. Differences are below: `<` == base branch `>` == new branch
> 
> ```
> 125c125
> <  uv       243   57   -1     3.0      0      0      0   1.5  15.0   1.4   1.5  0.055000     1  200.   100.      0    0.     2.   15   -8
> ---
> >  uv       243   57    1     3.0      0      0      0   1.5  15.0   1.4   1.5  0.055000     1  200.   100.      0    0.     2.   15   -8
> 175c175
> <  uv       253   57   -1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
> ---
> >  uv       253   57    1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
> 181c181
> <  uv       254   57   -1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
> ---
> >  uv       254   57    1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
> ```
> 
> If this is the extent of the differences, things look good to me.

@BrettHoover-NOAA D'oh!  My mistake.   I edited the instructions to ensure there is no confusion going forward.

**Comment by ADCollard** [comment]
> Based on examination of the global_convinfo.txt file, presuming no other changes have taken place

Thanks @BrettHoover-NOAA

**Review by RussTreadon-NOAA — APPROVED** [review]
I concur with @BrettHoover-NOAA .  Changes approved.

I'll wait until 1 pm EST before merging in case @ilianagenkova wants to look over the changes.

**Comment by BrettHoover-NOAA** [comment]
It seems like a fix submodule change is a gap in the normal repository update/review workflow, would it be worth raising this as a problem encountered in the monthly report? This change is small and contained to a single file so it's well insulated from human error and introducing unreported code changes, but I can imagine that a more complex change to the submodule could be prone to letting errors slip in.

**Comment by RussTreadon-NOAA** [comment]
Given @KateFriedman-NOAA's schedule, I will merge this PR now and create GSI tag gfsda.v16.3.7.   

g-w issue [#1368](https://github.com/NOAA-EMC/global-workflow/issues/1368) will be updated after the tag is created.

**Comment by RussTreadon-NOAA** [comment]
**Final documentation**  

[gfsda.v16.3.7](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.7) was created as a copy of [release/gfsda.v16](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) at a25590c1.

g-w issue [#1368](https://github.com/NOAA-EMC/global-workflow/issues/1368) was [updated](https://github.com/NOAA-EMC/global-workflow/issues/1368#issuecomment-1453827277) accordingly.

**Comment by RussTreadon-NOAA** [comment]
> It seems like a fix submodule change is a gap in the normal repository update/review workflow, would it be worth raising this as a problem encountered in the monthly report? This change is small and contained to a single file so it's well insulated from human error and introducing unreported code changes, but I can imagine that a more complex change to the submodule could be prone to letting errors slip in.

You are right.  A lot can be hidden in the change to the fix submodule.   Extra care needs to be taken when updating fix.   

The fact that operational GSI fix files are in gerrit:GSI-fix complicates matters further.   GFS v17 will use [NOAA-EMC/GSI-fix](https://github.com/NOAA-EMC/GSI-fix).  We still have the submodule issue but at least it will be easier to see what changed.

Note that NOAA-EMC/GSI-fix only contains ASCII GSI fix files.  EIB stages binary GSI fix files on WCOSS2 and other NOAA RDHPCS machines.  We do not, yet, have a good way to version control binary GSI fix files.

**Comment by ilianagenkova** [comment]
The changes look good!

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , while we updated `global_convinfo.txt` in gerrit:GSI-fix, file [`global_convinfo.txt`](https://github.com/NOAA-EMC/GSI-fix/blob/develop/global_convinfo.txt) in NOAA-EMC/GSI-fix was not updated.   NOAA-EMC/GSI `develop` pulls ASCII fix from NOAA-EMC/GSI-fix.    

I think an issue should be opened in [NOAA-EMC/GSI-fix](https://github.com/NOAA-EMC/GSI-fix) to document & capture the gfs.v16.3.7 update to `global_convinfo.txt`.  What do you think?

**Pull request merged**
