### PR TITLE
Update GH CI workflows

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
**Description**

This updates the workflows for apparent recent updates to the GH CI environment.

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing tests pass with my changes

### CODE REVIEW

**Review by CoryMartin-NOAA — DISMISSED** [review]

**Review by RussTreadon-NOAA — DISMISSED** [review]
Didn't test but assume it works.

Approve.

**Comment by RussTreadon-NOAA** [comment]
Workflow tests are still failing

**Comment by DavidHuber-NOAA** [comment]
This isn't working yet.  There are still issues with both the GCC and Intel builds.  I'm waiting for @AlexanderRichert-NOAA to get a look at this.

**Comment by AlexanderRichert-NOAA** [comment]
For the GCC/gsi failure, it looks like it's not finding libblas. In the most recent successful run of that workflow, it found /usr/lib/x86_64-linux-gnu/libblas.so, so I'm assuming this is what you want. I don't see it being explicitly installed anywhere, so maybe it was installed by default previously but got removed from the runner image? In any case, I would try `sudo apt install libblas-dev` and see if that does the trick.

I'll see if I can narrow down which command is failing in the Intel/build job.

**Comment by AlexanderRichert-NOAA** [comment]
The issue with the intel one is your `[[ ! -z "${...}" ]]` line-- I'm not sure the exact issue, but in any case using `if [[ ... ]]; then ...` seems to fix it.

**Comment by DavidHuber-NOAA** [comment]
Ah good calls, thanks @AlexanderRichert-NOAA!  I'll give those a shot.

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA I was able to get a bit further, but both builds are still failing.

For GCC, mpich (`mpicc`) is looking for gcc-10 in `/usr/bin` instead of looking in the spack environment.  And earlier (during the setup stage), it appears that the environment is using /usr/bin/gcc-10 in the environment, so I'm not sure why it cannot find it during the gsi stage.  Do you have an idea on what is missing here?

For Intel, it is failing to build `snappy` as there are undefined symbols (e.g. `_Float32`).  I believe it is trying to get these symbols from GCC, but I'm not sure.  Did spack-stack have to do anything special to build snappy with Intel compilers?

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA The GCC build is now working, but I am still having issues with the Intel `snappy` build.  When you have a second, would you mind taking a look?

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA :  Does [spack](https://github.com/spack/spack) issue [#48152](https://github.com/spack/spack/pull/48152) provide any clues as to how to get GSI CI workflows to work again?

**Comment by DavidHuber-NOAA** [comment]
I don't think so, but we can certainly try an older Ubuntu.  I'll give that a shot this morning.

On a side note, I spoke with @aerorahul about this yesterday who suggested a containerized GH runner may be a better way to go in the long run.  EPIC is working on containers that we could potentially use for this case, but they are a ways off yet.  Thus, it's not something that will fix the current issue, but will hopefully make for a more stable option in the future.

**Comment by RussTreadon-NOAA** [comment]
Thank you @DavidHuber-NOAA for the update and working on this as time permits.  I confess that I don't understand much about this part of the GSI repo or github.   Is there a way to experiment with ideas without pushing changes to a branch in the GSI repo?

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA It may be possible to set up an image on a cloud instance and try building via spack there, though I don't think the same Ubuntu image is available, so it wouldn't be a 1-to-1 representation.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA .  Several GSI-based repos contain the same workflow scripts and are encountering the same failure (e.g, GSI-utils PR [#59](https://github.com/NOAA-EMC/GSI-utils/pull/59)).  Are any other non-GSI EMC repos running similar CI but **not** experiencing the same problem?  If _yes_, can we apply their approach in GSI repos?

**Comment by DavidHuber-NOAA** [comment]
The ufs_utils has a similar setup and it looks like @alexanderrichert-noaa just fixed the Intel builds in https://github.com/ufs-community/UFS_UTILS/pull/998, though it appears that he moved to the new LLVM compilers.  I can see if a hybrid approach will work.

**Comment by RussTreadon-NOAA** [comment]
OK.  Thank you @DavidHuber-NOAA  ... but only work on this as your other tasks and priorities allow.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA :  gcc passes but intel fails.  The intel failure is with spack. I see [ubuntu-ci-x86_64-intel.yaml](https://github.com/JCSDA/spack-stack/blob/develop/.github/workflows/ubuntu-ci-x86_64-intel.yaml) in `spack-stack/.github/workflows`.  

Can the [spack-stack](https://github.com/JCSDA/spack-stack) team help us resolve this problem?

**Comment by AlexanderRichert-NOAA** [comment]
I'm looking at this right now. Disabling blosc eliminates the snappy dependency, so that problem goes away, but now it's failing on building netcdf-c because it can't find hdf5... I'll let you know when I have a fix.

**Comment by RussTreadon-NOAA** [comment]
Thank you @AlexanderRichert-NOAA .  Sorry that this has become such a time consuming endeavor for @DavidHuber-NOAA and you.

**Comment by AlexanderRichert-NOAA** [comment]
@DavidHuber-NOAA please check out my version of your branch, it seems to be working with Intel classic (it looks like you made some more recent updates involving oneAPI which I have not incorporated). The highlights are that it relocates /usr/local (I think this was messing up cmake), installs external blas/lapack, and gets rid of the c-blosc dependency for netcdf-c.

**Comment by DavidHuber-NOAA** [comment]
Thanks @AlexanderRichert-NOAA I will give that a shot today.

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA @RussTreadon-NOAA The CI builds are appear to again be working!!  Marking this PR ready for review.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by RussTreadon-NOAA — APPROVED** [review]
github CI passes.  

Approve.

**Comment by RussTreadon-NOAA** [comment]
Thank you @CoryMartin-NOAA for the review and approval.   @ShunLiu-NOAA and @hu5970 , this PR is ready for merger into `develop`.  If you're OK with the PR, any of us can merge it into `develop`.

**Pull request merged**
