### PR TITLE
EFSOI additions to jobs directory for issue #118

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
Changes to jobs directory:

	new file:   jobs/JGDAS_EFSOI
	new file:   jobs/JGDAS_EFSOI_ECEN
	new file:   jobs/JGDAS_EFSOI_FCST
	new file:   jobs/JGDAS_EFSOI_POST
	new file:   jobs/JGDAS_EFSOI_SFC
	new file:   jobs/JGDAS_EFSOI_UPDATE

Each of these files is needed to set up the environment for EFSOI-specific tasks; some call existing scripts, others need scripts specific to EFSOI

### CODE REVIEW

**Comment by AndrewEichmann-NOAA** [comment]
tagging @aerorahul @CatherineThomas-NOAA @MichaelLueken-NOAA (Liaofan not taggable)

**Review by CatherineThomas-NOAA — APPROVED** [review]
These job scripts are straightforward and separated from the rest of the workflow.  I have no issues here.

**Comment by MichaelLueken-NOAA** [comment]
Hi @AndrewEichmann-NOAA ,

Since both @aerorahul and @CatherineThomas-NOAA have approved this PR, I can go ahead and merge this work into the master.  Before I do this, please clean up the commit messages using the following commands:

1) Checkout your EXP-efso_fv3_PR_jobs branch
    * git checkout EXP-efso_fv3_PR_jobs

2) Rebase the NOAA-EMC/GSI master into your PR branch:
    * git remote add upstream git@github.com:NOAA-EMC/GSI.git
    * git remote update
    * git rebase upstream/master
    * vi CMakeLists.txt
    * Please remove lines 263 and 276 - 287.
    * git add CMakeLists.txt
    * git rebase --continue
    * vi CMakeLists.txt
    * Please remove lines 263 and 275 - 282.
    * git add CMakeLists.txt
    * git rebase --continue

3) Clean up commit messages:
    * git reset --soft HEAD~1
    * git reset --soft HEAD~1
    * git reset --soft HEAD~1
    * git reset --soft HEAD~1
    * git reset --soft HEAD~1
    * git reset --soft HEAD~1
    * git reset --soft HEAD~1
    * git reset --soft HEAD~1

4) Commit and push back to the repository:
    * git commit -m "GitHub Issue NOAA-EMC/GSI#118. Implement EFSOI process in FV3 GFS workflow - EFSOI-specific additions to jobs."
    * git push origin EXP-efsoi_fv3_PR_jobs --force

If you have any questions, please let me know.

Mike

**Comment by AndrewEichmann-NOAA** [comment]
@MichaelLueken-NOAA, sorry for the late reply, I missed this. I applied your instructions and everything looked ok until the end:

(base) -bash-4.2$ git push origin EXP-efsoi_fv3_PR_jobs --force
error: src refspec EXP-efsoi_fv3_PR_jobs does not match any.
error: failed to push some refs to 'git@github.com:AndrewEichmann-NOAA/GSI.git'
(base) -bash-4.2$ 

Full session pasted below:


(base) -bash-4.2$ git checkout EXP-efso_fv3_PR_jobs
Switched to branch 'EXP-efso_fv3_PR_jobs'
Your branch is up to date with 'origin/EXP-efso_fv3_PR_jobs'.
(base) -bash-4.2$ git remote add upstream git@github.com:NOAA-EMC/GSI.git
(base) -bash-4.2$ git remote update
Fetching origin
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Total 6 (delta 5), reused 6 (delta 5), pack-reused 0
Unpacking objects: 100% (6/6), done.
From github.com:AndrewEichmann-NOAA/GSI
   b67bc7cf7..6e4f3a10d  EXP-efso_fv3 -> origin/EXP-efso_fv3
Fetching upstream
remote: Enumerating objects: 776, done.
remote: Counting objects: 100% (418/418), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 776 (delta 320), reused 394 (delta 317), pack-reused 358
Receiving objects: 100% (776/776), 417.63 KiB | 10.99 MiB/s, done.
Resolving deltas: 100% (489/489), completed with 134 local objects.
From github.com:NOAA-EMC/GSI
 * [new branch]          master                -> upstream/master
 * [new branch]          release/gefs_v12      -> upstream/release/gefs_v12
 * [new branch]          release/gfsda.v16.0.0 -> upstream/release/gfsda.v16.0.0
 * [new branch]          release/gfsda.v16.1.0 -> upstream/release/gfsda.v16.1.0
 * [new tag]             gefs_v12.0.2          -> gefs_v12.0.2
 * [new tag]             gfsda.v16.0.0_beta    -> gfsda.v16.0.0_beta
 * [new tag]             gfsda.v16.1.0         -> gfsda.v16.1.0
 * [new tag]             gefs_v12.0.1          -> gefs_v12.0.1
Fetching submodule fix
Total 7 (delta 4), reused 7 (delta 4)
From gerrit:GSI-fix
   d163aca..e92bfbd  DA_GFSv16.1_global_only -> origin/DA_GFSv16.1_global_only
   47b7485..24c6403  wdas                    -> origin/wdas
(base) -bash-4.2$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: seem to have to add these to merge in upstream
Applying: GitHub Issue NOAA-EMC/GSI#118.  Implement EFSOI process in FV3 GFS workflow (2nd try).
Using index info to reconstruct a base tree...
M	CMakeLists.txt
.git/rebase-apply/patch:31: trailing whitespace.
  endif(BUILD_UTIL)   
.git/rebase-apply/patch:34: trailing whitespace.
  endif(BUILD_EFSOI) 
.git/rebase-apply/patch:293: trailing whitespace.
export COMIN_ENS="$ROTDIR/efsoi$CDUMP_ENKF.$PDY/$cyc/$COMPONENT" 
.git/rebase-apply/patch:1285: trailing whitespace.
   $NAM_ENKF  
.git/rebase-apply/patch:1959: trailing whitespace.
   $NAM_ENKF  
warning: squelched 445 whitespace errors
warning: 450 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging CMakeLists.txt
CONFLICT (content): Merge conflict in CMakeLists.txt
error: Failed to merge in the changes.
Patch failed at 0002 GitHub Issue NOAA-EMC/GSI#118.  Implement EFSOI process in FV3 GFS workflow (2nd try).
Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

(base) -bash-4.2$ vi CMakeLists.txt 
(base) -bash-4.2$ git add CMakeLists.txt
(base) -bash-4.2$ git rebase --continue
Applying: GitHub Issue NOAA-EMC/GSI#118.  Implement EFSOI process in FV3 GFS workflow (2nd try).
Applying: Revert "GitHub Issue NOAA-EMC/GSI#118.  Implement EFSOI process in FV3 GFS workflow (2nd try)."
Using index info to reconstruct a base tree...
M	CMakeLists.txt
.git/rebase-apply/patch:34: trailing whitespace.
  endif(BUILD_UTIL) 
.git/rebase-apply/patch:2102: trailing whitespace.
if(fso_cycling) then  
warning: 2 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Removing util/EFSOI_Utilities/src/statevec_efsoi.f90
Removing util/EFSOI_Utilities/src/scatter_chunks_efsoi.f90
Removing util/EFSOI_Utilities/src/loc_advection.f90
Removing util/EFSOI_Utilities/src/loadbal_efsoi.f90
Removing util/EFSOI_Utilities/src/gridio_efsoi.f90
Removing util/EFSOI_Utilities/src/gridinfo_efsoi.f90
Removing util/EFSOI_Utilities/src/efsoi_main.f90
Removing util/EFSOI_Utilities/src/efsoi.f90
Removing util/EFSOI_Utilities/src/CMakeLists.txtORIG
Removing util/EFSOI_Utilities/src/CMakeLists.txt
Removing util/EFSOI_Utilities/scripts/read_osense.py
Removing util/EFSOI_Utilities/scripts/osense.py
Removing util/EFSOI_Utilities/scripts/getefsiofiles.sh
Removing util/EFSOI_Utilities/scripts/display_osense.py
Removing util/EFSOI_Utilities/scripts/copyefsoifiles.sh
Removing util/EFSOI_Utilities/scripts/convdata_codes.csv
Removing util/EFSOI_Utilities/scripts/README_fv3gfs
Removing util/EFSOI_Utilities/fix/global_anavinfo_efsoi.l127.txt
Removing scripts/exgdas_efsoi_update.sh
Removing scripts/exgdas_efsoi_fcst.sh
Removing scripts/exgdas_efsoi.sh
Removing jobs/JGDAS_EFSOI_UPDATE
Removing jobs/JGDAS_EFSOI_SFC
Removing jobs/JGDAS_EFSOI_POST
Removing jobs/JGDAS_EFSOI_FCST
Removing jobs/JGDAS_EFSOI_ECEN
Removing jobs/JGDAS_EFSOI
Auto-merging CMakeLists.txt
CONFLICT (content): Merge conflict in CMakeLists.txt
error: Failed to merge in the changes.
Patch failed at 0003 Revert "GitHub Issue NOAA-EMC/GSI#118.  Implement EFSOI process in FV3 GFS workflow (2nd try)."
Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

(base) -bash-4.2$ vi CMakeLists.txt
(base) -bash-4.2$ git add CMakeLists.txt
(base) -bash-4.2$ git rebase --continue
Applying: Revert "GitHub Issue NOAA-EMC/GSI#118.  Implement EFSOI process in FV3 GFS workflow (2nd try)."
Applying: GitHub Issue NOAA-EMC/GSI#118.  Implement EFSOI process in FV3 GFS workflow - EFSOI-specific fortran files
Applying: Squashed commit of the following:
Applying: Squashed commit of the following: mod to PR 124
Applying: removing EFSOI source files until they are merged into GSI master upstream
Applying: GitHub Issue NOAA-EMC/GSI#118.  Implement EFSOI process in FV3 GFS workflow.
(base) -bash-4.2$ git reset --soft HEAD~1
(base) -bash-4.2$ git reset --soft HEAD~1
(base) -bash-4.2$ git reset --soft HEAD~1
(base) -bash-4.2$ git reset --soft HEAD~1
(base) -bash-4.2$ git reset --soft HEAD~1
(base) -bash-4.2$ git reset --soft HEAD~1
(base) -bash-4.2$ git reset --soft HEAD~1
(base) -bash-4.2$ git reset --soft HEAD~1
(base) -bash-4.2$ git commit -m "GitHub Issue #118. Implement EFSOI process in FV3 GFS workflow - EFSOI-specific additions to jobs."
[EXP-efso_fv3_PR_jobs 0287141da] GitHub Issue #118. Implement EFSOI process in FV3 GFS workflow - EFSOI-specific additions to jobs.
 6 files changed, 830 insertions(+)
 create mode 100755 jobs/JGDAS_EFSOI
 create mode 100755 jobs/JGDAS_EFSOI_ECEN
 create mode 100755 jobs/JGDAS_EFSOI_FCST
 create mode 100755 jobs/JGDAS_EFSOI_POST
 create mode 100755 jobs/JGDAS_EFSOI_SFC
 create mode 100755 jobs/JGDAS_EFSOI_UPDATE
(base) -bash-4.2$ ls jobs/
JGDAS_ATMOS_ANALYSIS_DIAG   JGDAS_EFSOI_FCST    JGDAS_ENKF_DIAG  JGDAS_ENKF_SELECT_OBS   JGLOBAL_ATMOS_ANALYSIS_CALC
JGDAS_ATMOS_CHGRES_FORENKF  JGDAS_EFSOI_POST    JGDAS_ENKF_ECEN  JGDAS_ENKF_SFC
JGDAS_EFSOI                 JGDAS_EFSOI_SFC     JGDAS_ENKF_FCST  JGDAS_ENKF_UPDATE
JGDAS_EFSOI_ECEN            JGDAS_EFSOI_UPDATE  JGDAS_ENKF_POST  JGLOBAL_ATMOS_ANALYSIS
(base) -bash-4.2$ git push origin EXP-efsoi_fv3_PR_jobs --force
error: src refspec EXP-efsoi_fv3_PR_jobs does not match any.
error: failed to push some refs to 'git@github.com:AndrewEichmann-NOAA/GSI.git'
(base) -bash-4.2$

**Comment by MichaelLueken-NOAA** [comment]
@AndrewEichmann-NOAA, I haven't seen that message before.  Looking it up, it sounds like the six modified files weren't being properly updated.  I was able to clone your fork, make the changes, then push, resulting in the current hash, 
62c884c.  There is work currently out to the review committee, but once that work has been merged, then I will be able to merge this work into the NOAA-EMC/GSI master.

**Pull request merged**
