### PR TITLE
Github issue #378: refactoring of EFSOI scripts and compiled code (EFSOI and EFSOI forecast scripts)

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
exgdas_efsoi_fcst.sh: removed because not used
exgdas_efsoi.sh: lines removed

### CODE REVIEW

**Comment by AndrewEichmann-NOAA** [comment]
@MichaelLueken-NOAA Github says this has no conflicts and is offering me a button to merge the pull request. Is this ok to go through with?

**Comment by MichaelLueken** [comment]
@AndrewEichmann-NOAA I have two minor updates to get in, then I will go ahead and merge this work to the authoritative repository.  Have you completed the EFSOI documentation?  I see that you were successfully able to create a new wiki:

https://github.com/NOAA-EMC/GSI/wiki/Using-EFSOI-with-GSI

If you are done, then I will remove your write permission.

Thanks.

**Comment by MichaelLueken** [comment]
Since there are no changes to the source code and the two scripts were cleaned and removed, I will now give final approval to this update and merge them to the authoritative repository.

**Comment by AndrewEichmann-NOAA** [comment]
@MichaelLueken-NOAA Thank you!

Regarding the manual, I'm still in the process of writing it - I had a basic outline earlier but expect to be working on it for a while.

**Pull request merged**
