### PR TITLE
Issue #91:  use communicator in global parallel netcdf read

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
PR to update GSI global parallel netcdf read to use communicator.   Details provided in issue #91.

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
Hi Russ,

Who would you like to have review this update?

Thanks,

Mike

**Review by CoryMartin-NOAA — APPROVED** [review]
Looks good to me, thanks @RussTreadon-NOAA for making this more flexible.

**Comment by RussTreadon-NOAA** [comment]
Regression tests run on Mars using NOAA-EMC:master @ 84eb5e9 as control and RussTreadon-NOAA:master @ cc4222c as update.   All regression tests, except global_C96_fv3aerorad, passed.    That the regression tests pass is an expected result since the changes in this PR do not alter the analysis.  Furthermore the changes in this PR are limited to global applications using parallel netcdf i/o.   

Regression test global_C96_fv3aerorad failed due to the global_gsi.x wall time exceeding the maximum allowable operational time of 1200 seconds.   The loproc_updat test completed with a wall time of 1297.820396 seconds.  The loproc_contrl completed with a wall time of 1301.758018 seconds.   The minimization statistics and analysis files created by these runs are identical.   The loproc results are identical with the hiproc results.   The setting "maxtime=1200" in regression_test.sh may need to be increased to avoid flagging this test as FAIL.   Alternatively, the loproc configuration could be modified to reduce the job run time.

**Comment by RussTreadon-NOAA** [comment]
Thanks, @CoryMartin-NOAA, for the quick review and approval.

**Comment by RussTreadon-NOAA** [comment]
Recompile updat code in DEBUG mode using debug crtm.   Set debug=".true. in regression/regression_var.sh.   Execute 19 ctests.   18 of the tests successfully ran and finished with rc=0.   global_T62_ozonly failed with rc=134 and the following message in stdout

```
 tpause: Warning, user request pv-based method toidentify tropaupose,
 but not all fields needed are available, resetting
 method to temperature-based one
forrtl: error (65): floating invalid
```
This failure is expected.   It is known that global_T62_ozonly does not run to completion in DEBUG mode.

**Comment by RussTreadon-NOAA** [comment]
After consultation with Mike, follow procedure outlined under "[How to rebase the master into your active PR](https://github.com/NOAA-EMC/GSI/wiki/GSI-GitHub-General-User-Information#how-to-rebase-the-master-into-your-active-pr)" to bring NOAA-EMC:master at ec2d22d into RussTreadon-NOAA:master.  Done at 3f7e286.

**Comment by MichaelLueken-NOAA** [comment]
The due date for this update has past with no feedback from the review committee, so I will give final approval to this update and merge it to the NOAA-EMC/GSI master.

**Pull request merged**
