### PR TITLE
bump bufr version to 11.7.0

### LINKED ISSUE #470: Bump bufr version to 11.6.0+
It was found that the GSI produces warnings such as these, when compiled w/ bufr 11.4.0 statically allocated library.

```
++++++++++++++++++++WARNING+++++++++++++++++++++
 BUFRLIB: ISETPRM - DYNAMIC MEMORY ALLOCATION IS NOT SUPPORTED FOR THIS BUILD OF BUFRLIB
 ++++++++++++++++++++WARNING+++++++++++++++++++++
```

Updating to 11.6.0+ will result in no such warning.  Also using the 11.4.0 `_DA` library would be acceptable.

### PR DESCRIPTION
**Pull request by aerorahul**
This PR bumps the version of the bufr library to 11.7.0.
Updates the modulefiles as well as the CI environment.

Fixes #470

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
I can not comment on the changes to `gcc.yml`, `intel.yml`, or `spack.yaml`.   I don't know what these files do.   

It makes sense that the bufr version is increased in `spack.yaml` from `11.5.0` to `11.7.0`.   I am familiar with the change to `gsi.common.lua`   That's the purpose of this PR - increase the bufr version to `11.7.0`.

Tests using `bufr/11.7.0` in `release/gfsda.v16.3.0` on Cactus found no change in analysis results when moving to `bufr/11.7.0`     With the move to `bufr/11.7.0` the runtime `DYNAMIC MEMORY ALLOCATION ` message goes away.

Changes approved.

**Comment by aerorahul** [comment]
> I can not comment on the changes to `gcc.yml`, `intel.yml`, or `spack.yaml`. I don't know what these files do.
> 
> It makes sense that the bufr version is increased in `spack.yaml` from `11.5.0` to `11.7.0`. I am familiar with the change to `gsi.common.lua` That's the purpose of this PR - increase the bufr version to `11.7.0`.
> 
> Tests using `bufr/11.7.0` in `release/gfsda.v16.3.0` on Cactus found no change in analysis results when moving to `bufr/11.7.0` With the move to `bufr/11.7.0` the runtime `DYNAMIC MEMORY ALLOCATION ` message goes away.
> 
> Changes approved.

Thank you for the approval @RussTreadon-NOAA 

The `gcc.yaml` and `intel.yaml` are building the container with the GSI dependencies using the respective compiler.  The GSI dependencies are specified in the file `spack.yaml`.  The container is used to build the GSI as part of the continuous integration (CI) process using a Github Action.
Those can be viewed in the "[Checks](https://github.com/NOAA-EMC/GSI/pull/469/checks)" tab.  We can't run the regression tests, but at the very least we can build the GSI in the CI as a first gate towards review.

**Comment by RussTreadon-NOAA** [comment]
Thank you, @aerorahul , for explaining what the yaml files are doing.  It's good to learn new things.

**Review by jderber-NOAA — APPROVED** [review]
I am also not an expert on yml files, but the changes appear to be simple and are updating the BUFR library used in the GSI to 11.7.0.  This is necessary to allow the use of dynamic memory.  Several one-off experiments were performed by Russ to ensure that the same results were given and that performance was not degraded.

**Comment by CoryMartin-NOAA** [comment]
Changes were approved by 2 reviewers and CI tests pass for Intel and GNU. Additionally, I was able to build successfully on both Hera and Cactus. Given that these criteria are met, and that it is a relatively small change set, I will merge this PR.

**Pull request merged**
