### PR TITLE
GitHub Issue NOAA-EMC/GSI#302. Removal of libsrc from the authoritative repository

### LINKED ISSUE #302: Removal of libsrc from the authoritative repository
With wrf_io/1.2.0 available via hpc-stack, there is no longer a reason for the GSI to maintain the libsrc submodule.  This issue will detail the steps taken to remove the libsrc submodule from the GSI and add wrf_io/1.2.0 to the modulefiles.  This work will be done in the [feature/libsrc_removal](https://github.com/MichaelLueken-NOAA/GSI/tree/feature/libsrc_removal) in my fork.

### PR DESCRIPTION
**Pull request by MichaelLueken-NOAA**
This update removes the dependence of the libsrc submodule from the GSI repository.  The libsrc entries in .gitmodules have been removed, the libsrc directory has been removed, and all modulefiles that have been updated to use hpc-stack have been updated to add `module load wrf_io/1.2.0`.  These changes were tested on WCOSS_D and Hera, where the code compiled without issue and the regression tests show bit reproducibility between this update and the current libsrc/wrflib executables.

Close #302

### CODE REVIEW

**Comment by aerorahul** [comment]
@MichaelLueken-NOAA 
The removal of `libsrc` as described in the PR looks good.

I have a follow on question.

There are references to `libsrc` in the build.
E.g. 
1. Lines 190-191 in the top-level `CMakeLists.txt`.  
2. In every `FindNCEPLIB.cmake` file e.g. `FindSIGIO.cmake` under `cmake/Modules` that will try to find, and if not found, build from the source expected to be in `libsrc`.
3. Some of the utility `CMakeLists.txt` e.g. `util/Correlated_Obs/CMakeLists.txt` are referencing `libsrc`. 

So, the question is, are these references to `libsrc` going to be removed/cleaned in a subsequent PR?

**Comment by MichaelLueken-NOAA** [comment]
@aerorahul Thank you very much for the review, Rahul.

Thanks for reminding me about the libsrc entries hardwired into the CMakeLists.txt files and the cmake/Modules/FindNCEPLIBS.cmake files.  As of this point, I have cleaned CMakeLists.txt and the cmake/Modules/Find* files.  On Monday, I will go through the CMakeLists.txt files in util to clean those up, then push the completed work.

**Comment by MichaelLueken-NOAA** [comment]
@aerorahul, I have removed libsrc from the CMakeLists.txt file (and CMakeLists.txt files in util) and from cmake/Modules/Find*.cmake.  I have removed findHelpers.cmake and removed libsrc from FindCORELIBS.cmake.  I have successfully compiled all DA components and ran the regression tests (both standard and debug) and all passed successfully.

**Comment by aerorahul** [comment]
@MichaelLueken-NOAA 
Removing references about `libsrc` in the CMakeLists.txt and other files looks good.

I noticed, however, that now that `libsrc` is gone, the build options such as `BUILD_CORELIBS` and other such as `BUILD_BACIO`, `BUILD_NEMSIO` etc make no sense.  
The third-partly libraries (including the NCEPLibs) are now expected to be present prior to building the GSI.

Do you anticipate removing those options and further cleaning up the `CMakeLists.txt` and other macros in a subsequent PR?  If so, that is fine.

**Comment by MichaelLueken-NOAA** [comment]
@aerorahul
Since changes related to BUILD_* options lie outside the scope of the removal of the libsrc submodule, I have created issue #331 to address this.

With your approval, I will commit this work to the authoritative repository tomorrow, Wednesday, March 9.

**Comment by MichaelLueken-NOAA** [comment]
Thank you very much for reviewing these changes, @aerorahul!  Since there are no source code changes, I will now give final approval to these changes and merge them to the authoritative repository.

**Pull request merged**
