### PR TITLE
GitHub Issue NOAA-EMC/GSI#123. OznMon update and bugzilla fixes.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**

### CODE REVIEW

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA after I issued the PR I found an issue with the copy script.  I have a fix that I've been testing over the weekend and if the logs look good tomorrow (Monday) I'll do an commit --append Mon. morning.  So please don't merge this until that happens.  Thanks!

**Comment by MichaelLueken-NOAA** [comment]
@EdwardSafford-NOAA Sounds good.  I'll hold off merging this work to the NOAA-EMC/GSI master until I have a final sign off from you.

**Comment by EdwardSafford-NOAA** [comment]
Hi @MichaelLueken-NOAA I've completed my update and committed the results.  I think I messed up though -- I see 3 commits instead of just 1.  I used --amend when I committed my change but I guess I am still missing something.  If I need to close this PR and start again I'll be glad to do that.

**Comment by MichaelLueken-NOAA** [comment]
Hi @EdwardSafford-NOAA to remove the extra two commits:

git reset --soft HEAD~1
git commit --amend
git push origin master --force

This should remove the extra two commits.

**Comment by EdwardSafford-NOAA** [comment]
Hi @MichaelLueken-NOAA   I see only one commit now.  Thanks as always for your help.

**Comment by MichaelLueken-NOAA** [comment]
Giving final approval and merging this work to the NOAA-EMC/GSI master.

**Pull request merged**
