### PR TITLE
GFS.v16.3 Implementation follow-up: Turn on VIIRS NPP/J1,  GOES-18 AMV winds, and Turn off GOES-17 AMV winds

### PR DESCRIPTION
**Pull request by emilyhcliu**
**Description**
Changes are made in the GSI fix directory for the following purposes:
1. Turn on VIIRS radiances from NPP and J1 for channels 12, 15, and 16
2. Turn on GOES-17 (271) AMV winds for types: 245 (IRLW), 246 (WVCT), and 247(WVCA) due to deteriorating conditions
3. Turn on GOES-18 (272) AMV winds for types: 245 (IRLW), 246 (WVCT), and 247(WVCA)

The feature branch was created from release/gfsda.16.3.0
Under Fix, a DA_GFSv16.3.1_global_only branch was created for add changes for VIIRS and G17/G18 AMV winds: (use flag change only)
- **global_satinfo.txt**
```
 viirs-m_npp            12   1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_npp            13  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_npp            14  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_npp            15   1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_npp            16   1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             12   1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             13  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_j1             14  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_j1             15   1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             16   1    0.620    0.000    6.000   10.000    0.000      1     -1     -1

```
- **global_convinfo.txt**

```
 uv       245  271   -1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
 uv       245  272    1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8

 uv       246  271   -1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
 uv       246  272    1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8

 uv       247  271   -1     3.0      0      0      0   2.5  20.0   1.4   2.5  0.005000     0    0.     0.      0    0.     0.   15   -8
 uv       247  272    1     3.0      0      0      0   2.5  20.0   1.4   2.5  0.005000     0    0.     0.      0    0.     0.   15   -8
```

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

  
**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
While the change to the fix submodule seems OK, I am unable to successfully pull the updated fix into a working copy of emilyhcliu:feature/gfsda.v16.3.1 on WCOSS2.   

- `git clone --recursive https://github.com/emilyhcliu/GSI.git .` works
- `git checkout feature/gfsda.v16.3.1` works
- `git status` works.  It returns

```
russ.treadon@clogin04:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr510> git status
On branch feature/gfsda.v16.3.1
Your branch is up to date with 'origin/feature/gfsda.v16.3.1'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   fix (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
```

- `git submodule sync` works
- `git submodule update` fails with

```
russ.treadon@clogin04:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr510> git submodule update
error: Server does not allow request for unadvertised object 2a1688d50794daa955a76e9728c3b6453d8dffe1
fatal: Fetched in submodule path 'fix', but it did not contain 2a1688d50794daa955a76e9728c3b6453d8dffe1. Direct fetching of that commit failed.
fatal: 
```

What am I doing wrong?    To which branch in gerrit:GSI-fix were changes committed?   Were the changes to this branch push back to gerrit?

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , thank you for pushing `DA_GFSv16.3.1_global_only` to `gerrit:GSI-fix`.   Now `git submodule update` works in my working copy of your fork `feature/gfsda.v16.3.1`.

**Review by RussTreadon-NOAA — COMMENTED** [review]
`git submodule update` now works.   Two files are changed
- `global_convinfo.txt`
   - subtype 271 usage flag set to -1 for types 245, 246, and 247
   - subtype 272 usage flag set to 1 for types 245, 245, and 247
- `global_satinfo.txt`
   - set usage flag to 1 for viirs-m_npp channels 12, 15, 16
   - set usage flag to 1 for viirs-m_j1 channels 12, 15, 16

The description for this PR states

`2. Turn on GOES-17 (271) AMV winds for types: 245 (IRLW), 246 (WVCT), and 247(WVCA) due to deteriorating conditions`

The PR title and convinfo list in the description suggest that _Turn on_ should read _Turn off_

**Comment by RussTreadon-NOAA** [comment]
Do we need to capture the changes to `global_convinfo.txt` and `global_satinfo.txt` in `fix/gfsv16_historical/gfsv16.3`?   I'm thinking about the future when we run retrospective parallels over this period.  We'll need to switch from one set of obs to the next.

**Comment by RussTreadon-NOAA** [comment]
> Do we need to capture the changes to `global_convinfo.txt` and `global_satinfo.txt` in `fix/gfsv16_historical/gfsv16.3`? I'm thinking about the future when we run retrospective parallels over this period. We'll need to switch from one set of obs to the next.

After discussing with @ADCollard , let's not pursue historical stuff in this PR.  Doing so adds an unnecessary change to gfsda.v16.3.5

**Review by ADCollard — APPROVED** [review]
Looks good

**Review by RussTreadon-NOAA — APPROVED** [review]
Approve

**Pull request merged**
