### PR TITLE
GitHub Issue NOAA-EMC/GSI#310 and #367. Correct RadMon's mean correction time series plots and update html generation.

### LINKED ISSUE #310: Fix RadMon time series plot problem
There are two problems with some of the RadMon time series plots:

1. The time plot for the sdv for mean correction is often all 0 values.  The sdv values are created by the extraction executable so the error must be occurring there.
2. Some time series plots do not use the user specified number of cycles but rather always plot 30 day intervals.

I'll tag @HaixiaLiu-NOAA so you will be notified automatically of my findings and progress on this.

### LINKED ISSUE #367: Update RadMon html generation
Recently several minor changes have been made to the html code on emcrzdm.  These changes need to be added to the RadMon's html generation scripts.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Fix the mean correction plots in the RadMon, which often displayed all 0 values for the sdv.  

This issue was traced back to the numerical format used in the files sent to the server.  The format did not include enough digits beyond the decimal point and often resulted in rounding to 0.  

Note that this improves the situation but more work needs to be done.  In the resulting plots the mouse-over values in the sdv plots, even when indicated they are non-zero, are still rounding to 0 in the mouse-over value display.  It may be possible to improve the javascript formatting of the data values.  It also may be that reverting to static plots might be a more satisfactory solution, though the ability to compare values on the fly would be lost.

@MichaelLueken-NOAA this change is trivial enough that I don't think a code review, beyond your once-over, is necessary.

### CODE REVIEW

**Comment by MichaelLueken** [comment]
Hi @EdwardSafford-NOAA.  This PR has four commits.  To reduce the number of commits:

1) git clone --recursive git@github.com:EdwardSafford-NOAA/GSI.git update
2) cd update
3) git reset --hard HEAD~1
4) git reset --hard HEAD~1
5) git reset --hard HEAD~1
6) git reset --hard HEAD~1
7) git remote add upstream https://github.com/NOAA-EMC/GSI.git
8) git remote update
9) git rebase upstream/develop
10) git submodule update
11) git checkout RadMon_310
12) git checkout develop
13) git merge --squash RadMon_310
14) git commit -m "`Github issue #310.  Correct mean correction time series plots.  Fixes #310.`"
15) git push origin develop --force

This will reduce the four commits to a single commit. This change should be merged to the authoritative develop branch next Tuesday (when the last of the GFS v16.x updates will be merged to develop).

If you have any questions, please let me know.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA I must have messed something up.  Now I have 5 commits instead of 4.  My guess is I messed up the transition from master to develop.  I did have problems quite a bit of a struggle with that, but thought I had it worked out.

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA.  What types of issues did you encounter while going through the previous steps?  It looks like you might have used `git pull` after following the original steps.  Please try:

1) git clone --recursive git@github.com:EdwardSafford-NOAA/GSI.git test
2) cd test
3) git reset --hard HEAD~1
4) git checkout RadMon_310
5) git checkout develop
6) git merge --squash RadMon_310
7) git commit -m "`Github issue #310.  Correct mean correction time series plots.  Fixes #310.`"

At this point, I have:
```
[Michael.Lueken@v71a2 test]$ git status
On branch develop
Your branch and 'origin/develop' have diverged,
and have 1 and 5 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

Please don't use the recommended `git pull` command.  This will add back in the removed commit messages and add another commit message as well.  Instead, please use:

git push origin develop --force

to push the change back to the repository.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA Thanks for your continued patience.  I *think* it's ok now.

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA Yep, everything looks good.  I should be able to merge this next Tuesday after the current work out to the review committee is merged.  Thank you very much for doing this!

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA  I have to offer apologies again for my incompetence.  I squash merged my 2nd dev branch, RadMon_367, into my develop branch and committed it with --amend and --no-edit, but I still managed to add 4 commits instead of just the one.  I have no idea how I messed up but I sure did.  Sorry for creating more work for you.  I'll be glad to fix it if you tell me how.

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA No worries.  Please try the following:

1) git clone --recursive git@github.com:EdwardSafford-NOAA/GSI.git test
2) cd test
3) git reset --hard HEAD~1
4) git reset --hard HEAD~1
5) git reset --hard HEAD~1
6) git reset --hard HEAD~1
7) git remote add upstream https://github.com/NOAA-EMC/GSI.git
8) git remote update
9) git rebase upstream/develop
10) git submodule update
11) git checkout RadMon_310
12) git checkout develop
13) git merge --squash RadMon_310
14) git commit -m "`Github issue #310. Correct mean correction time series plots. Fixes #310.`"
15) git checkout RadMon_367
16) git checkout develop
17) git merge --squash RadMon_367
18) git commit --amend
19) git push origin develop --force

These steps should allow you clone get both issue #310 and #367 changes into your fork's develop branch with only a single commit message.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA thanks as always for your help.  I think it's ok now.

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA Yep, everything looks good now.  I have also added issue #367 to the list of issues that can be closed with this PR.  Is there anyone you would like to have review the html changes, or should that not be required?

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA a review isn't essential; these changes are in the non-operational portion of the package and are not routinely used.  If @DavidHuber-NOAA  is free I'd welcome his $0.02, but I wouldn't hold up release if he's not able to look it over.

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good to me.  Thanks!

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA Please use the following commands to reduce the 2 commits to a single commit:

1) git clone --recursive git@github.com:EdwardSafford-NOAA/GSI.git update
2) cd update
3) git reset --hard HEAD~1
4) git remote add upstream https://github.com/NOAA-EMC/GSI.git
5) git remote update
6) git rebase upstream/develop
7) git push origin develop --force

Thanks!

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA sorry, I got ahead of things and updated my develop branch from upstream, forgetting that would mess up this PR.

**Comment by MichaelLueken** [comment]
Since there are no source code changes and @DavidHuber-NOAA has reviewed the changes, will now give final approval to these changes and merge them to the authoritative repository.

**Comment by aerorahul** [comment]
Why was a tarball `sum_thumbs.tar` with thumbnail sized pngs included in this PR?

**Comment by EdwardSafford-NOAA** [comment]
The pngs are used by the RadMon's website building script on the splash page.  I guess the thumbs could be left on the server and manipulated remotely, but it made sense to me to put all the RadMon html related files in one place.  Also, from what I've heard there is no backup for emcrzdm, so a copy might be useful.

**Comment by aerorahul** [comment]
> The pngs are used by the RadMon's website building script on the splash page. I guess the thumbs could be left on the server and manipulated remotely, but it made sense to me to put all the RadMon html related files in one place. Also, from what I've heard there is no backup for emcrzdm, so a copy might be useful.

Generally speaking, committing binary files to a git repository is not recommended.
This is so because Git cannot diff a binary file.  It will upload the entire file into the repository and will store it as is forever.
If there is going to be an update to the binary file, Git will upload another copy (rather than the diff), thereby increasing the size of the git repository.
When this repository is cloned, the clone will download every single version of the binary file; thus slowing down the clone.

NOAA-EMC does not pay for Git-LFS (a solution for storing binary files in Git on GitHub).

Having said that, if the thumbs will never be updated (.tar), then I think this will likely not be a concern.
I suspect, new thumbs will be added as new instruments get added, and thus this tar ball will be replaced with another one.

**Comment by EdwardSafford-NOAA** [comment]
@aerorahul Thanks for the detailed explanation.  I wasn't aware of the git issues with binary files.  

Yes, your sense is right -- the thumbs will change over time in response to changes in available instruments.  I'll make a point of replacing the file as needed rather than updating it.

**Comment by aerorahul** [comment]
@EdwardSafford-NOAA replacing the file is the same as adding new file.  The history will still contain the old file and a new file.  I don't think that changes anything. 
If you have:
```
thumbA.png
thumbB.png
thumbC.png
```
and then you add 
```
thumbD.png
```
then I think we can live with it.

But, if you replace `thumbA.png` with a newer version (copy) of `thumbA.png`, then the repo still stores 2 copies of `thumbA.png`; the original and the new.
If you are certain that once the thumbs are added, they won't be updated, then we can possibly live with it.
To do so this way, you will need to remove the tar and store the pngs as individual files in a png directory.

**Comment by EdwardSafford-NOAA** [comment]
@aerorahul The individual thumbs will never be updated -- there isn't any need for that.  I'll open a new issue to remove the tar and move the thumbs to a new png directory.

**Comment by aerorahul** [comment]
@EdwardSafford-NOAA 
Removing of binary files from history is a bit more involved.
Just removing the files do not remove it from the history.
Also, any branch that now have since been created after this went to `develop` now contain these binary files.

**Comment by EdwardSafford-NOAA** [comment]
@aerorahul Sorry, I had no idea the scope of this problem.  I'll investigate how to remove the binaries from history.

**Comment by EdwardSafford-NOAA** [comment]
@aerorahul  I read there are some tools that will assist with rewriting history but I assume they are not available.  I tested this solution locally:

> git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch util/Radiance_Monitor/image_gen/html/sum_thumbs.tar" HEAD~5..HEAD

That seems to work -- the file is removed and the last 5 commits are modified to remove all references to the tar file.  I assume that @MichaelLueken-NOAA would need to run this on the authoritative develop branch in order to really implement it.  As for branches created from develop since the merger (f16e852), I'm not yet sure how best to handle that.

**Comment by aerorahul** [comment]
@EdwardSafford-NOAA 
Excellent.  Thanks for the research on this.

I think any branch created since the merge will have to do the same on the branch on the users fork.

I am not sure about this next bit, but I think the `develop` branch on the users fork will also need to get a force push to remove the references to the binary files.  Or possibly, the user might have to fork again.  I am not sure about this bit, but I am certain something needs to be done with the `develop` branch that contains the traces of this file on the users fork.

But, as you can see, once a binary file gets in, it gets very difficult to get rid of its traces, especially when there is a large community involved.

**Comment by EdwardSafford-NOAA** [comment]
@aerorahul 
> But, as you can see, once a binary file gets in, it gets very difficult to get rid of its traces, especially when there is a large community involved.

That is **very** clear now.  I am really sorry my ignorance resulted in this mess.

I explored interactive rebase as well.  That's a bit less invasive, modifying only the f16e852 commit, but from what I read, it doesn't remove the associated history.  So I don't think that's the best option, though it looks like a useful thing to know about for use in less dire circumstances.

**Comment by EdwardSafford-NOAA** [comment]
@aerorahul @MichaelLueken-NOAA I've continued to investigate the options to remove the binary file.  From what I read, after the filter command on the authoritative develop branch, a push to the develop branch on user forks should be sufficient.  None of the sources I've read suggest re-forking is necessary.  That said, I can't rule that possibility out. 

If the decision is that we can live with the current situation, then I will not make any changes to the binary, ever.  If the filter process is deemed too cumbersome/risky, then I think I should go ahead and remove the binary (knowing that doesn't solve the problem, but it does prevent any change to teh binary and thus additional growth in the size of the repo).  I can adjust the install scripts to work around that and store the binary on the server (I have a local copy as well).

Thoughts?

**Comment by aerorahul** [comment]
@EdwardSafford-NOAA 
Thank you for your continued investigation.
I think at this time removing and filtering on the authoritative `develop` branch should suffice.
@MichaelLueken-NOAA could send out an email with the necessary steps to take for the users.

Is there a way for @MichaelLueken-NOAA to verify (for the next few PR's that come in), to ensure that they do not contain this binary file in their history.  This is just to ensure that the users did infact get the push to their `develop` after the filtering.

**Comment by EdwardSafford-NOAA** [comment]
@aerorahul Indeed there is.  

Running:
`git log --oneline -M --stat --follow -- util/Radiance_Monitor/image_gen/html/sum_thumbs.tar` 
- oneline = output compact as possible
- M = include file renames
- stat = report diff stat
- follow = follow file history

Returns this: 
`f16e8526 Github issue #310.  Correct mean correction time series plots.  Fixes #310.
 util/Radiance_Monitor/image_gen/html/sum_thumbs.tar | Bin 0 -> 204800 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)`

I cloned a new GSI repo, created a new branch, `testdev`, switched back to the `develop` branch, and ran the filter command:
`git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch util/Radiance_Monitor/image_gen/html/sum_thumbs.tar" HEAD~8..HEAD`

When I run the git log command (above) on branch `develop` it produces no reply -- the file is gone from both `develop` and the branch history.  But if I run it on `testdev`, the file exists and the git log command produces output as above.  

As a sanity check I then manually removed the file from `testdev` and retested the git log command:
`rm util/Radiance_Monitor/image_gen/html/sum_thumbs.tar`
`ls util/Radiance_Monitor/image_gen/html/sum_thumbs.tar
ls: cannot access util/Radiance_Monitor/image_gen/html/sum_thumbs.tar: No such file or directory`

The git log command on `testdev` then produces this result:
`git log --oneline -M --stat --follow -- util/Radiance_Monitor/image_gen/html/sum_thumbs.tar`
`f16e8526 Github issue #310.  Correct mean correction time series plots.  Fixes #310.
 util/Radiance_Monitor/image_gen/html/sum_thumbs.tar | Bin 0 -> 204800 bytes
 1 file changed, 0 insertions(+), 0 deletions(-)`

So I think running that git log command on candidate merger branches will do the trick.

**Comment by MichaelLueken** [comment]
@aerorahul @EdwardSafford-NOAA I have submitted an update to the review committee, so no changes will be made to the authoritative repository until that work has been approved and merged (next Wednesday).  Once the work has been merged, I will use the:

`git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch util/Radiance_Monitor/image_gen/html/sum_thumbs.tar" HEAD~10..HEAD`

command (10 rather than 8 due to the update to the develop branch this morning and the IR bug fix update middle of next week), and then let developers know to use the command in their forks so that the tar file and history are removed.

Thanks!

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA I'm good with that schedule.  

I'd like to do some experimentation as part of the filter, provided you're OK with it.  I want to set up two different clones before you run the filter command.  After you run the filter I'll do a force pull on one and run the same filter command on the other and compare results.  I'm just curious to see if both strategies work as I expect.  If they do then users will have some options.

Also I assume there's some sort of backup in place for the authoritative `develop` branch.  Everything I read about the filter command starts with some warning along the lines of "Danger Will Robinson!".  I didn't have any problems with experiments on my local, _expendable_, clone, but I'd hate to find out about unknown unknowns the hard way.

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA Yes, I don't do anything to the authoritative repository without having the authoritative develop branch cloned in a static location first (the control used for the regression testing).  So, not to worry there.  If there is an issue, I'd just force push this control local copy that doesn't include the filter command.

I'll let you know once PR #374 has been merged so that you can prep your experiment.  Once you give me the green light, I'll disseminate the filter command (or whatever the best path forward is, once it has been decided) to the users of the NOAA-EMC/GSI repository.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA I'm set up to run my experiments.  Just let me know when you've run the filter command on the upstream develop branch and I will proceed.

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA I have three updates to merge to the authoritative repository today, then I will move forward with the filter command.  I'll let you know through this PR when the filter command has been run.

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA I have force pushed the filter command now.  Please let me know once your experiment is complete so that I can let the developers know what they need to do to bring in the change.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA here's what I did.  I'll be glad to answer any questions.  Again, thanks for your patience and, while I regret making the mistake, I have learned a great deal about git as a result.

1.  I first used an existing cloned repo and did a force pull from upstream/develop:
`git pull -f upstream develop`
The log command showed the offending file was still in my branch and in the history.  I manually removed it but of course the history still contained the file.  Ratz, I thought that _might_ be an easy solution.  Not so. 

2.  I cloned a new repo (test1), pulled in the upstream updates:
'git pull upstream develop'
Then ran the filter (guessing 13 was the right number, maybe it's actually 12):
`git filter-branch --index-filter "git rm -rf ^M --cached --ignore-unmatch util/Radiance_Monitor/image_gen/html/sum_thumbs.tar" HEAD~13..HEAD`
The log command showed no history of the binary file, as expected.   Then I did
`git status`
`On branch develop`
`Your branch and 'origin/develop' have diverged,`
`and have 1 and 21 different commits each, respectively.`  
So I forced pushed develop to origin/develop.

3.  Lastly I cloned repo (test2), and confirmed the binary file and history were not present.  I pulled from upstream develop:
`git pull upstream develop`
`From https://github.com/NOAA-EMC/GSI`
 `* branch              develop    -> FETCH_HEAD`
`Already up-to-date.`

Summation:  I'm disappointed but not surprised to learn that a force pull from upstream/develop is insufficient to overwrite the local history.  But it looks like running the filter command on user's develop branch (followed by the log command to make sure the filter reached back far enough) will fix the problem.

I didn't try re-forking but I'm sure that would work too.

**Pull request merged**
