### PR TITLE
GitHub Issue NOAA-EMC/GSI#410. Remove ncdiag from gsi repo and replace with submodule

### LINKED ISSUE #410: (Re)move ncdiag source code from the GSI repository
`ncdiag` is used in the [GSI](https://github.com/noaa-emc/gsi), [GSI-monitor](https://github.com/noaa-emc/gsi-monitor) as well as in some JEDI based UFO evaluation applications.

This library is built every time the GSI is built and does not change often (or at all).  There has been no change to the source code till a bug fix for GNU update a month ago.

In order to make flexible use of this library in the variety of applications, (re)moving this library from the GSI and making it a part of library deployment e.g. similar to NCEPlibs, built and deployed on all relevant platforms with (hpc-stack)(https://github.com/noaa-emc/hpc-stack) (or spack-stack in the future).  The ownership of NCDiag will remain with the GSI owners.

The GSI and other applications will then simply load the `ncdiag` library for their purposes (like any other third-party library).

### PR DESCRIPTION
**Pull request by aerorahul**
Closes #410 

This PR:
- removes the `ncdiag` source code from the GSI repository
- replaces the `ncdiag` source code with a submodule pointer to [GSI-ncdiag](https://github.com/noaa-emc/gsi-ncdiag).

When [GSI-ncdiag](https://github.com/noaa-emc/gsi-ncdiag) is added to [hpc-stack](https://github.com/noaa-emc/hpc-stack), the submodule will be replaced with `module load ncdiag`.

### CODE REVIEW

**Comment by MichaelLueken** [comment]
@aerorahul The regression tests were run on WCOSS and all passed.  Please move forward with creating the `v1.0.0` tag in [GSI-ncdiag](https://github.com/NOAA-EMC/GSI-ncdiag) and updating the PR to point to the `v1.0.0` tag.  Please reduce the number of commits to 1 by using `git rest --soft HEAD~1` and using `git commit --amend`, followed by `git push origin feature/remove-ncdiag-from -gsi-repo  --force`.  Also, please ensure that your commit message includes the issue number `NOAA-EMC#410`.

**Comment by MichaelLueken** [comment]
@aerorahul These changes will be merged to the authoritative repository early next week, following the RAP/HRRR/RRFS update that has been submitted to the review committee.

**Comment by aerorahul** [comment]
> @aerorahul The regression tests were run on WCOSS and all passed. Please move forward with creating the `v1.0.0` tag in [GSI-ncdiag](https://github.com/NOAA-EMC/GSI-ncdiag) and updating the PR to point to the `v1.0.0` tag. Please reduce the number of commits to 1 by using `git rest --soft HEAD~1` and using `git commit --amend`, followed by `git push origin feature/remove-ncdiag-from -gsi-repo --force`. Also, please ensure that your commit message includes the issue number `NOAA-EMC#410`.

Done.

**Comment by MichaelLueken** [comment]
@aerorahul Thank you very much for addressing my comment!  I will be able to merge this work to the authoritative repository on Tuesday, June 21, following the RAP/HRRR/RRFS update from Ming.

**Comment by MichaelLueken** [comment]
These changes have been tested on WCOSS and Hera (using both Intel and GNU compilers), so I will now give final approval to these changes and merge them to the authoritative repository.

**Pull request merged**
