### PR TITLE
GitHub Issue NOAA-EMC/GSI#266.  remove global_cycle from DA jobs and scripts

### LINKED ISSUE #266: Move global_cycle out of global DA jobs and scripts.
This issue is opened to document the removal of global_cycle and gaussian_sfcanl from global DA jobs and scripts.  This functionality is moving into the global-workflow.    This refactoring is in support of the goals stated in the JEDI [Prototype 3DVar Cycling Capability](https://github.com/NOAA-EMC/JEDI-Eval/projects/2) project.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
The PR removes global_cycle from DA jobs and scripts.   global_cycle is part of the global workflow, not NOAA-EMC/GSI.   As such, this PR does not alter the behavior of applications specific to NOAA-EMC/GSI.

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Cross reference this PR with [g-w PR #871](https://github.com/NOAA-EMC/global-workflow/pull/871).   g-w [#871](https://github.com/NOAA-EMC/global-workflow/pull/871) adds global_cycle jobs and scripts to the g-w repo.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Thank you @GeorgeGayno-NOAA !

**Comment by RussTreadon-NOAA** [comment]
@MichaelLueken-NOAA , the changes in this PR have been reviewed and approved by @GeorgeGayno-NOAA .  Is there anything else you need me to do for this PR?

**Comment by MichaelLueken** [comment]
@RussTreadon-NOAA Everything looks good.  Since @GeorgeGayno-NOAA has approved your changes and the automated build passed (and there are no changes to the source code), I will give final approval and merge this PR to the authoritative develop branch.

**Pull request merged**
