### PR TITLE
GitHub Issue NOAA-EMC/GSI#435.  Remove jobs/ scripts/ and some from ush/

### LINKED ISSUE #435: Move GFS jjobs, ex and ush scripts to GFS application repository
This issue is to document moving the GFS scripting to global-workflow.

The following will be moved:

- All scripts under `jobs/`.
- All except [exurma2p5_gsianl.sh](https://github.com/NOAA-EMC/GSI/blob/1a3fb1340d68e5979573d89457557071297532cc/scripts/exurma2p5_gsianl.sh) from `scripts/`
[exurma2p5_gsianl.sh](https://github.com/NOAA-EMC/GSI/blob/1a3fb1340d68e5979573d89457557071297532cc/scripts/exurma2p5_gsianl.sh) will be deleted as NCO maintains a copy of this script in their subversion repository.  This was discussed w/ @ManuelPondeca-NOAA offline.
- The following from `ush/`:
[calcanl_gfs.py](https://github.com/NOAA-EMC/GSI/blob/1a3fb1340d68e5979573d89457557071297532cc/ush/calcanl_gfs.py)
[calcinc_gfs.py](https://github.com/NOAA-EMC/GSI/blob/1a3fb1340d68e5979573d89457557071297532cc/ush/calcinc_gfs.py)
[gsi_utils.py](https://github.com/NOAA-EMC/GSI/blob/1a3fb1340d68e5979573d89457557071297532cc/ush/gsi_utils.py)
[getgfsnctime](https://github.com/NOAA-EMC/GSI/blob/1a3fb1340d68e5979573d89457557071297532cc/ush/getgfsnctime)
[getncdimlen](https://github.com/NOAA-EMC/GSI/blob/1a3fb1340d68e5979573d89457557071297532cc/ush/getncdimlen)

### PR DESCRIPTION
**Pull request by aerorahul**
These files have been moved to the global-workflow.
See PR https://github.com/NOAA-EMC/global-workflow/pull/904
closes #435

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Please add @AndrewEichmann-NOAA as a reviewer since this PR includes EFSOI.

**Comment by MichaelLueken** [comment]
@aerorahul
Please add the issue to the commit message for this PR.  You can do this by using the following commands:

- git commit --amend
- Please add `GitHub Issue NOAA-EMC/GSI#435` to the commit message.
- Save and close the commit message window.
- git push origin feature/gsi-jobs-gone --force

**Review by AndrewEichmann-NOAA — APPROVED** [review]
Looks comprehensive

**Comment by aerorahul** [comment]
> @aerorahul Please add the issue to the commit message for this PR. You can do this by using the following commands:
> 
> * git commit --amend
> * Please add `GitHub Issue NOAA-EMC/GSI#435` to the commit message.
> * Save and close the commit message window.
> * git push origin feature/gsi-jobs-gone --force

Done

**Comment by MichaelLueken** [comment]
Since @AndrewEichmann-NOAA has given his approval to this update and there are no changes to the source code, I will now give final approval to this update and merge them to the authoritative develop branch.

**Pull request merged**
