### PR TITLE
GitHub Issue NOAA-EMC/GSI#62. Add support for gps data to ConMon

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
This is a partial implementation of gps support in the Conventional DA Monitor.  Data extraction, error reporting, and time series plots have been added for gps data sources.  

Other plot types will be added later via the PyGSI and emcpy packages as they become available.

### CODE REVIEW

**Comment by EdwardSafford-NOAA** [comment]
Changes have only been made to the ConMon package.

**Comment by MichaelLueken-NOAA** [comment]
@EdwardSafford-NOAA Please reduce the number of commit messages from three to one.  To do this:

1) git reset --soft HEAD~1
2) git commit --amend
3) Please save and close without changing commit message
4) git push origin master --force

This should remove the two additional commit messages and maintain the difference to util/Conventional_Monitor/nwprod/conmon_shared/ush/clean_tankdir.sh

I have an HWRF bug fix from Li that will go in first today, then I will be able to merge this ConMon update to the authoritative repository.

If you have any questions, please let me know.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA I've redone the commit per your instructions.  My apologies for my ongoing inability to use git; despite all evidence to the contrary I continue trying to do the right thing.

**Comment by MichaelLueken-NOAA** [comment]
There are no changes to the source code in this PR.  The regression tests were run and all passed.  All concerns have been addressed, so I will now give final approval and merge these changes to the authoritative repository.

**Pull request merged**
