### PR TITLE
Nceplibs update2

### PR DESCRIPTION
**Pull request by mark-a-potts**
This is an update to the GSI build system that works with the new NCEPLIBS and NCEPLIBS-external repos used with the public release of the UFS weather model and app. The idea is to require an installation of NCEPLIBS and NCEPLIBS-external (possibly just a partial install of that repo) rather than provide the source for all the dependent libraries ourselves. For that transition, I removed the libsrc submodule and moved ncdiag and wrflib under src. I also added a submodule for the cmake directory that is the same as the one used for the UFS. Because of this change, I moved the GSI-centric files out of cmake/Modules and put them in the GSI root directory (setHOST.cmake, platforms, setPlatformVariables.cmake, etc.). I am perfectly open to moving all of them into another subdirectory, if that is better. Currently, the submodule points to my fork of the CMakeModules repo, so we will have to coordinate on updating that to the official NOAA-EMC version. Finally, to build on a supported platform, a cmake version of 3+ is sufficient, but in order to build using the NCEPLIBS and NCEPLIBS-external, cmake version 3.16+ is required in order to correctly find all the dependencies. I am not sure how to address that other than via the README file (which I updated, but probably needs a bit more work).

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
Hi Mark,

I have not attempted to checkout this work at this time, but I do have some comments:

1) All PRs require a GitHub issue before the changes will be merged to the master.  Please ensure that you have created a new GitHub issue for this work.

2) With respect to wrflib, does the NCEPLIBS team have an ETA on when they will be porting wrfio v1.1.1 to GitHub?  It is available on VLab and modules are available on the Crays, Dells, and Hera, so it should also be included in GitHub.  The wrflib library doesn't belong in src in the GSI project.  We will need to remove wrflib from src, then add wrfio/1.1.1 to the modulefiles (and leave the community hanging in the breeze, since it isn't in GitHub), or we maintain libsrc, but only have wrflib within.

On Hera - wrfio/1.1.1, on Dell - wrfio/1.1.1, and on Cray - wrfio-intel/1.1.1.

I'm open to further discussion on the topic, but the GSI shouldn't be hamstringed because other groups aren't willing to fully port what they are responsible for.

3) I saw that the fix submodule had been removed and a link was added, pointing to ../ProdGSI/fix.  Please ensure that the fix submodule is properly added back in.

Mike

**Comment by guoqing-noaa** [comment]
Hi Mark and Mike, 

I have a few questions/comments:

1. For the GSI-centric cmake files, I will suggest either 
       (1).  Keep the top-level cmake/ directory; put platforms/, setFlags.cmake, setHOST.cmake, setPlatformVariables.cmake under it and at the same time set up the Modules/ directory as a submodule and link it to the CMakeModules repository
or
        (2).  put platforms/, setFlags.cmake, setHOST.cmake, setPlatformVariables.cmake into another subdirectory (for example cmake-gsi/ or cmake2/, etc)

2. I see "setGNUFlags.cmake", "setPGIFlags.cmake" are removed, only setIntelFlags.cmake was kept and renamed to setFlags.cmake.  It is possible to keep "setGNUFlags.cmake", "setPGIFlags.cmake" ?

3. Will NCEPLIBS release bufrlib?  I have problems to compile a good bufrlib from NCEPLIBS tag ufs-v1.0.0 (but no problems from libsrc/)

Under the GNU environment,  I got error messages like this:
```
Error: BIND(C) Variable 'cbelem' at (1) must have length one
/lfs4/BMC/wrfruc/gge/precompiled/NCEPLIBS/NCEPLIBS-bufr/src/moda_mstabs.F:41:46:

   41 |    CHARACTER*8, BIND(C) :: CBMNEM(MXMTBB)
      |                                              1
........................
/lfs4/BMC/wrfruc/gge/precompiled/NCEPLIBS/NCEPLIBS-bufr/src/moda_mstabs.F:45:46:

   45 |    CHARACTER*8, BIND(C) :: CDMNEM(MXMTBD)
      |                                              1
Error: BIND(C) Variable 'cdmnem' at (1) must have length one
/lfs4/BMC/wrfruc/gge/precompiled/NCEPLIBS/NCEPLIBS-bufr/src/moda_mstabs.F:44:47:

   44 |    CHARACTER*120, BIND(C) :: CDSEQ(MXMTBD)
      |                                               1
Error: BIND(C) Variable 'cdseq' at (1) must have length one
make[2]: *** [NCEPLIBS-bufr/CMakeFiles/bufr_8_f.dir/src/moda_mstabs.F.o] Error 1
make[1]: *** [NCEPLIBS-bufr/CMakeFiles/bufr_8_f.dir/all] Error 2
```
Under the Intel environment, I can build three different version of bufrlib's (_8, _4 and _d) from NCEPLIBS but neither of them can be linked by GSI. The error message goes as:
```
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(c$
osbf.f.o): in function `closbf_':
closbf.f:(.text+0x5e): undefined reference to `closfb_'
[  4%] Building Fortran object src/ncdiag/CMakeFiles/ncdiag.dir/netcdf_unlimdims.F90.o
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(m$
gwrt.f.o): in function `msgwrt_':
msgwrt.f:(.text+0x98a): undefined reference to `cwrbufr_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(o$
enbf.F.o): in function `openbf_':
openbf.F:(.text+0x821): undefined reference to `openab_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x88a): undefined reference to `openwb_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x8c6): undefined reference to `openwb_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x917): undefined reference to `openrb_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x966): undefined reference to `openwb_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x9a2): undefined reference to `openrb_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0xa9c): undefined reference to `openrb_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(p$
sapx.f.o): in function `posapx_':
posapx.f:(.text+0xf9): undefined reference to `backbufr_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(r$
bfdx.f.o): in function `rdbfdx_':
rdbfdx.f:(.text+0xef): undefined reference to `backbufr_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(r$
msgw.f.o): in function `rdmsgw_':
rdmsgw.f:(.text+0x35): undefined reference to `crdbufr_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(s$
ndrd.f.o): in function `stndrd_':
stndrd.f:(.text+0x4a9): undefined reference to `restd_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(b$
rt.f.o): in function `bort_':
bort.f:(.text+0x6d): undefined reference to `bort_exit_'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(b$
rt2.f.o): in function `bort2_':
bort2.f:(.text+0x86): undefined reference to `bort_exit_'
```

Thanks,
Guoqing

**Comment by mark-a-potts** [comment]
Adding in an issue for this PR.(thanks, Mike.) [https://github.com/NOAA-EMC/GSI/issues/23](url) 

This current PR uses the UFS public release version of NCEPLIBS and NCEPLIBS-external, but NCEPLIBS has been moving forward quickly with changes to their approach to using find_package() calls. I am not really sure which we should try to support, but I am thinking maybe the most current version. I will try to work towards that.

**Comment by mark-a-potts** [comment]
> Hi Mark and Mike,
> 
> I have a few questions/comments:
> 
> 1. For the GSI-centric cmake files, I will suggest either
>    (1).  Keep the top-level cmake/ directory; put platforms/, setFlags.cmake, setHOST.cmake, setPlatformVariables.cmake under it and at the same time set up the Modules/ directory as a submodule and link it to the CMakeModules repository
>    or
>    (2).  put platforms/, setFlags.cmake, setHOST.cmake, setPlatformVariables.cmake into another subdirectory (for example cmake-gsi/ or cmake2/, etc)
> 2. I see "setGNUFlags.cmake", "setPGIFlags.cmake" are removed, only setIntelFlags.cmake was kept and renamed to setFlags.cmake.  It is possible to keep "setGNUFlags.cmake", "setPGIFlags.cmake" ?
> 3. Will NCEPLIBS release bufrlib?  I have problems to compile a good bufrlib from NCEPLIBS tag ufs-v1.0.0 (but no problems from libsrc/)
> 
> Under the GNU environment, I got error messages like this:
> 
> ```
> Error: BIND(C) Variable 'cbelem' at (1) must have length one
> /lfs4/BMC/wrfruc/gge/precompiled/NCEPLIBS/NCEPLIBS-bufr/src/moda_mstabs.F:41:46:
> 
>    41 |    CHARACTER*8, BIND(C) :: CBMNEM(MXMTBB)
>       |                                              1
> ........................
> /lfs4/BMC/wrfruc/gge/precompiled/NCEPLIBS/NCEPLIBS-bufr/src/moda_mstabs.F:45:46:
> 
>    45 |    CHARACTER*8, BIND(C) :: CDMNEM(MXMTBD)
>       |                                              1
> Error: BIND(C) Variable 'cdmnem' at (1) must have length one
> /lfs4/BMC/wrfruc/gge/precompiled/NCEPLIBS/NCEPLIBS-bufr/src/moda_mstabs.F:44:47:
> 
>    44 |    CHARACTER*120, BIND(C) :: CDSEQ(MXMTBD)
>       |                                               1
> Error: BIND(C) Variable 'cdseq' at (1) must have length one
> make[2]: *** [NCEPLIBS-bufr/CMakeFiles/bufr_8_f.dir/src/moda_mstabs.F.o] Error 1
> make[1]: *** [NCEPLIBS-bufr/CMakeFiles/bufr_8_f.dir/all] Error 2
> ```
> 
> Under the Intel environment, I can build three different version of bufrlib's (_8, _4 and _d) from NCEPLIBS but neither of them can be linked by GSI. The error message goes as:
> 
> ```
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(c$
> osbf.f.o): in function `closbf_':
> closbf.f:(.text+0x5e): undefined reference to `closfb_'
> [  4%] Building Fortran object src/ncdiag/CMakeFiles/ncdiag.dir/netcdf_unlimdims.F90.o
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(m$
> gwrt.f.o): in function `msgwrt_':
> msgwrt.f:(.text+0x98a): undefined reference to `cwrbufr_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(o$
> enbf.F.o): in function `openbf_':
> openbf.F:(.text+0x821): undefined reference to `openab_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x88a): undefined reference to `openwb_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x8c6): undefined reference to `openwb_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x917): undefined reference to `openrb_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x966): undefined reference to `openwb_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0x9a2): undefined reference to `openrb_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: openbf.F:(.text+0xa9c): undefined reference to `openrb_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(p$
> sapx.f.o): in function `posapx_':
> posapx.f:(.text+0xf9): undefined reference to `backbufr_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(r$
> bfdx.f.o): in function `rdbfdx_':
> rdbfdx.f:(.text+0xef): undefined reference to `backbufr_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(r$
> msgw.f.o): in function `rdmsgw_':
> rdmsgw.f:(.text+0x35): undefined reference to `crdbufr_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(s$
> ndrd.f.o): in function `stndrd_':
> stndrd.f:(.text+0x4a9): undefined reference to `restd_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(b$
> rt.f.o): in function `bort_':
> bort.f:(.text+0x6d): undefined reference to `bort_exit_'
> /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /glade/p/ral/jntp/gge/precompiled/NCEPLIBS/b_intel18.0.5_impi2018.4.274/install/lib/libbufr_d.a(b$
> rt2.f.o): in function `bort2_':
> bort2.f:(.text+0x86): undefined reference to `bort_exit_'
> ```
> 
> Thanks,
> Guoqing

Thanks, Guoqing. The bufrlib hasn't been fully ported to the new NCEPLIBS build system yet, so that is probably where the problem is coming from. I have made some changes to that code and will see if I can get them pushed to develop so that we can count on everything working right.

**Comment by MichaelLueken-NOAA** [comment]
Since all NCEP projects are moving from NCEPLIBS to hpc-stack, this work is now obsolete.  Closing PR #22.

**Pull request closed without merging**
