### PR TITLE
Turn on NOAA-21, GOES-18 and Metop-C ASCAT in Release/gfsda.v16

### PR DESCRIPTION
**Pull request by ADCollard**
This PR turns on for active assimilation NOAA-21 CrIS and ATMS, GOES-18 AMVs and Metop-C ASCAT.

Changes are to the fix file only.

To inspect the changes you will need to:

```
git clone --recursive https://github.com/ADCollard/GSI.git GSI_ACollard
cd GSI_ACollard
git checkout release/gfsda.v16
git submodule sync
git submodule update
cd fix
```
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by ADCollard** [comment]
@RussTreadon-NOAA, @HaixiaLiu-NOAA is on leave until Thursday.  So I am trying to add @wx20jjung as a third reviewer as he probably has the most experience with GOES CSRs.  However I am unable to do so.

**Review by RussTreadon-NOAA — APPROVED** [review]
Clone [`ADCollard:release/gfsda.v16`](https://github.com/ADCollard/GSI/tree/release/gfsda.v16) on Orion.  Compare with [`NOAA-EMC:release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16).  Differences limited to
- `fix/global_convinfo.txt` 
   - set usage flag to 1 (assimilate) for uv type 290 (ascat), subtype 5 (metop-c)
- `fix/global_satinfo.txt` 
   - set usage flag to 1 (assimilate) for atms_n21 channels 1-14, 16-22 and set usage flag to 4 for channel 15
   - set usage flag to 1 (assimilate) for 100 channels of cris-fsr_n21
   - set usage flag to 1 (assimilate) assimilate abi_g19 channels 8, 9, 10

These changes look to be correct.  Approve.

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , what tag name would you like me to use for this update?   The previous gfsda tag was `gfsda.v16.3.10`.   The g-w PR for this implementation is GFS.v16.3.12.   I'm fine with either `gfsda.v16.3.11` or `gfsda.v16.3.12`.

Jim (@wx20jjung) does not belong to the NOAA-EMC github organization.  Therefore, we can not add him as a PR reviewer.  He can still review, give feedback, and approve via comments in this PR.  Alternatively, we can add Jim as an _outside collaborator_ to the NOAA-EMC/GSI repository.  Then he may be assigned as a reviewer for GSI PRs.   Jim, what's your preference?

**Comment by ADCollard** [comment]
> @ADCollard , what tag name would you like me to use for this update? The previous gfsda tag was `gfsda.v16.3.10`. The g-w PR for this implementation is GFS.v16.3.12. I'm fine with either `gfsda.v16.3.11` or `gfsda.v16.3.12`.
> 
> Jim (@wx20jjung) does not belong to the NOAA-EMC github organization. Therefore, we can not add him as a PR reviewer. He can still review, give feedback, and approve via comments in this PR. Alternatively, we can add Jim as an _outside collaborator_ to the NOAA-EMC/GSI repository. Then he may be assigned as a reviewer for GSI PRs. Jim, what's your preference?

@RussTreadon-NOAA Please tag with `gfsda.v16.3.12`.  The GFS tag number was increased after the GSI tag for the previous implementation was made - hence the discrepancy.

To be honest if you are happy with this change, then I think having @wx20jjung as an additional reviewer is not necessary.  I will defer to you on how many approvals you need.

**Comment by RussTreadon-NOAA** [comment]
Tag [`NOAA-EMC:release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) at [`e593e20`](https://github.com/NOAA-EMC/GSI/commit/e593e20ee29df275ffe56b82ad4810e9104be43d) as [`gfsda.v16.3.12`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.12).

**Comment by ADCollard** [comment]
Thank you @RussTreadon-NOAA !

**Comment by wx20jjung** [comment]
For the future, it does not matter to me if/how I am added as a reviewer.
Jim

**Comment by emilyhcliu** [comment]
> Clone [`ADCollard:release/gfsda.v16`](https://github.com/ADCollard/GSI/tree/release/gfsda.v16) on Orion. Compare with [`NOAA-EMC:release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16). Differences limited to
> 
> * `fix/global_convinfo.txt`
>   
>   * set usage flag to 1 (assimilate) for uv type 290 (ascat), subtype 5 (metop-c)
> * `fix/global_satinfo.txt`
>   
>   * set usage flag to 1 (assimilate) for atms_n21 channels 1-14, 16-22 and set usage flag to 4 for channel 15
>   * set usage flag to 1 (assimilate) for 100 channels of cris-fsr_n21
>   * set usage flag to 1 (assimilate) assimilate abi_g18 channels 8, 9, 10
> 
> These changes look to be correct. Approve.

The ASCAT Metop-C configuration and ATMS_N21 Channels are good.  
Just one question for abi_g18.  Are we using channel 9 from ABI?  
Otherwise, changes look good to me.

**Comment by emilyhcliu** [comment]
I am a bit late to review this PR.  Iit is already merged.   I guess we do want to use channel 9 from ABI.

**Comment by ADCollard** [comment]
> I am a bit late to review this PR. Iit is already merged. I guess we do want to use channel 9 from ABI.

@emilyhcliu Channel 9 does have slightly larger biases than the other channels, but bias correction mops that up and I think we can assimilate this channel.

**Comment by ADCollard** [comment]
> > I am a bit late to review this PR. Iit is already merged. I guess we do want to use channel 9 from ABI.
> 
> @emilyhcliu Channel 9 does have slightly larger biases than the other channels, but bias correction mops that up and I think we can assimilate this channel.

@HaixiaLiu-NOAA confirms that we should use Channel 9

**Pull request merged**
