### PR TITLE
GitHub Issue NOAA-EMC/GSI#177 Update build/run scripts and disable regression tests for S4

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
These changes are intended to bring support for the GSI, EnKF, and utilities up to date for S4 as required by the global workflow.  Additionally, regression tests are not available to S4, which cannot host restricted data, so references to S4 in the regression tests have been removed.  Lastly, S4 consists of two partitions, s4 and ivy, with the latter using an older architecture (Ivy Bridge).  Thus, instructions are sent to the compiler to support the older architecture.

Two test runs have been completed, one at 192/96 (2020073118 through 2020081000) and another at 384/192 (2020073118 through 2020080400).  Logs and data for these runs can been copied to Orion here:
__192/96__
Logs: /work/noaa/nesdis-rdo2/dhuber/s4_logs/test_dev
Comrot (2020081000 only): /work/noaa/nesdis-rdo2/dhuber/s4_data/comrot/test_dev
Archive: /work/noaa/nesdis-rdo2/dhuber/s4_data/archive/test_dev

__384/192__
Logs: /work/noaa/nesdis-rdo2/dhuber/s4_logs/test_dev_384
Comrot (2020080400 only, **still transferring**): /work/noaa/nesdis-rdo2/dhuber/s4_data/comrot/test_dev_384
Archive: /work/noaa/nesdis-rdo2/dhuber/s4_data/archive/test_dev_384

I expect the 384/192 comrot transfer to complete tomorrow (8/11).

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
@DavidHuber-NOAA Would you like to have anyone review the changes before I begin working on merging this work into the authoritative master?  Since there are no source code changes, no third party review is required, but I wanted to check before moving forward.

**Comment by DavidHuber-NOAA** [comment]
@MichaelLueken-NOAA I think we'll be alright without the review.  Results have been tested against Orion and all has run well.  Thanks for checking.

**Comment by MichaelLueken-NOAA** [comment]
@DavidHuber-NOAA Please follow these steps to reduce the number of commits from four to one and remove the fix modification from the PR, then I will be able to merge this work to the authoritative repo:

1) git clone --recursive git@github.com:DavidHuber-NOAA/GSI.git update
2) cd update
3) git checkout port_2_s4
4) git submodule update
5) git reset --hard HEAD~1
6) git reset --hard HEAD~1
7) git reset --soft HEAD~1
8) git commit --amend
9) You can add a fifth entry for removing S4 from the regression test scripts

Now, to rebase the master into port_2_s4:

10) git remote add upstream https://github.com/NOAA-EMC/GSI.git
11) git remote update
12) git rebase upstream/master

Final cleanup and push back to repo:

13) git submodule update
14) git push origin port_2_s4 --force

If you encounter any issues, please let me know.

**Comment by DavidHuber-NOAA** [comment]
@MichaelLueken-NOAA Alright, all done.

**Comment by MichaelLueken-NOAA** [comment]
These changes have been compiled and the regression tests run on Venus and Hera.  All tests passed.  Since no changes have been made to the source code, I will now give final approval for these changes and will merge them to the authoritative repository.

**Pull request merged**
