### PR TITLE
GitHub Issue NOAA-EMC/GSI#341. Add GMI for radmon

### LINKED ISSUE #341: Add changes for all-sky radiance assimilation
**The following changes will be added to GSI Master for V16.x Implementation:**

**Source code update:**
- [x] Switching from assimilating antenna temperature (SDR) to brightness temperature (TDR) for AMSU-A, ATMS, and MHS
- [x] The use precipitation-affected radiances for ATMS and AMSU-A (extened all-sky framework)
- [x] The use of GMI radiances under all-sky conditions

**Fix files update:**
- [x] Add global_anavinfo_allhydro_l127.txt --- add precipitation components
- [x] Update cloudy_radiance_info.txt --- add GMI
- [x] Update global_satinfo.txt --- modify channel use flag and error bounds for GMI
- [x] Update global_scaninfo.txt --- add GMI

**Script update:**
- [x] exglobal_atmos_analysis.sh

The working branch is **[feature/v16x_allsky](https://github.com/emilyhcliu/GSI/tree/feature/v16x_allsky)**
**The changes in the branch will not change the GSI result from master with the default namelist and default resource files (All regression tests passed).** 

**List of changes for Ta2Tb work:**
- antcorr_application.f90
- crtm_interface.f90
- read_atms.f90
- read_bufrtovs.f90
- obsmod.F90
- gsimod.F90

Set ta2tb = .true. will trigger the use of Tb for AMSU-A, ATMS, and MHS
Default ta2tb is set to false.   This ensures that the code update will not change GSI result from the master

**List of changes for assimilating precipitation-affected ATMS and AMSU-A:** 
- cloud_efr_mod.f90
- cplr_gfs_ensmod.f90
- crtm_interface.f90
- general_read_gfsatm.f90
- netcdfgfs_io.f90
- prt_guess.f90
- qcmod.f90
- read_atms.f90
- read_bufrtovs.f90
- write_incr.f90
- setuprad.f90

These code changes will not affect GSI result from master unless the default global_anavinfo.l127.txt is replaced with global_anavinfo_alhydro.l127.txt

The current GSI master (and operational GDAS) is using CRTM2.3.0 for radiance assimilation
The use of precipitation-affected  MW data should combined with the use of CRTM 2.4.0 for the following two reasons:

1. The surface Jacobian under scattering condition from CRTM2.3.0 was not implemented correctly and CRTM 2.4.0 fixed the issue.  (Surface Jacobian is used in QC for radiance data)
2. CRTM2.4.0 has the cloud optical table generated based on GFDL physics (consistent with FV3 model physics)

Note: If we decide not to include precipitation-affected MW radiance in our next implementation, then we should not use CRTM2.4.0 (should stay with CRTM 2.3.0) due to the following two reasons:

1. CRTM 2.4.0 requires cloud fraction profile in the input for cloudy simulation.  
2. GFDL cloud fraction calculation requires all hydrometeors which is not available in our operational run (only cloud water and cloud water are available)

**List of changes for the assimilation of GMI under all-sky conditions:**

- read_gmi.f90
- crtm_interface.f90
- setuprad.f90

These code update  will not change GSI result from the master since GMI channel use flags are set to -1 (monitoring)
To activate GMI for assimilation, modifiy the use flags as the following:
```
 gmi_gpm                 1  -1    2.700   25.000   30.000   40.000    0.000      1      1     -1
 gmi_gpm                 2  -1    3.700   40.000   30.000   40.000    0.000      1      1     -1
 gmi_gpm                 3  -1    3.500   40.000   15.000   40.000    0.000      1      1     -1
 gmi_gpm                 4  -1    4.500   55.000   30.000   40.000    0.000      1      1     -1
 gmi_gpm                 5   1    4.000   35.000   15.000   40.000    0.000      1      1     -1
 gmi_gpm                 6   1    3.800   25.000   30.000   40.000    0.000      1      1     -1
 gmi_gpm                 7   1  300.000  500.000    5.000   40.000    0.000      1      1     -1
 gmi_gpm                 8  -1    5.000   50.000   15.000   40.000    0.000      1      1     -1
 gmi_gpm                 9  -1   11.500   50.000   20.000   40.000    0.000      1      1     -1
 gmi_gpm                10   1    5.000   50.000   20.000   40.000    0.000      1      1     -1
 gmi_gpm                11  -1    5.000   50.000   20.000   40.000    0.000      1      1     -1
 gmi_gpm                12   1    2.500   30.000   10.000   40.000    0.000      1      1     -1
 gmi_gpm                13   1    3.000   40.000   10.000   40.000    0.000      1      1     -1
```

**List of changes for exglobal_atmos_analysis.sh:**

1. add link to AMSU-A MetOp-A version 2 coefficient file
2. add logic (ta2tb) to turn on the use of brightness temperature for ATMS, AMSU-A and MHS for assimilaton
3. add logic (cao_check) to turn on CAO (cold air outbreak check) for quality control
4. set thinning box to 145 km for GMI (original is 100 km)

### PR DESCRIPTION
**Pull request by emilyhcliu**
Add gmi in radmon

### CODE REVIEW

**Comment by MichaelLueken** [comment]
@emilyhcliu Is there an issue associated with this work?  If not, please create an issue for it.  Additionally, please let me know whether you would like to have either @EdwardSafford-NOAA or @DavidHuber-NOAA have a look before merging this work to the authoritative repository.

**Comment by EdwardSafford-NOAA** [comment]
@MichaelLueken-NOAA those changes look good to me.  It's just adding a new entry in two of the RadMon fix files for a new instrument.

**Comment by MichaelLueken** [comment]
> @MichaelLueken-NOAA those changes look good to me. It's just adding a new entry in two of the RadMon fix files for a new instrument.

@EdwardSafford-NOAA Thanks for the confirmation!

**Comment by emilyhcliu** [comment]
@MichaelLueken-NOAA This PR is related to [Issue #341](https://github.com/NOAA-EMC/GSI/issues/341) 
 
Please add any reviews you see fit.  Thanks.

**Comment by MichaelLueken** [comment]
Since there are no source code changes and @EdwardSafford-NOAA has given his approval, I will now give final approval to these changes and merge them to the authoritative repository.

**Pull request merged**
