### PR TITLE
Remove deprecated WCOSS platforms

### LINKED ISSUE #471: Remove deprecated WCOSS platforms
WCOSS Phase 1 (Tide and Gyre)
WCOSS Cray (Luna and Surge)
WCOSS Dell (Mars and Venus)

have been decommissioned.

Remove references to these platforms.

### PR DESCRIPTION
**Pull request by aerorahul**
Fixes #471

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Makes sense to remove WCOSS_C, WCOSS_D, and WCOSS since these machines are no longer available.   

While not the subject of this PR, it seems we do not have regression tests set up on WCOSS2.   Also `regression_var.sh` refer to files in Mike's directories.  This will need to be changed at some future date.

**Comment by aerorahul** [comment]
> Makes sense to remove WCOSS_C, WCOSS_D, and WCOSS since these machines are no longer available.
> 
> While not the subject of this PR, it seems we do not have regression tests set up on WCOSS2. Also `regression_var.sh` refer to files in Mike's directories. This will need to be changed at some future date.

No we do not have regression tests for WCOSS2 or Orion -- two of our most widely used platforms.

**Comment by RussTreadon-NOAA** [comment]
Ooops, I missed Orion.   Not having regression tests on either is a problem.

**Comment by CoryMartin-NOAA** [comment]
This PR has one approval, all CI status checks pass, and I have confirmed that the GSI compiles successfully on Cactus with these changes. Given that there are no source code changes, this is sufficient for merging to the develop branch.

**Pull request merged**
