### PR TITLE
Release/gfsda.v16

### PR DESCRIPTION
**Pull request by ADCollard**
Turn on PlanetIQ for operational assimilation

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by ADCollard** [comment]
Once merged this should be tagged as gfsda.v16.3.20

**Review by RussTreadon-NOAA — APPROVED** [review]
Clone [`ADCollard:release/gfsda.v16`](https://github.com/ADCollard/GSI/tree/release/gfsda.v16) and [`NOAA-EMC:release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) on Dogwood.  The only difference between the two is
```
diff '--exclude=.git' -r gfsda.v16/fix/global_convinfo.txt pr803/fix/global_convinfo.txt
264c264
<  gps      267    0   -1     3.0      0      0      0  10.0  10.0   1.0  10.0  0.000000     0    0.     0.      0    0.     0.    0    0
---
>  gps      267    0    1     3.0      0      0      0  10.0  10.0   1.0  10.0  0.000000     0    0.     0.      0    0.     0.    0    0
```

`ADCollard:release/gfsda.v16 places` gps 267 in assimilate mode.  This is correct.

Approve.

**Comment by RussTreadon-NOAA** [comment]
@ADCollard .  Tag [`gfsda.v16.3.20`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.20) has been created as a copy of `release/gfsda.v16` at [0326220](https://github.com/NOAA-EMC/GSI/commit/03262201cfd2d6a0e006ed2305912bb346e87aad)

**Comment by XuanliLi-NOAA** [comment]
Change looks good.

**Pull request merged**
