### PR TITLE
GSI GitHub Issue NOAA-EMC/GSI#253.  Update OznMon satype file.

### PR DESCRIPTION
**Pull request by EdwardSafford-NOAA**
Update gdas_oznmon_satype.txt file to remove reference to gome_metop-a.

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
@EdwardSafford-NOAA Do you wish for a review, or are these changes ready for the master?

**Review by RussTreadon-NOAA — APPROVED** [review]
Metop-A data is no longer disseminated as this satellite has reached its end of life.   As such is it is appropriate to remove gome_metop-a from the list of satellite_sensors checked by OznMon.

**Comment by RussTreadon-NOAA** [comment]
I submitted a review for completeness.

**Comment by MichaelLueken-NOAA** [comment]
Thanks for the review @RussTreadon-NOAA.  Given Russ' approval, I will now give final approval to these changes and merge them to the master.

**Pull request merged**
