### PR TITLE
GitHub Issue NOAA-EMC/GSI#295. GSI scripts and fix file changes to assimilate Metop-c AVHRR radiance

### PR DESCRIPTION
**Pull request by XuLi-NOAA**
This PR is to add metop-c AVHRR radiance to GSI/NSST. 
See https://github.com/NOAA-EMC/GSI/issues/295

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
@XuLi-NOAA Is there anyone that you would like to have review these changes, or are they good to go?  If you would like to have a reviewer go over the script changes, please let me know.

**Comment by MichaelLueken-NOAA** [comment]
@XuLi-NOAA There are 5 commit messages associated with this PR.  Please reduce this to a single commit message message by:

1) git clone --recursive git@github.com:XuLi-NOAA/GSI.git update
2) cd update
3) cp -rp scripts/exgdas_efsoi.sh ..
4) cp -rp scripts/exgdas_efsoi_update.sh ..
5) cp -rp scripts/exgdas_enkf_update.sh ..
6) git reset --hard HEAD~1
7) git reset --hard HEAD~1
8) git reset --hard HEAD~1
9) git remote add upstream git@github.com:NOAA-EMC/GSI.git
10) git remote update
11) git merge upstream/master
12) git checkout feature/gsi_avhmc
13) git checkout master
14) git merge --squash feature/gsi_avhmc
15) cp -rp ../exgdas* scripts/
16) `git commit -m "GitHub Issue NOAA-EMC/GSI#295. GSI scripts and fix file changes to assimilate Metop-C AVHRR radiance."`
17) git push origin master --force

These steps will reduce the number of commit messages from 5 to 1.

If you have any questions, please let me know.  These changes will be going in next Tuesday, after a bug fix that is currently out to the review committee has been merged to the authoritative repository.

**Comment by XuLi-NOAA** [comment]
@MichaelLueken-NOAA : Done. Learned something about git and thanks!

**Comment by MichaelLueken-NOAA** [comment]
Since this work doesn't include source code changes, I will now give final approval to these changes and merge them to the authoritative repository.  Following merging these changes, I will update the fix file in the authoritative repository.

**Pull request merged**
