### PR TITLE
add two band sdl to global_4denvar namelist

### LINKED ISSUE #756: Turn on SDL in global_4denvar ctest
GFS v17 will run `gsi.x` with scale dependent localization (SDL) on.  GFS v17 will use three bands. Two bands is sufficient for the ctest.  the following will be added to the global_4denvar namelist `HYBRID_ENSEMBLE `
```
  s_ens_h=1000.0,300.0,685.0,s_ens_v=-0.5,-0.5,0.0,
  readin_localization=.false.,global_spectral_filter_sd=.false.,
  r_ensloccov4scl=1,nsclgrp=2,naensloc=3,
```

This issue is opened to document the addition of SDL to the global_4denvar ctest.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
GFS v17 runs `gsi.x` with scale-dependent localization (SDL).  Update the global_4denvar ctest to include SDL.

Fixes #756

**Type of change**
- [ ] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
Install feature/sdl on Dogwood and run global_4denvar ctest.  Confirm correct namelist parameters are set to activate SDL.

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
global_4denvar ctests have been run on Dogwood with [acceptable results](https://github.com/NOAA-EMC/GSI/issues/756#issuecomment-2176702284).

**Comment by RussTreadon-NOAA** [comment]
@CatherineThomas-NOAA and @TravisElless-NOAA :  This PR activates two-band SDL in the global_4denvar ctest. Do either of you have time to review the changes in this PR?

**Comment by CatherineThomas-NOAA** [comment]
@RussTreadon-NOAA: I can review these changes today.

**Comment by RussTreadon-NOAA** [comment]
Thank you @CatherineThomas-NOAA

**Comment by TravisElless-NOAA** [comment]
Potential newbie question. Should `regression_namelists_db.sh` also be updated with these values given this [if block](https://github.com/NOAA-EMC/GSI/blob/develop/regression/global_4denvar.sh#L86C1-L91C3)?

**Comment by CatherineThomas-NOAA** [comment]
My ctests [ran on Hera](https://github.com/NOAA-EMC/GSI/issues/756#issuecomment-2181098638) without issue.  Looking at the log for the ctests, I see that the parameters are set appropriately:
```
 NSCLGRP =           2,
 NGVARLOC        =           1,
 NAENSLOC        =           3,
 R_ENSLOCCOV4TIM =   1.00000000000000     ,
 R_ENSLOCCOV4VAR =   1.00000000000000     ,
 R_ENSLOCCOV4SCL =   1.00000000000000     ,
 S_ENS_H =   1000.00000000000     ,   300.000000000000     ,   685.000000000000     , 17*2828.00000000000        ,
 S_ENS_V = 2*-0.500000000000000      ,  0.000000000000000E+000, 17*30.0000000000000        ,
 READIN_LOCALIZATION     = F,
 GLOBAL_SPECTRAL_FILTER_SD       = F,
```

The only snag is that due to the decreased resolution of the ctest, our chosen second scale is too small:
```
( pi*rearth*.001/jcap_in <= s_ens_hv <= 5500 )
```
Our second scale localization value of 300 km is reset automatically:
```
  s_ens_hv(           1 ) =    300.000000000000       km--too small, min value =
     416.994064886485       km.
  s_ens_hv(           1 ) reset to min value
```
Once it's reset, the scales are showing as expected:
```
 in init_sf_xy, jcap,s_ens_hv(    1 -  127), max diff(f0-f)=        48   1000.00    0.4608313731E-11
 in init_sf_xy, jcap,s_ens_hv(    1 -  127), max diff(f0-f)=        48    416.99    0.4824141087E-11
 in init_sf_xy, jcap,s_ens_hv(    1 -  127), max diff(f0-f)=        48    685.00    0.4678923915E-11
```
@RussTreadon-NOAA, @TravisElless-NOAA: Should we adjust our second scale so these warnings aren't set off?  450 km instead of 300?

**Comment by RussTreadon-NOAA** [comment]
Good suggestion @TravisElless-NOAA:  I will add SDL to the global_4denvar case in `regression_namelists_db.sh`

Good catch @CatherineThomas-NOAA:  I will increase the 300 km scale to 450 km.

**Comment by RussTreadon-NOAA** [comment]
Rerun `global_4denvar` on Dogwood with 450 km scale.  No more warning messages
```
  reading time level            7
 in init_sf_xy, jcap,s_ens_hv(    1 -  127), max diff(f0-f)=        48   1000.00    0.4608313731E-11
 in init_sf_xy, jcap,s_ens_hv(    1 -  127), max diff(f0-f)=        48    450.00    0.4799716180E-11
 in init_sf_xy, jcap,s_ens_hv(    1 -  127), max diff(f0-f)=        48    685.00    0.4678923915E-11
GLBSOI: jiter,jiterstart,jiterlast,jiterend=    1    1    2    1
```
ctest still passes (it should!)
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/sdl/build
    Start 1: global_4denvar
1/1 Test #1: global_4denvar ...................   Passed  2344.44 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 2344.45 sec
```

**Review by CatherineThomas-NOAA — DISMISSED** [review]
Looks great. Thanks @RussTreadon-NOAA!

**Comment by RussTreadon-NOAA** [comment]
Update `modulefiles/gsi_orion.intel.lua` in order to compile feature/sdl on Orion and run ctest.   Done at aab4a063.

Sorry @CatherineThomas-NOAA - this commit dismissed your approval.

**Comment by CatherineThomas-NOAA** [comment]
That's fine @RussTreadon-NOAA.  I'll wait until the Orion tests complete before approving again.

**Comment by RussTreadon-NOAA** [comment]
**WARNING**

Updating to Orion Rocky 9 is not as simple as updating a few files.  The Orion and Hercules Rocky 9 `crtm-fix/2.4.0.1_emc` module do not contain the same coefficient files.

Orion `crtm-fix/2.4.0.1_emc` has
```
setenv("CRTM_FIX","/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/unified-env-rocky9/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-qls55kd/fix")
```
whereas Hercules `crtm-fix/2.4.0.1_emc` has
```
setenv("CRTM_FIX","/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/unified-env/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-2os2hw2/fix")
```
A `diff -r` of these two `CRTM_FIX` directories finds 447 files differ.  This is not correct.
```
hercules-login-3:~$ diff -r /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/unified-env-rocky9/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-qls55kd/fix /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/unified-env/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-2os2hw2/fix |wc
    447    2680  159396
```
For example,
```
hercules-login-3:~$ ls -l /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/unified-env-rocky9/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-qls55kd/fix/abi_gr.TauCoeff.bin /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/unified-env/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-2os2hw2/fix/abi_gr.TauCoeff.bin
-rw-r--r-- 1 role-epic epic  10972 Dec 20  2023 /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/unified-env/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-2os2hw2/fix/abi_gr.TauCoeff.bin
-rw-r--r-- 1 role-epic epic 184588 Jun 14 16:06 /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/unified-env-rocky9/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-qls55kd/fix/abi_gr.TauCoeff.bin
```

Given this, revert commits 086e2737 and aab4a063 from `feature/sdl`.

**Comment by RussTreadon-NOAA** [comment]
@CatherineThomas-NOAA : I abandoned the Orion ctest attempt.  While updating the module is easy, the CRTM coefficients when loading the Orion `crtm-fix/2.4.0.1_emc` differ from those one gets when loading the Hercules `crtm-fix/2.4.0.1_emc`.  This is not correct.  Leave this to be sorted out in GSI issue #754

I am done making changes to this PR.

**Review by TravisElless-NOAA — APPROVED** [review]
All looks good to me. Thanks @RussTreadon-NOAA!

**Review by CatherineThomas-NOAA — APPROVED** [review]

**Pull request merged**
