### PR TITLE
Zero increments for precipitation hydrometeors are written as missing values instead of zeros

### LINKED ISSUE #577: Missing values in the increment files for precipitation which should be zeros.
We do not want the hydrometeor increments to be used in the IAU.
So, we zero them out and save them in the increment files.
This is done in the subroutine writeincrement_pnc in [gridio_gfs.f90](https://github.com/NOAA-EMC/GSI/blob/develop/src/enkf/gridio_gfs.f90)

However, the precipitation increments are filled in with missing values instead of zeros.  
This bug is found in the GSI develop version and was introduced by PR #499 
So, a PR will be submitted to fix this.

### PR DESCRIPTION
**Pull request by emilyhcliu**
**Description**

We do not want the hydrometeor increments to be used in the IAU.
So, we zero them out and save them in the increment files.
This is done in the subroutine writeincrement_pnc in [gridio_gfs.f90](https://github.com/NOAA-EMC/GSI/blob/develop/src/enkf/gridio_gfs.f90)

However, the precipitation increments are filled in with missing values instead of zeros.
This bug is found in the GSI develop version and was introduced by PR https://github.com/NOAA-EMC/GSI/pull/499

A fix is provided in this PR to make sure precipitation increments are filled in with zeros when the logic `should_zero_increments_for` is set to true.  

Fixes #577

 **Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

I tested this in a cycled experiment using global-workflow. 
Ensemble increment files were checked to make sure all hydrometer increments are filled with zeros as intended.  
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

**DUE DATE** for merger of this PR into develop is **7/2/2023** (six weeks after PR creation).

### CODE REVIEW

**Comment by emilyhcliu** [comment]
Regression tests performs for global models
WCOSS-2
```
emily.liu@clogin01:/lfs/h2/emc/da/noscrub/emily.liu/git/GSI-emilyhcliu/GSI-allsky3/build> ctest -R global
Test project /lfs/h2/emc/da/noscrub/emily.liu/git/GSI-emilyhcliu/GSI-allsky3/build

    Start 1: global_3dvar
1/4 Test #1: global_3dvar .....................   Passed  1442.55 sec
    Start 2: global_4dvar
2/4 Test #2: global_4dvar .....................   Passed  1442.28 sec
    Start 3: global_4denvar
3/4 Test #3: global_4denvar ...................   Passed  1322.37 sec
    Start 9: global_enkf
4/4 Test #9: global_enkf ......................   Passed  490.42 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) = 4697.62 sec

```
HERA
```
Emily.Liu@hfe05 build]$ ctest -R global
Test project /scratch1/NCEPDEV/da/Emily.Liu/git/GSI-emilyhcliu/GSI-allsky3/build

    Start 1: [=[global_3dvar]=]
1/4 Test #1: [=[global_3dvar]=] ...............   Passed  2226.81 sec
    Start 2: [=[global_4dvar]=]
2/4 Test #2: [=[global_4dvar]=] ...............   Passed  2585.05 sec
    Start 3: [=[global_4denvar]=]
3/4 Test #3: [=[global_4denvar]=] .............   Passed  1748.55 sec
    Start 9: [=[global_enkf]=]
4/4 Test #9: [=[global_enkf]=] ................   Passed  577.62 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) = 7138.05 sec

```

ORION
```
Orion-login-4[197] eliu$ ctest -R global
Test project /work/noaa/da/eliu/git/GSI-emilyhcliu/GSI-allsky3/build

    Start 1: [=[global_3dvar]=]
1/4 Test #1: [=[global_3dvar]=] ...............   Passed  1921.96 sec
    Start 2: [=[global_4dvar]=]
2/4 Test #2: [=[global_4dvar]=] ...............   Passed  1861.89 sec
    Start 3: [=[global_4denvar]=]
3/4 Test #3: [=[global_4denvar]=] .............   Passed  1501.84 sec
    Start 9: [=[global_enkf]=]
4/4 Test #9: [=[global_enkf]=] ................   Passed  488.56 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) = 5774.27 sec


```

**Review by azadeh-gh — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu ,  when you have a chance would you please update your forked branch, `emilyhcliu:feature/allsky3` to the current head of `develop`?

**Comment by RussTreadon-NOAA** [comment]
If this PR is not merged into `develop` by 7/2/2023, it will be closed and returned to the developer on 7/3/2023.

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA I will upodate the branch with the develop first.

**Comment by emilyhcliu** [comment]
@ADCollard When you have time, could you review this PR?  Thanks!

**Comment by ADCollard** [comment]
> @ADCollard When you have time, could you review this PR? Thanks!

I'm looking now, but I am a little confused about why there are so many differences for what I thought was a simple change.  Can you help me by explaining what you have done?

**Comment by emilyhcliu** [comment]
@ADCollard  In current ops, we only write out EnKF hydrometer increments for ql and qi.  I am expanding it to include all hydrometer increments (ql, qi, qr, qs, and qg).  They should be all zeros, just like the deterministic part.  

In my previous PR.  I made a mistake in this part. The precipitation increments (qr, qs, and qg) were not written as zero.  This is because they were not properly initialized.  This PR is to make sure the zero increments are written into the output file for precipitation.

**Comment by RussTreadon-NOAA** [comment]
Thank you @emilyhcliu for updating  `emilyhcliu:feature/allsky3` to the head of `develop`.

GSI PR #568 has been merged into `develop` (done at [00cac54](https://github.com/NOAA-EMC/GSI/commit/00cac5443e49f466a8d117b18a7c30903747b6a0)).  Your branch is now one commit behind the head of `develop`.   Please update your branch to the current head of GSI `develop`.

**Review by ADCollard — APPROVED** [review]

**Review by RussTreadon-NOAA — APPROVED** [review]
Given approval from peer reviewers, approve.

**Comment by emilyhcliu** [comment]
> Thank you @emilyhcliu for updating `emilyhcliu:feature/allsky3` to the head of `develop`.
> 
> GSI PR #568 has been merged into `develop` (done at [00cac54](https://github.com/NOAA-EMC/GSI/commit/00cac5443e49f466a8d117b18a7c30903747b6a0)). Your branch is now one commit behind the head of `develop`. Please update your branch to the current head of GSI `develop`.

@RussTreadon-NOAA I updated the branch with the latest develop.

**Pull request merged**
