### PR TITLE
GitHub Issue NOAA-EMC/GSI#94 deallocate ges_q2 and ges_th2 in setupt.f90

### PR DESCRIPTION
**Pull request by ShunLiu-NOAA**
deallocate ges_th2 and ges_q2 in setupt.f90

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
Hi Shun,

Who would you like me to assign as reviewer for this update?

Thanks,

Mike

**Comment by ShunLiu-NOAA** [comment]
Please let Cory review this.
Thanks.

Shun

**Review by CoryMartin-NOAA — APPROVED** [review]
Very quick and small fix, looks good to me!

**Comment by MichaelLueken-NOAA** [comment]
The due date for the review committee has past with no feedback, so final approval will be given and this update will now be merged to the NOAA-EMC/GSI master.

**Pull request merged**
