### PR TITLE
GitHub Issue NOAA-EMC/GSI#57.  Adding an option for tropical cyclone initialization

### PR DESCRIPTION
**Pull request by WanshuWu-NOAA**

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Changes look good.  Default is for new option to be off.   Pending confirmation that options 1 and 2 have been tested and found to function as intended these changes should be considered for inclusion in the master.

Observation:  As comments in the code note this option may need to be revisited at higher resolutions.  The search area may need to be expanded.   The size of the search box (now + / - 5 gridpoints) could be replaced with namelist variables.   5 could be the default.  Users could then easily adjust the search box size based on resolution.  Just a thought, not a request to change.

**Comment by WanshuWu-NOAA** [comment]
Thanks, Russ. Great suggestions. I will add plots to show the functions of the option and make search box size a namelist variable. Thanks.

**Review by RussTreadon-NOAA — APPROVED** [review]
Looks good to me.   Thanks for adding tcp_box.

**Review by MichaelLueken-NOAA — COMMENTED** [review]
Hi Wan-Shu,

I have completed my review on your changes.  The regression tests were run and all passed successfully.  I compiled the code in debug mode and saw new issues during code compilation.  All debug tests passed successfully as well.  I completed my visual inspection of the changes and found three minor issues with your changes in setuptcp.f90 (these three issues were noted in the review).  To correct these issues:

1) git clone --recursive git@github.com:WanshuWu-NOAA/GSI.git update
2) cd update
3) vi src/gsi/setuptcp.f90
4) Make necessary changes to the routine.
5) git add src/gsi/setuptcp.f90
6) git commit --amend
7) Please replace "add search box size as a namelist variable" with "GitHub Issue NOAA-EMC/GSI#57. Analysis strategy on misalignment of tropical cyclone position in the first guess." in the commit message.
8) git push origin master --force

I should be able to get your change out to the review committee once step 8 is complete.

Please let me know if you have any questions or encounter issues.

Mike

**Comment by WanshuWu-NOAA** [comment]
Done. Thank you very much.

**Comment by MichaelLueken-NOAA** [comment]
Looks good!  I'll submit this work to the review committee now.

**Comment by MichaelLueken-NOAA** [comment]
The due date has past for feedback from the review committee, with no feedback received.  Approving update and merging to the NOAA-EMC/GSI master.

**Pull request merged**
