### PR TITLE
Update feature/gdas-validation with develop

### LINKED ISSUE #685: Update feature/gdas-validation with develop
`feature/gdas-validation` at [`6df19fc`](https://github.com/NOAA-EMC/GSI/commit/6df19fc96a950a6fc67feec76080829a31efaba6) is behind `develop` at [`275ee0d`](https://github.com/NOAA-EMC/GSI/commit/275ee0dc7d9ae7c506729920b9fdab2d0ce2e578).  This issue is opened to document the updating of `feature/gdas-validation` with recent changes committed to `develop`.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
`feature/gdas-validation` is behind `develop`.  This PR brings `feature/gdas-validation` up to date with `develop`

Resolves #685

**Type of change**
- [ ] Maintenance

**How Has This Been Tested?**
Install `develop` and forked `feature/gdas-validation` and run GSI ctests.
  
**Checklist**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] New and existing tests pass with my changes

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , @ADCollard , and @CoryMartin-NOAA :  Is this PR necessary?  Are developers still using [`NOAA-EMC/GSI:feature/gdas-validation`](https://github.com/NOAA-EMC/GSI/tree/feature/gdas-validation)

**Comment by CoryMartin-NOAA** [comment]
I do think we need this branch, as there are some CRTM version changes (among others) to make the validation consistent

**Comment by RussTreadon-NOAA** [comment]
> I do think we need this branch, as there are some CRTM version changes (among others) to make the validation consistent

I agree.  We'll need to monitor commits to `develop` and decide if/when to merge updates into `feature/gdas-validation`.

**Comment by RussTreadon-NOAA** [comment]
Since this is a merge of approved changes from `develop` into a feature branch go ahead and squash merge changes in this PR into `feature/gdas-validation`.

**Pull request merged**
