### PR TITLE
Fix cool layer output

### LINKED ISSUE #655: Fix Skin Layer Cooling output from setupsst.f90
Skin layer cooling output to `ncdiags` in [setupsst.f90](https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/setupsst.f90) is actually diurnal warming.

```
if (nst_gsi>0) then
              call nc_diag_metadata("FoundationTempBG",        sngl(data(itref,i)) )
              call nc_diag_metadata("DiurnalWarming_at_zob",   sngl(data(idtw,i)) )
              call nc_diag_metadata("SkinLayerCooling_at_zob", sngl(data(idtw,i)) )
              call nc_diag_metadata("Sensitivity_Tzob_Tr",     sngl(data(itz_tr,i)) )
endif
```

### PR DESCRIPTION
**Pull request by ADCollard**
Fixes #655.

The skin layer cooling output to ncdiag is not correct.  

Code compiles and runs.

### CODE REVIEW

**Review by emilyhcliu — APPROVED** [review]
Looks good!

**Review by XuanliLi-NOAA — APPROVED** [review]
The change looks good to me!

**Review by RussTreadon-NOAA — APPROVED** [review]
Variable `idtw` is incorrectly used as the index for the Skin Layer Cooling term.   The correct index is `idtc`.   This PR uses the correct index for Skin Layer Cooling.

Approve.

**Comment by RussTreadon-NOAA** [comment]
GSI code management policy requires ctests be run as part of the PR process ([see 3ii](https://github.com/NOAA-EMC/GSI/wiki/GSI---Code-Management-Policy)).  This is true even for simple typo corrections.   Merger of this PR into `develop` is on hold until ctests are completed.

I am running ctests on Hera, Orion, and WCOSS2 (Cactus).  Results will be reported in this PR as tests complete.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 (Cactus) ctests**
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr656/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  483.17 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  485.10 sec
3/7 Test #7: global_enkf ......................   Passed  610.23 sec
4/7 Test #2: rtma .............................   Passed  968.70 sec
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  1213.90 sec
6/7 Test #6: hafs_3denvar_hybens ..............   Passed  1214.57 sec
7/7 Test #1: global_4denvar ...................   Passed  1322.52 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1322.52 sec
```

**Hera ctests**
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr656/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  610.53 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  611.51 sec
3/7 Test #7: global_enkf ......................   Passed  933.56 sec
4/7 Test #6: hafs_3denvar_hybens ..............   Passed  1285.08 sec
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  1522.45 sec
6/7 Test #2: rtma .............................   Passed  2896.10 sec
7/7 Test #1: global_4denvar ...................   Passed  2935.12 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 2935.16 sec
```

**Orion ctests**
```
Test project /work2/noaa/da/rtreadon/git/gsi/pr656/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  482.60 sec
2/7 Test #7: global_enkf ......................   Passed  488.66 sec
3/7 Test #3: rrfs_3denvar_glbens ..............   Passed  545.84 sec
4/7 Test #2: rtma .............................   Passed  1208.27 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1335.62 sec
6/7 Test #5: hafs_4denvar_glbens ..............***Failed  1515.97 sec
7/7 Test #1: global_4denvar ...................   Passed  1682.51 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 1682.51 sec

The following tests FAILED:
          5 - hafs_4denvar_glbens (Failed)
Errors while running CTest
Output from these tests are in: /work2/noaa/da/rtreadon/git/gsi/pr656/build/Test                                                             ing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
The `hafs_4denvar_glbens` failed due to a runtime check
```
The runtime for hafs_4denvar_glbens_loproc_updat is 410.943114 seconds.  This has exceeded maximum allowable threshold time of 407.720619 seconds,
resulting in Failure time-thresh of the regression test.
```
A check of the `gsi.x` wall times confirms that the loproc_updat time was noticeably higher than the loproc_contrl.
```
hafs_4denvar_glbens_hiproc_contrl/stdout:The total amount of wall time                        = 274.727002
hafs_4denvar_glbens_hiproc_updat/stdout:The total amount of wall time                        = 281.556165
hafs_4denvar_glbens_loproc_contrl/stdout:The total amount of wall time                        = 370.655109
hafs_4denvar_glbens_loproc_updat/stdout:The total amount of wall time                        = 410.943114
```
A rerun of the `hafs_4denvar_glbens` test resulted in a _Passed_ result 
```
Test project /work2/noaa/da/rtreadon/git/gsi/pr656/build
    Start 5: hafs_4denvar_glbens
1/1 Test #5: hafs_4denvar_glbens ..............   Passed  1576.54 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 1576.55 sec
```
with the following `gsi.x` wall times.
```
hafs_4denvar_glbens_hiproc_contrl/stdout:The total amount of wall time                        = 259.300913
hafs_4denvar_glbens_hiproc_updat/stdout:The total amount of wall time                        = 283.951111
hafs_4denvar_glbens_loproc_contrl/stdout:The total amount of wall time                        = 428.779788
hafs_4denvar_glbens_loproc_updat/stdout:The total amount of wall time                        = 386.123849
```

Acceptable results are obtained from ctests run on Hera, Orion, and WCOSS2 (Cactus).

**Pull request merged**
