### PR TITLE
merge recent updates and bug fixes in EnKF

### PR DESCRIPTION
**Pull request by jswhit**
also adds 'beta_e0' parameter to GSI (so weights given to ensemble and static B don't have to sum to 1)

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Technical review complete.   Regression tests run on WCOSS_D using `NOAA-EMC:master` at 2bcedcb and `jswhit:feature/enkf-64bit` at  e2819e5.  All regressions tests passed.   

Set up single cycle C768L127 gdas/enkf only parallel on WCOSS_D.   Run 2021111112 gdas cycle.  First pass used `NOAA-EMC:master` for DA component.   Save results, rewind, and rerun using `jswhit:feature/enkf-64bit` for DA component.   Output from anal, eobs, and ediag are identical.   Output from eupd (global_enkf.x) differ    The workflow runs global_enkf.x in LETKF mode.   The enkf regression test runs with `LETKF_FLAG=F`.   

Do we expect LETKF results from  `jswhit:feature/enkf-64bit`  to differ from `NOAA-EMC:master`?

This PR probably can not be further processed as is.   I think `jswhit:feature/enkf-64bit` needs to be merged into `jswhit:master` such that `jswhit:master` is one commit ahead of `NOAA-EMC:master`.   PR #219 will likely enter `NOAA-EMC:master` next week.   These changes will also need to pulled into `jswhit:master`.

**Comment by jswhit2** [comment]
@RussTreadon-NOAA yes, the LETKF results will not be bit identical because the precision of some variables has changed

**Comment by jswhit2** [comment]
regarding merging this into `jswhit::master`, I've been keeping it up to date with `NOAA-EMC::master`, and then merging `jswhit::master` into jswhit::feature/enkf64bit` to keep it up to date.  Can `jswhit::feature/enkf64bit` not be merged into `NOAA-EMC::master` directly via this PR?

**Comment by RussTreadon-NOAA** [comment]
Thanks, @jswhit , for confirming that the difference is expected.

**Review by RussTreadon-NOAA — APPROVED** [review]
Changes look good.  Assuming regression tests have been run and acceptable results obtained, we can send these changes out to the DA Review Committee.

**Comment by MichaelLueken-NOAA** [comment]
Since PR #281 has been merged to the authoritative repository, I will now close this PR.

**Pull request closed without merging**
