### PR TITLE
Port gsi to WCOSS2 & Remove hardwired version nums

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
1) Port GSI for GEFSv12 to WCOSS2
2) Update build modules to remove hardwired version numbers

 On branch feature/gefs_v12_port2wcoss2
 Changes to be committed:
	new file:   modulefiles/modulefile.ProdGSI.wcoss2
	modified:   ush/build_all_cmake.sh

Refs: #183

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
These changes are required for the GEFS v12 implementation to compile on WCOSS2.  I will merge these changes into the release branch associated with GEFS v12 (release/gefs_v12) at this time.

**Comment by XianwuXue-NOAA** [comment]
@MichaelLueken-NOAA Could you review my changes? After your approval and merging, could you please create a tag as  "gefs.v12.2.0"? Thanks.

**Comment by MichaelLueken-NOAA** [comment]
@XianwuXue-NOAA I have created tag gefs.v12.2.0 in the authoritative repository.  Please let me know if there are any issues.

**Comment by XianwuXue-NOAA** [comment]
@MichaelLueken-NOAA Thank you very much for your help and quick response.

**Pull request merged**
