### PR TITLE
GitHub Issue NOAA-EMC/GSI#311. Update scripts needed for EFSOI 

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
These are catching up various EFSOI-specific scripts: changes to reflect GSI and global-workflow, some refactoring

Files included:

jobs/JGDAS_EFSOI
jobs/JGDAS_EFSOI_FCST
scripts/exgdas_efsoi.sh
scripts/exgdas_efsoi_update.sh

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
Hi @AndrewEichmann-NOAA, Is there anyone that you would like to have review these modifications to the j-jobs and scripts, or are they ready to go?  If they are ready as is, please update the commit message so that it has:

`GitHub Issue NOAA-EMC/GSI#311`

To do this:

1) Make sure that you are in your EXP-efso_fv3_issue_311 branch
2) git commit --amend
3) Replace added for issue 311 with `GitHub Issue NOAA-EMC/GSI#311`
4) Save and close the commit message window
5) git push origin EXP-efso_fv3_issue_311 --force

There is an update out for review and will be merged to the authoritative repo on Monday.  Once that goes in, I will be able to merge this update to the authoritative repo.

Otherwise, please let me know who you would like to have review this work.

**Comment by AndrewEichmann-NOAA** [comment]
@MichaelLueken-NOAA I could suggest @CatherineThomas-NOAA and @aerorahul for review, but they're probably ready to go since I have been using them for a couple months unchanged.

I've made the changes in the branch as requested.

**Comment by MichaelLueken-NOAA** [comment]
@AndrewEichmann-NOAA Thanks for making the modification to the commit message.  I will merge these changes to the authoritative repo on Monday after the current work that is out to the review committee has been merged.

**Comment by AndrewEichmann-NOAA** [comment]
@MichaelLueken-NOAA Ok, thanks! Have a good weekend.

**Comment by MichaelLueken-NOAA** [comment]
No changes were made to the source code, so I will now give final approval to these changes and merge them to the authoritative repository.

**Pull request merged**
