### PR TITLE
Update global_satinfo.txt: turn off VIIRS data (set to monitoring mode)

### PR DESCRIPTION
**Pull request by emilyhcliu**
We need to turn off VIIRS radiance data and set it to monitoring mode in gfsda.v16.3.0 ([Issue #486 ](https://github.com/NOAA-EMC/GSI/issues/486))
The only file change is in fix/global_sainto.txt.

The change in GSI fix is done in branch fix_gfsda.v16.3.0
There are no code changes in GSI except the fix.

```
 viirs-m_npp            12  -1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_npp            13  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_npp            14  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_npp            15  -1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_npp            16  -1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             12  -1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             13  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_j1             14  -1    0.800    0.000    6.000   10.000    0.000     -1     -1     -1
 viirs-m_j1             15  -1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
 viirs-m_j1             16  -1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
```

A real-time parallel experiment will be conducted to test the impact of VIIRS.

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Check out a fresh clone of `release/gfsda.v16.3.0` and `release/gfsda.v16.3.0_viirs`.   A recursive diff of the two directories, excluding `.git`, shows the only differences to be

```
diff -r '--exclude=.git' gfsda.v16.3.0/fix/global_satinfo.txt viirs/fix/global_satinfo.txt
3877c3877
<  viirs-m_npp            12   1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
---
>  viirs-m_npp            12  -1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
3880,3882c3880,3882
<  viirs-m_npp            15   1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
<  viirs-m_npp            16   1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
<  viirs-m_j1             12   1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
---
>  viirs-m_npp            15  -1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
>  viirs-m_npp            16  -1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
>  viirs-m_j1             12  -1    0.500    0.000    6.000   10.000    0.000      1     -1     -1
3885,3886c3885,3886
<  viirs-m_j1             15   1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
<  viirs-m_j1             16   1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
---
>  viirs-m_j1             15  -1    0.580    0.000    6.000   10.000    0.000      1     -1     -1
>  viirs-m_j1             16  -1    0.620    0.000    6.000   10.000    0.000      1     -1     -1
```
A visual check of `release/gfsda.v16.3.0_viirs` confirms that all `viirs` lines have the data in monitor mode (-1).   This is correct.

Comments in `fix/gfsv16_historical/gfsv16.3/README` state
```
# Turn on assimilation of MetOp-C IASI
# This file is identical to global_satinfo.txt
global_satinfo.txt.2021102612
```

This statement is no longer true.   File `global_satinfo.txt.2021102612` still has some viirs changes in assimilate (1) mode.    Do we 
1. update `global_satinfo.txt.2021102612` to be consistent with `global_satinfo.txt`
2. add a new `global_satinfo.txt.YYYYMMDDHH` identical to `global_satinfo.txt`
3. something else?

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA 
We only turn off the VIIRS BTs  in the real-time run since the VIIRS BTs are missing in real-time (sometime in June 2022)
NESDIS discontinued the VIIRS BTs product without seeing any notifications to EMC.

We do have VIIRS data before June 2022 and were tested.  So, the EMC retrospective (from October 2021 - Feb 2022) is assimilating VIIRS BTs data.

We do not need to touch the history satinfo for gfsda.v16.3.0

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , OK.  If we do not need to edit a existing satinfo file in or add a new satinfo file to `fix/gfsv16_historical/gfsv16.3/` for consistency we need to remove the line

`# This file is identical to global_satinfo.txt`

in `fix/gfsv16_historical/gfsv16.3/README`

This line is no longer true.   It's presence could confuse developers or us when we work on the next GFS implementation.

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA  
NESDIS discontinued the data in June, and is put the product back on their operational stream since 20221005 00Z.
In principle, we should be able to use the VIIRS BTs as soon as they are available.  However, we do have some concerns about NESDIS data delivery recently.  We got ASCAT MetOP-B/C data in the operational stream a few weeks ago. ASCAT MetOp-B is already in operation, and MetOp-C is new.  However, due to changes in the ASCAT bufr format (just format change, no scientific change), the ASCAT MetOp-B/C data are delivered as a new product.  

We tested the new MetOP-B/C ASCAT product.  The quality was not expected.  The wind directions are systematically 180 degrees than the original product. The QC threw out most of the data.  

Therefore, we are more careful about using new products from NESDIS.  We want to test it before we turn it on.
I am running a real-time parallel with VIIRS data (we only run GDAS since we will only look at NSST performance).  EMC real-time parallel (Lin's run) already had the VIIRS off.

**Comment by emilyhcliu** [comment]
> @emilyhcliu , OK. If we do not need to edit a existing satinfo file in or add a new satinfo file to `fix/gfsv16_historical/gfsv16.3/` for consistency we need to remove the line
> 
> `# This file is identical to global_satinfo.txt`
> 
> in `fix/gfsv16_historical/gfsv16.3/README`
> 
> This line is no longer true. It's presence could confuse developers or us when we work on the next GFS implementation.

Yes, I will modify the README.

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA I modified the README file (for gfsv16.3 historical files).

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , sorry but I do not see a update to `fix/gfsv16_historical/gfsv16.3/README`.   We should see a change in the hash for the fix submodule.   According to the github [commit history](https://github.com/NOAA-EMC/GSI/commits/release/gfsda.v16.3.0_viirs) for `release/gfsda.v16.3.0_viirs`, the last commit was four hours ago (10/7/2022 8:21 AM EDT).

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA I am sorry. I forgot to push the changes back.  
The REAME file should be updated now in the repository.

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , updated `README` looks good.

**Review by RussTreadon-NOAA — APPROVED** [review]
Top level `fix/global_satinfo.txt` contains advertised changes:  place VIIRS data in monitor mode (-1).   `fix/gfsv16_historical/gfsv16.3/README` contains a corresponding descriptive comment.

Approve changes.

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , tag [`gfsda.v16.3.0`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.0) has been created as a snapshot of `release/gfsda.v16.3.0` at [3fb30e4](https://github.com/NOAA-EMC/GSI/commit/3fb30e4caeedb30591fbdc2224930c516c2ca74a).

**Pull request merged**
