### PR TITLE
Add activation of Himawari-9 to the implementation branch (for the gfsda.v16.3.12 tag)

### PR DESCRIPTION
**Pull request by ADCollard**
@HaixiaLiu-NOAA pointed out the the changes to the fix files in #660 did not include Himawari-9.  This PR turns on channels 8 and 9 of Himawari-9 in Release/gfsda.v16.

Changes are to the fix file only.

To inspect the changes you will need to:
```
git clone --recursive https://github.com/ADCollard/GSI.git GSI_ACollard
cd GSI_ACollard
git checkout release/gfsda.v16
git submodule sync
git submodule update
cd fix
```
Checklist

My code follows the style guidelines of this project
I have performed a self-review of my own code
I have commented my code, particularly in hard-to-understand areas
New and existing tests pass with my changes
Any dependent changes have been merged and published

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Clone [ADCollard:release/gfsda.v16](https://github.com/ADCollard/GSI/tree/release/gfsda.v16) and current head of [NOAA-EMC:release/gfsda.v16](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) on Orion.  After `git submodule sync` and `git submodule update` compare the two working copies.  Only difference, excluding `.git`, is `fix/global_satinfo.txt`.

`ADCollard:release/gfsda.v16` sets the usage flag to 1 (assimilate) for channels 8 and 9 of ahi_himawari9.  This is consistent with the stated purpose of this PR.

Approve, but I will not merge this PR into `NOAA-EMC:release/gfsda.v16` until the two peer reviewers approve the PR.  After merger, tag `gfsda.v16.3.12` will be recreated from the updated head of `NOAA-EMC:release/gfsda.v16`.

**Comment by RussTreadon-NOAA** [comment]
Notice that `ADCollard:release/gfsda.v16` is one commit behind `NOAA-EMC:release/gfsda.v16`.   This is odd.  `ADCollard:release/gfsda.v16` should be one commit ahead of `NOAA-EMC:release/gfsda.v16`.   Clones of each branch shows the correct change. `ADCollard:release/gfsda.v16`  updates `fix/global_satinfo.txt`.   

Suspect the issue is that `ADCollard:release/gfsda.v16`  was not updated with the current head of `NOAA-EMC:release/gfsda.v16` prior to updating the `fix` associated with `ADCollard:release/gfsda.v16`.   The preferred way to resolve this is to 
1. update `ADCollard:release/gfsda.v16` with `NOAA-EMC:release/gfsda.v16`
2. update fix submodule in `ADCollard:release/gfsda.v16`

An alternative is to skip this PR and directly update the fix submodule in `NOAA-EMC:release/gfsda.v16` to the correct hash.

**Comment by ADCollard** [comment]
@RussTreadon-NOAA Sorry for missing that and thanks for spotting it.   I think it is correct now.

... although I cannot actually see what the errant commit was.

**Comment by RussTreadon-NOAA** [comment]
Looks good now.  No more conflicts with `fix`.  Thank you @ADCollard

**Comment by emilyhcliu** [comment]
@ADCollard  Just to confirm,  we want H8, channels 8 and 9 assimilated, and channel 10 will be passive.  Is that correct?

**Comment by ADCollard** [comment]
> @ADCollard Just to confirm, we want H8, channels 8 and 9 assimilated, and channel 10 will be passive. Is that correct?

@emilyhcliu This should be turning on H-9 channels 8 & 9, not H-8.   Hopefully @HaixiaLiu-NOAA can confirm this is correct.

**Comment by RussTreadon-NOAA** [comment]
Refresh a working copy of [`ADCollard:release/gfsda.v16`](https://github.com/ADCollard/GSI/tree/release/gfsda.v16) to [dbc2512](https://github.com/ADCollard/GSI/commit/dbc251286a97c169c269215e100499ac65732e33).   Compare working copy with [`NOAA-EMC:release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16).  The only difference is `fix/global_satinfo.txt`.  This PR sets the usage flags for channels 8 and 9 of `ahi_himawari9` to 1 (assimilate).
```
 ahi_himawari9           7  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9           8   1    3.000    0.000    4.000   10.000    0.000     -2     -1     -1
 ahi_himawari9           9   1    2.500    0.000    4.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          10  -1    2.200    0.000    3.500   10.000    0.000     -2     -1     -1
 ahi_himawari9          11  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          12  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          13  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          14  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          15  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          16  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
```

The ahi_himawari9 usage flags above differ slightly from ahi_himawari8.   `global_satinfo.txt` has a usage flag of 1 (assimilate) for ahi_himawari8 channels 8, 9, and 10.
```
 ahi_himawari8           7  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari8           8   1    3.000    0.000    4.000   10.000    0.000     -2     -1     -1
 ahi_himawari8           9   1    2.500    0.000    4.000   10.000    0.000     -2     -1     -1
 ahi_himawari8          10   1    2.200    0.000    3.500   10.000    0.000     -2     -1     -1
 ahi_himawari8          11  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari8          12  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari8          13  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari8          14  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari8          15  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari8          16  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
```
This is @emilyhcliu 's question.   Do we want to assimilate ahi_himawari9 channel 10 in addition to channels 8 and 9?

**Comment by ADCollard** [comment]
> > @ADCollard Just to confirm, we want H8, channels 8 and 9 assimilated, and channel 10 will be passive. Is that correct?
> 
> @emilyhcliu This should be turning on H-9 channels 8 & 9, not H-8. Hopefully @HaixiaLiu-NOAA can confirm this is correct.

@emilyhcliu Sorry I misunderstood.  H-9 Ch 10 is now on!  Thank you!

**Comment by RussTreadon-NOAA** [comment]
Refresh working copy of `ADCollard:release/gfsda.v16`.   Now ahi_himawari9 channels 8, 9, and 10 have a usage flag of 1 (assimilate).   
```
 ahi_himawari9           7  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9           8   1    3.000    0.000    4.000   10.000    0.000     -2     -1     -1
 ahi_himawari9           9   1    2.500    0.000    4.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          10   1    2.200    0.000    3.500   10.000    0.000     -2     -1     -1
 ahi_himawari9          11  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          12  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          13  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          14  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          15  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
 ahi_himawari9          16  -1    2.200    0.000    2.000   10.000    0.000     -2     -1     -1
```
This is consistent with ahi_himawari8.

**Comment by RussTreadon-NOAA** [comment]
Tag [`gfsda.v16.3.12`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.12) created from [`NOAA-EMC:release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) at 681e2ee.

**Comment by emilyhcliu** [comment]
> > > @ADCollard Just to confirm, we want H8, channels 8 and 9 assimilated, and channel 10 will be passive. Is that correct?
> > 
> > 
> > @emilyhcliu This should be turning on H-9 channels 8 & 9, not H-8. Hopefully @HaixiaLiu-NOAA can confirm this is correct.
> 
> @emilyhcliu Sorry I misunderstood. H-9 Ch 10 is now on! Thank you!

Ha! I am dumb.  H8 should be H9.  Yes. My question is for H9.

**Pull request merged**
