### PR TITLE
GitHub Issue NOAA-EMC/GSI#68. Switches assimilating Ta to Tb.

### LINKED ISSUE #68: Switching from assimilating microwave antenna temperatures to brightness temperatures
This is to switch from assimilating satellite microwave antenna temperature observations to brightness temperatures.

As it is now, the bias between the observed antenna temperature and the simulated brightness temperature is being handled by the variational bias correction. For the platforms and feeds which have only antenna temperature, an accurate formula for converting antenna temperatures to brightness temperatures will be used. Doing this and assimilating brightness temperatures removes a burden of the variational bias correction.

Many (or all) other centers are assimilating brightness temperatures.

### PR DESCRIPTION
**Pull request by ScottSieron-NOAA**
This PR switches from assimilating satellite microwave antenna temperature (Ta) observations to brightness temperatures (Tb). This required:
- a function to apply the antenna correction to antenna temperatures
- changing which mnemonic is read from bufr files

Another set of changes, required for accurate Tb assimilation, is adding the support for multiple versions of antenna correction coefficients (ACCoeffs), each of which is in a version of CRTM SpcCoeff files. This required
- reading the satellite antenna correction version from the bufr file
- checking for the existence of multiple versions of the SpcCoeff file for a given satellite/sensor
- if a different version of ACCoeffs is used for a given observation, then remove this antenna correction, and then apply the first version of the antenna correction

Several regression tests failed, noted in the issue.

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
Hi @ScottSieron-NOAA, Thanks for updating your issue with the regression test results and creating the PR.  Please let me know who you would like to have review your changes, and I will assign them.  If you have any questions about any of the steps that you have followed up to this point, please let me know.

**Review by ADCollard — COMMENTED** [review]
amsua_metop-a_v2.SpcCoeff.bin is not available in CRTMv2.3.0 as far as I can tell.   So we cannot proceed with this pull request at present.   Presumably this file is available in 2.4.0?

**Comment by HaixiaLiu-NOAA** [comment]
The v2 SpcCoeff files are not in 2.4.0 yet so far. Already contacted Ben who will update us on this.

**Comment by emilyhcliu** [comment]
This PR is combined with [PR #350](https://github.com/NOAA-EMC/GSI/pull/350).  This PR can be closed.

**Comment by MichaelLueken** [comment]
As noted from @emilyhcliu above, these changes were brought into the authoritative repository via PR #350.  PR #350 was merged to the authoritative repository on 05/03/2022 at [c13361c](https://github.com/NOAA-EMC/GSI/commit/c13361c587503298907480d14ef5c92ecb0be3f7), so I will now close this PR.

**Pull request closed without merging**
