### PR TITLE
HAFS related ENKF changes to do recentering and ensemble meaning  to support the self-cycled EnsDA 

### LINKED ISSUE #610: HAFS related ENKF changes to support the self-cycled ENSDA capability
Bring in the HAFS related ENKF changes to support the self-cycled ENSDA capability. The changes mainly developed and leveraged from Ting Lei (EMC).

## Related to (optional)
- Addressed by NOAA-EMC/GSI/pull/pr#

### PR DESCRIPTION
**Pull request by TingLei-NOAA**
This planned PR include two functions for GSI EnKF had been developed and used 
for HAFS DA:  using EnKF to do recentering and calculation of the ensemble meaning. 
Those functions are developed by use of original EnKF interface with minimal changes to the later. 
Fixes https://github.com/NOAA-EMC/GSI/issues/610.

**How Has This Been Tested?**
These function has been tested and used by HAFS DA and is regarded as well verified and validated.
For this PR with merging current EMC GSI, a few local test will be done. 
Hence, this PR is currently labelled as "draft PR" 
This PR is submitted by @TingLei-NOAA and @BinLiu-NOAA .  That will be great if @jswhit and @daviddowellNOAA could be the reviewers. 

**DUE DATE for merger of this PR into `develop` is 1/23/2024 (six weeks after PR creation).**

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@TingLei-NOAA , two requests
1. Please post ctest (regression test) results in this PR or the originating issue, #610
2. Click _Ready for review_ to move this PR forward

**Comment by RussTreadon-NOAA** [comment]
**WCOSS (Dogwood) ctest**
Install `hafs-community:feature/hafs_enkf_merge` on Dogwood.   Run `global_enkf` ctest.  

```
russ.treadon@dlogin04:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr667/build> ctest -R global_enkf
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr667/build
    Start 7: global_enkf
1/1 Test #7: global_enkf ......................***Failed   60.24 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =  63.08 sec

The following tests FAILED:
          7 - global_enkf (Failed)
Errors while running CTest
```
`enkf.x` aborted with the following traceback
```
forrtl: severe (24): end-of-file during read, unit 912, file /lfs/h2/emc/ptmp/russ.treadon/pr667/tmpreg_global_enkf/global_enkf_loproc_updat/enkf.nml, line 133, position 0
Image              PC                Routine            Line        Source
enkf.x             0000000001808C6B  Unknown               Unknown  Unknown
enkf.x             00000000018430FD  Unknown               Unknown  Unknown
enkf.x             000000000046B01C  params_mp_read_na         490  params.f90
enkf.x             0000000000412EB1  MAIN__                    125  enkf_main.f90
```
Code around line 490 of `src/enkf/params.f90` is
```
if (fv3_native) then
  read(912,nam_fv3)
  nlons = nx_res; nlats = ny_res ! (total number of pts = ntiles*res*res)                                                                                                                          
endif
```
`params.f90` initializes `fv3_native` to `true` on declaration
```
! use fv3 cubed-sphere tiled restart files                                                                                                                                                         
logical,public :: fv3_native = .true.
```
However, `regressions/regression_namelists.sh` does not include namelist `nam_fv3`.   Hence the aborted execution.

The GDAS execution of `enkf.x` does not read tiles at present.  While `fv3_native` may be set to `.false.` via namelist `nam_enkf`, it is preferable to initialize `fv3_native` to .`false.` in `params.f90` and require the user to set `fv3_native=.true.` in namelist `nam_enkf` if they want to run `enkf.x` in this mode.

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA So many thanks for running those regression tests, which I had been expecting to run along with other local regression tests.  I will have this issue fixed as you suggested and proceed on this PR as soon as possible.

**Comment by jswhit2** [comment]
@TingLei-NOAA - can you explain the purpose of the new option ``l_do_enscalc``?  It looks like it just bypasses the EnKF update and computes ensemble means and does recentering?  But only for the regional model?

**Comment by TingLei-NOAA** [comment]
@jswhit2  I should have added some doc in the code.  Yes.  l_do_enscale is used to control what function is to be done:
=0, the regular enkf update; =1, ensemble meaning ; =2, recentering.   It has been tested and used for fv3reg but conceptually, it should also work for global cases (and other regional applications).

**Comment by jswhit2** [comment]
@TingLei-NOAA OK, thanks for that explanation.  My next question is why would you just not use an offline utility for that simple operation, instead of adding this option to the EnKF code? (as is one now for the global model)?  Is the motivation to avoid having to read and write the data multiple times?  (if so, it doesn't seem like this approach avoids that)

**Comment by TingLei-NOAA** [comment]
@jswhit2  When we developed this function on top of the fv3reg enkf, there is no off-line tools for ensemble meaning and recentering for fv3reg,  in addition to saving coding efforts for a new off-line tool, this function attached to the EnKF   allow us make use of the efficient IO interface.   Later,  RRFS develops have developed their own off-line tools and, this EnKF functions have been used by HAFS DA scientist.

**Comment by RussTreadon-NOAA** [comment]
I agree with @jswhit2 .  

[NOAA-EMC/GSI-utils](https://github.com/NOAA-EMC/GSI-utils) contains codes for recentering and computing ensemble means.   Check [NOAA-EMC/GSI-utils/develop/src/EnKF/gfs/src](https://github.com/NOAA-EMC/GSI-utils/tree/develop/src/EnKF/gfs/src) for examples of global utilities.

The source code in [NOAA-EMC/GSI:src/gsi](https://github.com/NOAA-EMC/GSI/tree/develop/src/gsi) is for variational DA.  The source code in [NOAA_EMC/GSI:src/enkf](https://github.com/NOAA-EMC/GSI/tree/develop/src/enkf) is for ensemble DA.  Both are analysis codes, not utility codes.

**Comment by TingLei-NOAA** [comment]
@RussTreadon-NOAA and @jswhit2   Your opinions will be shared with collaborators and users of this function attached to EnKF.

**Comment by BinLiu-NOAA** [comment]
@jswhit2, @RussTreadon-NOAA, @TingLei-NOAA, please feel free to correct me if I am wrong. My understanding is that for GSI/EnKF, the capabilities of conducting ensemble mean and recenter (together with EnKF update) have already been there to support regional models (e.g., GSI/EnKF for HWRF, maybe also WRF, not sure about NMMB though) previously. The current development is try to expand and add similar functions so that it can work for the regional FV3ATM model.

Meanwhile, if the consensus is to not include the EnKF mean and recenter capabilities for regional FV3ATM interface, we (from the HAFS application side) will then try to use the same/similar method (through off-line tools) the RRFS application is using (assuming it works fine/efficiently and it is available). Thanks!

**Comment by TingLei-NOAA** [comment]
@BinLiu-NOAA  The ensemble meaning and recentering function doesn't exist in the authoritative GSI/EnKF. It was added to the GSI EnKF for use of FV3REG while the code changes are (needs to be )  in the general EnKF part (and should work for all other global/regional applications)

**Comment by hu5970** [comment]
The RRFS has a separate utility to do recenter and calculate ensemble mean. It uses netcdf parallel IO to read in all of the fields from a ensemble member files at the same time. The RRFS has 30 member NA 3km grid ensembles, it takes 10 wcoss2 nodes (1280 cores) to run. The ensemble mean takes 4 to 5 minutes. The recenter takes about 7-8 minutes.

Please let me know if you need more details on the RRFS recenter/ensemble mean utility.

**Comment by BinLiu-NOAA** [comment]
> The RRFS has a separate utility to do recenter and calculate ensemble mean. It uses netcdf parallel IO to read in all of the fields from a ensemble member files at the same time. The RRFS has 30 member NA 3km grid ensembles, it takes 10 wcoss2 nodes (1280 cores) to run. The ensemble mean takes 4 to 5 minutes. The recenter takes about 7-8 minutes.
> 
> Please let me know if you need more details on the RRFS recenter/ensemble mean utility.

Thanks, @hu5970! We will reach out to you and/or other RRFS collaborators for help with the RRFS recenter/ensemble mean utility. Thanks!

**Comment by RussTreadon-NOAA** [comment]
Thank you @BinLiu-NOAA for working with the RRFS team on ensemble mean and recentering utilities.  I take this to mean this PR may be closed.  I'll do so upon your confirmation.

**Comment by BinLiu-NOAA** [comment]
> Thank you @BinLiu-NOAA for working with the RRFS team on ensemble mean and recentering utilities. I take this to mean this PR may be closed. I'll do so upon your confirmation.

@RussTreadon-NOAA, I will communicate with @TingLei-NOAA offline for some technical details. And will respond/follow-up this GitHub thread afterwards. Thanks!

**Comment by RussTreadon-NOAA** [comment]
Thank you @BinLiu-NOAA for your reply.  May I close this PR?

**Comment by BinLiu-NOAA** [comment]
> Thank you @BinLiu-NOAA for your reply. May I close this PR?

@RussTreadon-NOAA I got a chance and communicated with @TingLei-NOAA. And we agree this PR can be closed. From HAFS side, we will try to adapt the RRFS approach for ensemble mean/recenter steps. Thanks!

**Comment by RussTreadon-NOAA** [comment]
Closing with developer consent.  Thank you @BinLiu-NOAA

**Pull request closed without merging**
