### PR TITLE
GitHub Issue NOAA-EMC/GSI#424.  Remove utilities from GSI repository

### LINKED ISSUE #424: Separate out utilities into its own repository
This issue is to separate out the utilities from the GSI repository into its own repository.

### PR DESCRIPTION
**Pull request by aerorahul**
GSI Utilities have a new home at: https://github.com/NOAA-EMC/GSI-utils

closes #424

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Changes looks good.  Two comments.

1) From a g-w perspective we need to add `NOAA-EMC/GSI-utils` to the g-w checkout and build once the g-w build of NOAA-EMC/GSI moves to or after the hash at which this PR enters GSI `develop`.    

2) In light of #426 line 110 of `ush/prune_4nco_global.sh` may be simplified to `rlist="sub"`.  Assuming #426 is acted upon prior to this PR, the merge of `develop` into `feature/separate-out-utilities` will accomplish this.

**Comment by aerorahul** [comment]
> Changes looks good. Two comments.
> 
>     1. From a g-w perspective we need to add `NOAA-EMC/GSI-utils` to the g-w checkout and build once the g-w build of NOAA-EMC/GSI moves to or after the hash at which this PR enters GSI `develop`.
> 
>     2. In light of #426 line 110 of `ush/prune_4nco_global.sh` may be simplified to `rlist="sub"`.  Assuming #426 is acted upon prior to this PR, the merge of `develop` into `feature/separate-out-utilities` will accomplish this.

Thanks @RussTreadon-NOAA for catching the linking of the directories.
I have retained the names of the executables to be consistent with the source code.  `ncdiag.fd` will become moot soon.

**Comment by aerorahul** [comment]
> > Changes looks good. Two comments.
> > ```
> > 1. From a g-w perspective we need to add `NOAA-EMC/GSI-utils` to the g-w checkout and build once the g-w build of NOAA-EMC/GSI moves to or after the hash at which this PR enters GSI `develop`.
> > 
> > 2. In light of #426 line 110 of `ush/prune_4nco_global.sh` may be simplified to `rlist="sub"`.  Assuming #426 is acted upon prior to this PR, the merge of `develop` into `feature/separate-out-utilities` will accomplish this.
> > ```
> 
> Thanks @RussTreadon-NOAA for catching the linking of the directories. I have retained the names of the executables to be consistent with the source code. `ncdiag.fd` will become moot soon.



> > Changes looks good. Two comments.
> > ```
> > 1. From a g-w perspective we need to add `NOAA-EMC/GSI-utils` to the g-w checkout and build once the g-w build of NOAA-EMC/GSI moves to or after the hash at which this PR enters GSI `develop`.
> > 
> > 2. In light of #426 line 110 of `ush/prune_4nco_global.sh` may be simplified to `rlist="sub"`.  Assuming #426 is acted upon prior to this PR, the merge of `develop` into `feature/separate-out-utilities` will accomplish this.
> > ```
> 
> Thanks @RussTreadon-NOAA for catching the linking of the directories. I have retained the names of the executables to be consistent with the source code. `ncdiag.fd` will become moot soon.
oops. wrong thread.

**Comment by MichaelLueken** [comment]
@aerorahul Please add the issue number, similar to PR #426, to the single commit message in this PR:

git commit --amend
Please add `GitHub Issue NOAA-EMC/GSI#424` to the commit message
git push origin feature/separate-out-utilities --force

I will then be able to merge this work to the authoritative develop branch tomorrow after the current work out for review has been merged.

**Comment by aerorahul** [comment]
> @aerorahul Please add the issue number, similar to PR #426, to the single commit message in this PR:
> 
> git commit --amend Please add `GitHub Issue NOAA-EMC/GSI#424` to the commit message git push origin feature/separate-out-utilities --force
> 
> I will then be able to merge this work to the authoritative develop branch tomorrow after the current work out for review has been merged.

Done.

**Comment by MichaelLueken** [comment]
Since there are no changes to the source code and @RussTreadon-NOAA has approved these changes, I will give final approval and merge this work to the authoritative develop branch.

**Pull request merged**
