### PR TITLE
Add assimilation of GLM flash-extent density (FED) observations to EnKF

### LINKED ISSUE #653: Add capability of assimilating GLM flash extent density (FED) observations with EnKF
RRFS version 1 will assimilate Geostationary Lightning Mapper (GLM) flash extent density (FED) observations.  Recent GSI PRs have added a FED observation operator and deterministic (EnVar) assimilation of FED observations.  The last needed capability for RRFS is EnKF assimilation of FED observations for the ensemble members.

### PR DESCRIPTION
**Pull request by daviddowellNOAA**
**Description**

Fixes https://github.com/NOAA-EMC/GSI/issues/653

The proposed code changes
(1) add a new "fed" observation type to the EnKF
(2) add localization parameters, with namelist control, for FED observations
(3) output basic statistics for FED observations.

In the RRFS, the FED observations will be assimilated together with radar-reflectivity observations.  The localization parameters for the reflectivity observations in RRFS are corrlength=18 and lnsigcutoff=0.5.  However, these tight localization distances don't work well for the sparse FED observations.  Therefore, localization parameters for FED observations, with namelist control, were added to allow the FED observations to influence the model state over longer distances.  The default localization parameters for FED observations (corrlength=30 and lnsigcutoff=2.0) were determined through experimentation with WRF and FV3 convection-allowing (3-km horizontal grid spacing) ensembles.

Screen Shot 2023-11-08 at 8 53 09 AM
Screen Shot 2023-11-08 at 8 53 02 AM

**Type of change**

- [X] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

Hourly cycling with simultaneous EnKF assimilation of FED and radar-reflectivity observations has been tested for a CONUS version of the prototype RRFSv1 for two short (1-2 days) retrospective periods, one in July 2022 and the other in August 2023.  The impacts of the FED observations on the analyses are greatest over the oceans far from land, where the radar network does not provide observations.

**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

**DUE DATE for this PR is 12/20/2023.** If this PR is not merged into `develop` by this date, the PR will be closed and returned to the developer.

### CODE REVIEW

**Comment by hongli-wang** [comment]
@hu5970 
Hi.

**Comment by TingLei-NOAA** [comment]
@daviddowellNOAA   is the current change only dealing with binary diag files?  if so, what is the plan for netcdf diag files?

**Comment by hu5970** [comment]
@hongli-wang 
Hongli, we are not able to add you as reviewer somehow but please review and code and make your comments. Thanks, Ming.

**Comment by hongli-wang** [comment]
> @hongli-wang Hongli, we are not able to add you as reviewer somehow but please review and code and make your comments. Thanks, Ming.

@hu5970 @daviddowellNOAA 

The code is pretty clean and fellow the same procedures for other types of observations. I don't think there should be issues there as David has tested the run. 

Just curious if a brief description on the new parameters could be added somewhere in the code. 

Thanks, 
Hongli

**Comment by RussTreadon-NOAA** [comment]
@hongli-wang 
We invited you to join NOAA-EMC/GSI as an outside collaborator.  Please check your email for an invitation.  If you accept the invitation, we should be able to add you as a reviewer on GSI PRs.

**Comment by hongli-wang** [comment]
> @hongli-wang We invited you to join NOAA-EMC/GSI as an outside collaborator. Please check your email for an invitation. If you accept the invitation, we should be able to add you as a reviewer on GSI PRs.

@RussTreadon-NOAA 
Thanks for your invitation. Accepted!

**Comment by RussTreadon-NOAA** [comment]
@hongli-wang , thank you for accepting the invitation.  Now we can formally add you as a reviewer on this PR.  Thanks!

**Review by hongli-wang — APPROVED** [review]

**Comment by hu5970** [comment]
@daviddowellNOAA Could you answer Ting's question? Thanks, Ming

**Comment by daviddowellNOAA** [comment]
@TingLei-NOAA The tests of the EnKF assimilation of FED data into a prototype RRFS used netcdf diag files.  I think the new functionality should also work for binary diag files, but I can't confirm with tests.

**Comment by daviddowellNOAA** [comment]
@hongli-wang The documentation within the code is very limited, and I only included a mention of "fed obs" in enkf.f90.  There is good documentation for the EnKF code in the "EnKF User's Guide".  @hu5970 Do you know if there will be any more updates to the EnKF User's Guide?  If so, then I would be happy to provide documentation of the new parameters for FED.

**Comment by TingLei-NOAA** [comment]
> @TingLei-NOAA The tests of the EnKF assimilation of FED data into a prototype RRFS used netcdf diag files. I think the new functionality should also work for binary diag files, but I can't confirm with tests.

@daviddowellNOAA Thanks for this clarification.

**Review by TingLei-NOAA — APPROVED** [review]

**Comment by hu5970** [comment]
The regression tests on Dogwood passed:

```
[ming.hu@dlogin07 build] ctest -j7
Test project /lfs/h2/emc/ptmp/Ming.Hu/gsi/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  482.93 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  485.25 sec
3/7 Test #7: global_enkf ......................   Passed  609.82 sec
4/7 Test #2: rtma .............................   Passed  968.70 sec
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  1213.92 sec
6/7 Test #6: hafs_3denvar_hybens ..............   Passed  1214.60 sec
7/7 Test #1: global_4denvar ...................   Passed  1322.47 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1322.48 sec

```

**Comment by hu5970** [comment]
The regression tests on Hera passed:
```
[Ming.Hu@hfe11 build]$ ctest -j7
Test project /scratch1/BMC/wrfruc/mhu/code/gsi/GSI/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  545.01 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  549.37 sec
3/7 Test #7: global_enkf ......................   Passed  1015.83 sec
4/7 Test #2: rtma .............................   Passed  1032.56 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1158.88 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1399.15 sec
7/7 Test #1: global_4denvar ...................   Passed  1606.77 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1606.77 sec

```

**Comment by hu5970** [comment]
The regression tests on Orion:

```
    Start 1: [=[global_4denvar]=]
    Start 2: [=[rtma]=]
    Start 3: [=[rrfs_3denvar_glbens]=]
    Start 4: [=[netcdf_fv3_regional]=]
    Start 5: [=[hafs_4denvar_glbens]=]
    Start 6: [=[hafs_3denvar_hybens]=]
    Start 7: [=[global_enkf]=]
1/7 Test #4: [=[netcdf_fv3_regional]=] ........   Passed  483.86 sec
2/7 Test #7: [=[global_enkf]=] ................   Passed  489.57 sec
3/7 Test #3: [=[rrfs_3denvar_glbens]=] ........   Passed  666.79 sec
4/7 Test #2: [=[rtma]=] .......................***Failed  1029.76 sec
5/7 Test #6: [=[hafs_3denvar_hybens]=] ........   Passed  1457.90 sec
6/7 Test #1: [=[global_4denvar]=] .............   Passed  1681.83 sec
7/7 Test #5: [=[hafs_4denvar_glbens]=] ........   Passed  1696.17 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) = 1696.18 sec

The following tests FAILED:
	  2 - [=[rtma]=] (Failed)
Errors while running CTest

```
The reason for rtma failure is:

```
The runtime for rtma_hiproc_updat is 227.950292 seconds.  This has exceeded maximum allowable threshold time of 226.470057 seconds,
resulting in Failure of timethresh2 the regression test.
```

So, the regression tests on Orion passed too.

**Review by hu5970 — APPROVED** [review]

**Pull request merged**
