### PR TITLE
GitHub Issue NOAA-EMC/GSI#371. Minor bug fixes to IR processing

### LINKED ISSUE #371: Minor Bug Fixes to IR Processing
@wx20jjung has identified three minor bug fixes in IR processing:

1) Numerical errors in the calculation of the surface emissivity check
2) The constant term was erroneously zeroed out when air-mass bias correction terms are zeroed.
3) Some tweaks to the selection of clear scenes during thinning including robustness against missing AVHRR data for IASI

### PR DESCRIPTION
**Pull request by ADCollard**
@wx20jjung has identified three minor bug fixes in IR processing:

Numerical errors in the calculation of the surface emissivity check

The constant term was erroneously zeroed out when air-mass bias correction terms are zeroed.

Some tweaks to the selection of clear scenes during thinning including robustness against missing AVHRR data for IASI

### CODE REVIEW

**Comment by MichaelLueken** [comment]
Hi @ADCollard.  Please let me know who you would like to have review this work.

**Comment by ADCollard** [comment]
> Hi @ADCollard. Please let me know who you would like to have review this work.

@emilyhcliu and @HaixiaLiu-NOAA , please.

**Comment by MichaelLueken** [comment]
Thanks, @ADCollard!  I have assigned @emilyhcliu and @HaixiaLiu-NOAA as reviewers.  To reduce the number of commits from 2 to 1, please use the following in IRBugFix:

1) git reset --hard HEAD~1
2) git remote add upstream https://github.com/NOAA-EMC/GSI.git
3) git remote update
4) git rebase upstream/develop
5) git submodule update
6) git push origin IRBugFix --force

If you have any questions, please let me know.

**Comment by emilyhcliu** [comment]
@ADCollard Could you add some information about this PR in the description?

**Comment by ADCollard** [comment]
> 
I added the top level description from the associated issue.

**Review by emilyhcliu — APPROVED** [review]

**Comment by emilyhcliu** [comment]
@ADCollard Did you accidentally close this PR?  It is not merged yet.

**Comment by MichaelLueken** [comment]
Reopening pull request to see what happens.

**Comment by MichaelLueken** [comment]
@ADCollard I have completed my review of the changes in this PR and everything looks good.  I have tested that the changes compile using the GNU compiler on Hera and submitted tests to ensure that the executables produced run without issue.  The code was compiled using the Intel compiler on WCOSS-D, in debug (no issues encountered), and the debug tests were submitted.  All debug tests successfully ran through to completion.  Running the standard regression tests, the global (and a few regional) tests failed to reproduce the current develop.  Looking at the changes, I wouldn't expect configurations that use IR data to reproduce the current authoritative develop branch.  If this is expected, then I can move forward and submit this work to the DA review committee.

**Comment by ADCollard** [comment]
Thanks, @MichaelLueken-NOAA !  Yes, small changes in results are expected.

**Review by HaixiaLiu-NOAA — APPROVED** [review]

**Comment by MichaelLueken** [comment]
The due date for feedback from the review committee has passed, so I will now give final approval to these changes and merge them to authoritative develop branch.

**Pull request merged**
