### PR TITLE
GitHub Issue NOAA-EMC/GSI#368.  WCOSS2 port.

### LINKED ISSUE #368: WCOSS2 port
The GFS v16.3 package will be the first implementation on WCOSS2.  In order to facilitate the running of real time parallels, which will be required shortly, the current changes in [feature/gfsda.v16.1.5_wcoss2_port](https://github.com/NOAA-EMC/GSI/tree/feature/gfsda.v16.1.5_wcoss2_port) will be merged into the [develop](https://github.com/NOAA-EMC/GSI/tree/develop) branch, along with the rest of the GFS v16.3 updates.

This work will be done in the [feature/wcoss2_port](https://github.com/MichaelLueken-NOAA/GSI/tree/feature/wcoss2_port) branch.

For more details, please see issues #246 and #298.

### PR DESCRIPTION
**Pull request by MichaelLueken**
The GFS v16.3 package will be the first implementation on WCOSS2. In order to facilitate the running of real time parallels, which will be required shortly, the current changes in [feature/gfsda.v16.1.5_wcoss2_port](https://github.com/NOAA-EMC/GSI/tree/feature/gfsda.v16.1.5_wcoss2_port) will be merged into the [develop](https://github.com/NOAA-EMC/GSI/tree/develop) branch, along with the rest of the GFS v16.3 updates.

For specific details on changes associated with this work, please see issues #246 and #298.

Closes #368

### CODE REVIEW

**Review by EdwardSafford-NOAA — APPROVED** [review]
Looks good to me.

**Review by RussTreadon-NOAA — COMMENTED** [review]
One question:   Do we want this PR to change the hash for submodule fix?   develop/fix is at 38c00f0.   This PR changes fix to point at 6f41493.   The following files differ between these two  hashes

```
fix/global_convinfo.txt
fix/gfsv16_historical/0readme
```

Other changes looks good.

**Comment by MichaelLueken** [comment]
@EdwardSafford-NOAA @RussTreadon-NOAA Thanks for the review!  The changes to fix are to bring in the fix file changes from the gfsda.v16.1.6 implementation.  So, the update to fix is required to finally bring in these changes to develop.

**Review by RussTreadon-NOAA — APPROVED** [review]
Thank you @MichaelLueken-NOAA for confirming that change in the fix hash is intentional.

**Comment by MichaelLueken** [comment]
The due date for the review committee has passed with no feedback, so final approval will be given to these changes and they will be merged to the authoritative repository.

**Pull request merged**
