### PR TITLE
GitHub Issue NOAA-EMC/GSI#425.  Cleanout stale, unused files from ush/

### LINKED ISSUE #425: clean `ush/`
[ush](https://github.com/NOAA-EMC/GSI/tree/develop/ush) contains

```
build_4nco_global.sh      detect_machine.sh                  rungsi62_prod.sh
build.sh                  getgfsnctime                       rungsi_globalprod.sh
calcanl_gfs.py            Get_Initial_Files                  rungsi_nems_nmmb.sh
calcinc_gfs.py            getncdimlen                        rungsi_nmm_binary.sh
comenkf_namelist_gfs.sh   gfs_truncate_enkf.sh               rungsi_nmmprod.sh
comenkf_namelist.sh       gsi_utils.py                       sub_discover
comenkf_run_gfs.ksh       link_crtm_coeffs.sh                sub_hera
comenkf_run_regional.ksh  llsub_gsi_cmaq.sh                  sub_jet
comgsi_namelist_chem.sh   module-setup.sh                    sub_ncar
comgsi_namelist_gfs.sh    para_config.gdas_analysis_high     sub_wcoss
comgsi_namelist.sh        para_config.gfs_analysis           sub_wcoss_c
comgsi_run_chem.ksh       prune_4nco_global.sh               sub_wcoss_d
comgsi_run_gfs.ksh        refactor_4nco_global.sh            test_gdas_analysis_high.sh
comgsi_run_regional.ksh   run_arw_netcdf_hybens_testcase.sh  test_gfs_analysis.sh
```

Amongst them, the following have not been touched for 4 years:
```
comenkf_*
comgsi_*
rungsi_*
test_gfs_analysis.sh
test_gdas_analysis_high.sh
para_config.gfs_analysis
para_config.gdas_analysis_high
gfs_truncate_enkf.sh
Get_Initial_Files
run_arw_netcdf_hybens_testcase.sh
``

Then there are files such as these that are stale (2 years old at least):
```
refactor_4nco_global.sh
llsub_gsi_cmaq.sh
link_crtm_coeffs.sh
```

These are  used; e.g.
```
sub_*
getncdimlen
getgfsnctime
gsi_utils.py
calcanl_gfs.py
calcinc_gfs.py
```

Not all `sub_` are used.

The build related scripts are used.

### PR DESCRIPTION
**Pull request by aerorahul**
closes #425

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Changes look good.  Removed `ush` files are not frequently used.  Developers may recover removed `ush` files via checkout of the appropriate hash.   Once PR #427 is merged into `develop`, the `util` sections of `ush/prune_4nco_global.sh` may be removed via a new PR.

**Comment by MichaelLueken** [comment]
@aerorahul Please reduce the number of commit messages from 2 to 1 and please ensure that the issue associated with this work is included in the single commit message with the following:

git reset --soft HEAD~1
git commit --amend
Please add `GitHub Issue NOAA-EMC/GSI#425` to your commit message.

Once these changes have been made, I can merge this work to the authoritative develop branch after the current work out to the review committee has been merged.

**Comment by aerorahul** [comment]
> @aerorahul Please reduce the number of commit messages from 2 to 1 and please ensure that the issue associated with this work is included in the single commit message with the following:
> 
> git reset --soft HEAD~1 git commit --amend Please add `GitHub Issue NOAA-EMC/GSI#425` to your commit message.
> 
> Once these changes have been made, I can merge this work to the authoritative develop branch after the current work out to the review committee has been merged.

done.

**Comment by MichaelLueken** [comment]
Since there are no changes to the source code and @RussTreadon-NOAA has approved the changes, I will now give final approval and merge this work to the authoritative develop branch.

**Pull request merged**
