### PR TITLE
Release/gfsda.v16

### PR DESCRIPTION
**Pull request by ADCollard**
This PR turns off NOAA-21 radiance ingest into GSI temporarily to allow the satingest of NOAA-21 to proceed.

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
atms and cris-fsr n21 are removed from the `OBS_INPUT` namelist thereby removing these two sensor_satellite combinations from `gsi.x` processing.

Approve.

**Comment by RussTreadon-NOAA** [comment]
Given that this was a straightforward and high priority PR, I reviewed, approved, and merged so @ADCollard's work can move forward.

Sorry, @HaixiaLiu-NOAA and @emilyhcliu for not waiting for your reviews.

**Comment by RussTreadon-NOAA** [comment]
@ADCollard , what tag name do you want for [`release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) at [`ef169a5`](https://github.com/NOAA-EMC/GSI/commit/ef169a5ed66c813ff0d00736f47b0d1950b67461)?

Our most recent GFS tag is [`gfsda.v16.3.7`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.7).   Will the new tag be _gfsda.v16.3.8_ ?

**Comment by ADCollard** [comment]
Correct.   *gfsda.v16.3.8*

Thanks, Russ!

ADC

**Comment by RussTreadon-NOAA** [comment]
[`gfsda.v16.3.8`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.8) created as copy of [`release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16) at [`ef169a5`](https://github.com/NOAA-EMC/GSI/commit/ef169a5ed66c813ff0d00736f47b0d1950b67461).

**Pull request merged**
