### PR TITLE
Release/gfsda.v16.0.0 restructure

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
Add new $COMPONENT subdirectory to scripts to support GFSv16 restructuring. New subdirectory called "atmos" for atmospheric component.

Documented in global-workflow issue: https://github.com/NOAA-EMC/global-workflow/issues/94

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA I was able to reproduce v16rt2 in my initial test but will run a fresh one with my forks and new warm starts today to reconfirm. I synced my GSI fork today with the main release/gfsda.v16.0.0 branch before submitting the PR. Will update this issue with results.

@EdwardSafford-NOAA Please review the changes in this PR for the monitoring scripts. Let me know if you have any questions. Thanks!

**Comment by RussTreadon-NOAA** [comment]
I believe that for v16 COMPONENT = "atmos" or "wave".   See global-workflow
issue #94 <https://github.com/NOAA-EMC/global-workflow/issues/94> for
details.

**Comment by KateFriedman-NOAA** [comment]
What Russ stated is correct. The values of COMPONENT for v16 will be either "atmos" or "wave". Future versions of the system (e.g. v17+) will begin to incorporate additional components (e.g. "ocean", "ice", etc.).

**Comment by KateFriedman-NOAA** [comment]
Sync merged NOAA-EMC/GSI release/gfsda.v16.0.0 into [KateFriedman-NOAA/GSI release/gfsda.v16.0.0-restructure](https://github.com/KateFriedman-NOAA/GSI/tree/release/gfsda.v16.0.0-restructure) at 263c10a.

**Comment by KateFriedman-NOAA** [comment]
Committed small text fix to JGDAS_VMINMON to resolve duplicate atmos in path. Committed at aff4da8.

Sync merged NOAA-EMC/GSI release/gfsda.v16.0.0 into [KateFriedman-NOAA/GSI release/gfsda.v16.0.0-restructure](https://github.com/KateFriedman-NOAA/GSI/tree/release/gfsda.v16.0.0-restructure) at b53db5d.

@EdwardSafford-NOAA Please see the following on Mars to confirm the monitoring jobs ran correctly, thanks!

log (starting lines 1347, 15388, 16636): /gpfs/dell3/ptmp/Kate.Friedman/comrot/v16atmos2/logs/2020072100/gdasvrfy.log
log (starting line 81359): /gpfs/dell3/ptmp/Kate.Friedman/comrot/v16atmos2/logs/2020072100/gfsvrfy.log
output: /gpfs/dell2/emc/modeling/noscrub/Kate.Friedman/monitor/*/*/v16atmos2

**Comment by EdwardSafford-NOAA** [comment]
Looks OK to me.

**Comment by KateFriedman-NOAA** [comment]
Great, thanks for checking and confirming @EdwardSafford-NOAA !

**Comment by KateFriedman-NOAA** [comment]
> Assuming the parallel testing these changes on Mars reproduced the control these changes may be approved.

Russ, yes, using inputs from the v16rt2 parallel I was able to run a full cycle and reproduce it with global-workflow feature/gfsv16b-restructure and the modified GSI release/gfsda.v16.0.0 fork of mine. Thanks for your help ironing out the differences caused due to resource settings!

**Comment by RussTreadon-NOAA** [comment]
Venus v16rt2atmos2 test indicates DA updates are working.   Will go ahead and merge PR #39 into release/gfsda.v16.0.0.

**Pull request merged**
