### PR TITLE
reorder correlated error setup checks

### LINKED ISSUE #735: gsi.x failure with correlated error
global-workflow issue [#2507](https://github.com/NOAA-EMC/global-workflow/issues/2507) reports a `gsi.x` failure when running 2021032418.  This issue is opened to document this failure and develop a fix.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
g-w issue [#2507](https://github.com/NOAA-EMC/global-workflow/issues/2507) flagged a `gsi.x` failure related to correlated error in a historical case.  Rearranging the correlated error setup checks allows `gsi.x` to successfully run the historical case.

Fixes #735

**Type of change**
- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
Two tests have been conducted
1. Run failed 2021032418 case using updated `gsi.x`.  GSI run to completion
2. Run ctests on Hera.  All tests pass.
```
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/develop_test/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  1209.16 sec
2/7 Test #3: rrfs_3denvar_glbens ..............Passed  1214.33 sec
3/7 Test #7: global_enkf ......................   Passed  1416.07 sec
4/7 Test #2: rtma .............................   Passed  1811.61 sec
5/7 Test #5: hafs_4denvar_glbens ..............   Passed  1887.12 sec
6/7 Test #6: hafs_3denvar_hybens ..............   Passed  1887.89 sec
7/7 Test #1: global_4denvar ...................   Passed  2468.95 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 2468.98 sec
```
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
@CatherineThomas-NOAA and @ADCollard - this PR contains the changes to `src/gsi/correlated_obsmod.F90` described in g-w issue [#2507](https://github.com/NOAA-EMC/global-workflow/issues/2507).

I don't know the inner workings of correlated error.  While the modified `src/gsi/correlated_obsmod.F90` allows the failed case to pass, your review of the change would be greatly appreciated.

**Review by ADCollard — APPROVED** [review]
@RussTreadon-NOAA Thank you so much for fixing this.   There is no reason for the code to exit in this case.

**Review by CatherineThomas-NOAA — APPROVED** [review]
Thanks for working out a fix to this, @RussTreadon-NOAA!

**Comment by RussTreadon-NOAA** [comment]
**Orion ctests**
```
Test project /work2/noaa/da/rtreadon/git/gsi/pr736/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  544.36 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  671.46 sec
3/7 Test #7: global_enkf ......................   Passed  798.60 sec
4/7 Test #2: rtma .............................   Passed  968.64 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1167.65 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1341.63 sec
7/7 Test #1: global_4denvar ...................   Passed  1745.74 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1745.75 sec
```

**Hercules ctests**
```
Test project /work/noaa/da/rtreadon/git/gsi/pr736/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  484.66 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  551.02 sec
3/7 Test #7: global_enkf ......................   Passed  726.58 sec
4/7 Test #2: rtma .............................   Passed  965.16 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1092.17 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1226.01 sec
7/7 Test #1: global_4denvar ...................   Passed  1741.68 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1741.89 sec
```

As expected, reordering the correlated error setup checks does not alter analysis results, wall time, or memory usage.

**Comment by RussTreadon-NOAA** [comment]
**WCOSS2 (Dogwood) ctests**
```
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr736/build
    Start 1: global_4denvar
    Start 2: rtma
    Start 3: rrfs_3denvar_glbens
    Start 4: netcdf_fv3_regional
    Start 5: hafs_4denvar_glbens
    Start 6: hafs_3denvar_hybens
    Start 7: global_enkf
1/7 Test #4: netcdf_fv3_regional ..............   Passed  483.67 sec
2/7 Test #3: rrfs_3denvar_glbens ..............   Passed  486.31 sec
3/7 Test #7: global_enkf ......................   Passed  851.93 sec
4/7 Test #2: rtma .............................   Passed  969.51 sec
5/7 Test #6: hafs_3denvar_hybens ..............   Passed  1153.08 sec
6/7 Test #5: hafs_4denvar_glbens ..............   Passed  1213.29 sec
7/7 Test #1: global_4denvar ...................   Passed  1682.47 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 1682.48 sec
```

**Pull request merged**
