### PR TITLE
GitHub Issue 674: compiling EFSOI under GSI

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
This PR adds the EFSOI fortran files under the src and allows for compiling on Orion. cmake additions are enough to get it to compile there with defaults, otherwise probably naive.

Files modified:
CMakeLists.txt
src/CMakeLists.txt

Files added:
src/efsoi/CMakeLists.txt
src/efsoi/cmake/FindNetCDF.cmake
src/efsoi/efsoi.f90
src/efsoi/efsoi_main.f90
src/efsoi/gridio_efsoi.f90
src/efsoi/loadbal_efsoi.f90
src/efsoi/loc_advection.f90
src/efsoi/scatter_chunks_efsoi.f90
src/efsoi/statevec_efsoi.f90

### CODE REVIEW

**Comment by aerorahul** [comment]
@AndrewEichmann-NOAA 
`efsoi` as it stands is an application rather than a core capability.
This repository is for generic core capabilities of the GSI and EnKF.
This is already a part of the GSI-utils https://github.com/NOAA-EMC/GSI-utils/tree/develop/src/EFSOI_Utilities/src

**Review by aerorahul — CHANGES_REQUESTED** [review]
This application does not belong in the core capability of the GSI/EnKF.
We are in the process of re-organizing this repository by following separation of concerns.
If you think that an EFSOI repository is needed for the application, we can certainly make that happen.
These codes are already a part of https://github.com/NOAA-EMC/GSI-utils/tree/develop/src/EFSOI_Utilities/src, which allows one to build just the EFSOI utilities, if  one desires.

**Comment by AndrewEichmann-NOAA** [comment]
@aerorahul EFSOI links a number of modules from the enkf code in order to address concerns about code duplication. At this point keeping the EFSOI code in a separate repository would either copying the necessary files from the enkf code, or arranging to link them from that separate repository. Is there a facility to do the latter?

**Comment by aerorahul** [comment]
There is no need to duplicate code.
You can link to the `enkf` library built in the GSI repository.

**Comment by AndrewEichmann-NOAA** [comment]
@aerorahul Is there an example of linking enkf from GSI-utils I could see? I've been trying to set enkf_ROOT as indicated in the GSI-utils INSTALL.md and haven't had any luck getting it recognized during the build.

**Comment by aerorahul** [comment]
> @aerorahul Is there an example of linking enkf from GSI-utils I could see? I've been trying to set enkf_ROOT as indicated in the GSI-utils INSTALL.md and haven't had any luck getting it recognized during the build.

Build and install the GSI+EnKF following the instructions [here](https://github.com/NOAA-EMC/GSI/blob/develop/INSTALL.md).

Then build the GSI-utils following the instructions [here](https://github.com/NOAA-EMC/GSI-utils/blob/develop/INSTALL.md)
For the `CMAKE_OPTIONS` during building the GSI-utils, include the path to GSI+EnKF installation prefix from the previous step as: `-Dgsi_ROOT=GSI_INSTALL_PREFIX -Denkf_ROOT=GSI_INSTALL_PREFIX`.

If you want to skip the `cmake` options and use the canned build scripts in the repositories, the instructions are:

```
$1> git clone https://github.com/noaa-emc/gsi
$2> git clone https://github.com/noaa-emc/gsi-utils

$3> BUILD_DIR=$PWD/build_gsi_enkf INSTALL_PREFIX=$PWD/install_gsi_enkf ./gsi/ush/build.sh
$4> BUILD_DIR=$PWD/build_gsi_utils INSTALL_PREFIX=$PWD/install_gsi_utils  CMAKE_OPTS="-Dgsi_ROOT=$PWD/install_gsi_enkf -Denkf_ROOT=$PWD/install_gsi_enkf" ./gsi-utils/ush/build.sh
```

I noticed that the CRTM module is not loaded in the gsi-utils, so I had to pass the path to CRTM as well in the argument for `CMAKE_OPTS` for `$4>`.  The following is an example for Orion.
`-Dcrtm_ROOT=/apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/crtm/2.3.0`

On Orion, `$4>` is:
```
$4> BUILD_DIR=$PWD/build_gsi_utils INSTALL_PREFIX=$PWD/install_gsi_utils CMAKE_OPTS="-Dgsi_ROOT=$PWD/install_gsi_enkf -Denkf_ROOT=$PWD/install_gsi_enkf -Dcrtm_ROOT=/apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/crtm/2.3.0" ./gsi-utils/ush/build.sh
```

The EFSOI utility `efsoi.x` is installed under `$PWD/install_gsi_utils`

A PR in the GSI-utils repository to load the CRTM modulefile is opened [here](https://github.com/NOAA-EMC/GSI-utils/pull/5).

**Comment by AndrewEichmann-NOAA** [comment]
Thanks @aerorahul I think I have this working reliably, though I'm not sure what I was doing wrong. 
Where do you think would be a good place for a user to intervene to build EFSOI within global-workflow? I'm thinking in terms of something appropriate for manual instructions that could be included in the standard repositories. Perhaps a commented line in gsi-utils build.sh that gets uncommented to build it?

**Comment by aerorahul** [comment]
> Thanks @aerorahul I think I have this working reliably, though I'm not sure what I was doing wrong. Where do you think would be a good place for a user to intervene to build EFSOI within global-workflow? I'm thinking in terms of something appropriate for manual instructions that could be included in the standard repositories. Perhaps a commented line in gsi-utils build.sh that gets uncommented to build it?

```
diff --git i/sorc/build_gsi_utils.sh w/sorc/build_gsi_utils.sh
index bc579300..0e16e925 100755
--- i/sorc/build_gsi_utils.sh
+++ w/sorc/build_gsi_utils.sh
@@ -21,9 +21,17 @@ while getopts ":dov" option; do
 done
 shift $((OPTIND-1))

+UTIL_OPTS="-DBUILD_UTIL_ENKF_GFS=ON -DBUILD_UTIL_NCIO=ON"
+GSIENKF_INSTALL_PREFIX="${cwd}/gsi_enkf.fd/install"
+if [[ -d "${GSI_INSTALL_PREFIX}" ]]; then
+  CMAKE_OPTS="-Dgsi_ROOT=${GSIENKF_INSTALL_PREFIX} -Denkf_ROOT=${GSIENKF_INSTALL_PREFIX}"
+  UTIL_OPTS+=" -DBUILD_UTIL_EFSOI=ON"
+fi
+
 BUILD_TYPE=${BUILD_TYPE:-"Release"} \
 BUILD_VERBOSE=${BUILD_VERBOSE:-"NO"} \
-UTIL_OPTS="-DBUILD_UTIL_ENKF_GFS=ON -DBUILD_UTIL_NCIO=ON" \
+CMAKE_OPTS="${CMAKE_OPTS:-}" \
+UTIL_OPTS="${UTIL_OPTS:-}" \
 ${cwd}/gsi_utils.fd/ush/build.sh

 exit
```

**Comment by AndrewEichmann-NOAA** [comment]
@aerorahul  The diff below corrects the differing GSI_INSTALL_PREFIX vs GSIENKF_INSTALL_PREFIX and builds with a fork of the latest global-workflow e2869a1247ad2ba72c1bfe82f7682323d5128f4c and the gsi-utils with the CRTM fix 14890afd1e13114e102e1d654b0d35efd8a5c93b

```
diff --git a/sorc/build_gsi_utils.sh b/sorc/build_gsi_utils.sh
index bc57930..f8e8104 100755
--- a/sorc/build_gsi_utils.sh
+++ b/sorc/build_gsi_utils.sh
@@ -21,9 +21,17 @@ while getopts ":dov" option; do
 done
 shift $((OPTIND-1))
 
+UTIL_OPTS="-DBUILD_UTIL_ENKF_GFS=ON -DBUILD_UTIL_NCIO=ON"
+GSIENKF_INSTALL_PREFIX="${cwd}/gsi_enkf.fd/install"
+if [[ -d "${GSIENKF_INSTALL_PREFIX}" ]]; then
+  CMAKE_OPTS="-Dgsi_ROOT=${GSIENKF_INSTALL_PREFIX} -Denkf_ROOT=${GSIENKF_INSTALL_PREFIX}"
+  UTIL_OPTS+=" -DBUILD_UTIL_EFSOI=ON"
+fi
+
 BUILD_TYPE=${BUILD_TYPE:-"Release"} \
 BUILD_VERBOSE=${BUILD_VERBOSE:-"NO"} \
-UTIL_OPTS="-DBUILD_UTIL_ENKF_GFS=ON -DBUILD_UTIL_NCIO=ON" \
+CMAKE_OPTS="${CMAKE_OPTS:-}" \
+UTIL_OPTS="${UTIL_OPTS:-}" \
 ${cwd}/gsi_utils.fd/ush/build.sh
 
 exit
```

**Pull request closed without merging**
