### PR TITLE
GitHub Issue NOAA-EMC/GSI#431.  Replace ncdiag submodule with hpc-stack ncidag/1.0.0

### LINKED ISSUE #431: Replace ncdiag submodule with hpc-stack library
The `ncdiag` library is available on Hera, Orion, and the `para` space on WCOSS2.  The submodule will be replaced with the hpc-stack built `ncdiag/1.0.0` library.

### PR DESCRIPTION
**Pull request by MichaelLueken**
The `ncdiag` library is available on Hera, Orion, and the `para` space on WCOSS2. The submodule will be replaced with the hpc-stack built `ncdiag/1.0.0` library.

Closes #431.

### CODE REVIEW

**Review by aerorahul — CHANGES_REQUESTED** [review]
I am afraid there are more changes required:

1. Update `INSTALL.md` to accurately reflect the removal of `BUILD_NCDIAG`.  Update dependencies.
2. `src/CMakeLists.txt`: Remove the option related to `BUILD_NCDIAG`.
3. `src/gsi/CMakeLists.txt`:  The blocks around `if(NOT TARGET ncdiag)`.  The dependency of `gsi_fortran_obj` on `ncdiag` when `if(TARGET ncdiag)`.
4. `src/gsi/cmake/PackageConfig.cmake.in`: Add dependency on `ncdiag`

I also found a stray `-` in https://github.com/MichaelLueken-NOAA/GSI/blob/756afcba6d6730bde0134b6cab50d418205825f3/src/enkf/cmake/PackageConfig.cmake.in#L14

**Comment by MichaelLueken** [comment]
Thank you for your very thorough review, @aerorahul!

`INSTALL.md` -
```
+| NCDIAG          | 1.0.0 and above                                            |
-| `BUILD_NCDIAG`        | Build GSI NetCDF Diagnostics Library (`ON`)          |
```
`src/CMakeLists.txt` - The BUILD_NCDIAG option has already been removed (this is required, otherwise the code wouldn't build).
`src/gsi/CMakeLists.txt` - 
`+find_package(ncdiag REQUIRED)`
```
-# NetCDF Diagnostic IO library dependency
-if(NOT TARGET ncdiag)
-  find_package(ncdiag REQUIRED)
-endif()
```
```
-if(TARGET ncdiag)
-  add_dependencies(gsi_fortran_obj ncdiag)
-endif()
```
`src/gsi/cmake/PackageConfig.cmake.in` - 
`+find_dependency(ncdiag REQUIRED)`
```
-# This gives more trouble since GSIApp is a nested project of projects
-# and targets are built in the GSIApp project
-#find_dependency(ncdiag REQUIRED)
-
```
`src/enkf/cmake/PackageConfig.cmake.in` -
This stray `-` is present in the authoritative repository.  I have removed it in this PR.

**Review by aerorahul — CHANGES_REQUESTED** [review]
These changes are good.
There is one more change required in:
https://github.com/MichaelLueken-NOAA/GSI/blob/feature/remove_ncdiag/src/CMakeLists.txt
Lines 6-9 don't belong here anymore.

**Comment by MichaelLueken** [comment]
> These changes are good. There is one more change required in: https://github.com/MichaelLueken-NOAA/GSI/blob/feature/remove_ncdiag/src/CMakeLists.txt Lines 6-9 don't belong here anymore.

Thanks again, @aerorahul for the review.  The `BUILD_NCDIAG` lines in `src/CMakeLists.txt` have been removed.

**Review by aerorahul — APPROVED** [review]
Looks good.

**Comment by MichaelLueken** [comment]
Since there are no changes to the source code and @aerorahul has approved the changes, I will now give final approval and merge this work to the authoritative develop branch.

**Pull request merged**
