### PR TITLE
deallocate ges_th2 and ges_q2

### PR DESCRIPTION
**Pull request by ShunLiu-NOAA**
deallocate ges_th2 and ges_q2 in setupt.f90

### CODE REVIEW

**Comment by MichaelLueken-NOAA** [comment]
Hi Shun,

Why did you create the PR from your allocate_ges branch rather than the master (I saw that you squash merged the update in allocate_ges into your fork's master with the correct commit message).  Who do you want to have review the update?

Thanks,

Mike

**Comment by ShunLiu-NOAA** [comment]
PR is should be created from master. I will close this one and create one
from master.
Thanks.

Shun

**Comment by ShunLiu-NOAA** [comment]
closed. Should create PR from master

**Comment by ShunLiu-NOAA** [comment]
Mike,

This is a small bug fix. Should I create a PR once a bug is found or create
PR later after combing several bug fixes together?

Shun

**Comment by MichaelLueken-NOAA** [comment]
Hi Shun,

Since we want to get bug fixes into the master as quickly as possible (bug fixes have priority and have a much shorter review period with the review committee), I'd recommend creating PRs as soon as a bug has been identified and corrected.

Mike

**Pull request closed without merging**
