### PR TITLE
remove old regional regression test cases and add new one for RRFS

### PR DESCRIPTION
**Pull request by hu5970**
This PR is addressing the Issue:
"update on current GSI regression tests #513"

Here is what has been done:
1) Remove regression tests: arw_binary,arw_netcdf,nmm_binary,nmm_netcdf,nmmb_nems_4denvar
2) Add regression case for RRFS: rrfs_3denvar_glbens
3) Reduce the number of ensembles used for hybrid analysis for saving space and time.

The following new fix files are added:
/lfs/h2/emc/lam/noscrub/Ming.Hu/code/gsi/GSI/fix/
-rw-r--r-- 1 ming.hu lam      2468 Jan  4 06:45 anavinfo.rrfs
-rw-r--r-- 1 ming.hu lam     27424 Jan  4 06:46 convinfo.rrfs
-rw-r--r-- 1 ming.hu lam      2540 Jan  4 06:46 hybens_info.rrfs
-rwxr-xr-x 1 ming.hu lam    492800 Jan  4 06:46 errtable.rrfs
-rw-r--r-- 1 ming.hu lam  67363540 Jan  4 06:47 rrfs_glb_berror.l127y770.f77

There are 9 regression test cases after this PR. The tests were tested on three platforms:
1) Hera: all 9 cases passed
2) WCOSS2: 8 case passed, rtma case failed
3) Orion: 9 cases passed.

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
First check of changes looks OK.   Will build branch on various platforms and run ctests.   
Suggest adding additional reviewers from review team and/or regional DA staff.

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , the first job for ctest `rrfs_3denvar_glbens` is `rrfs_3denvar_glbens_loproc_updat`.   This job immediately fails on Hera, Orion, and WCOSS2 (cactus) with the following message in `stdout`
```
 beta_s0 needs to be set to zero in this GSI version, when reflectivity is direc
 tly assimilated. Static B extended for radar reflectivity assimilation will be
 included in future version.
 beta_s0 needs to be set to zero in this GSI version, when reflectivity is direc
 tly assimilated. Static B extended for radar reflectivity assimilation will be
 included in future version.
MPICH ERROR [Rank 13] [job id 0dcdad03-20eb-4a66-a7fd-2f420ef421b6] [Fri Jan  6 11:40:38 2023] [nid003135] - Abort(8888) (rank 13 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 8888) - process 13

aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 8888) - process 13
```
This error message is written from `gsimod.F90`
```
! If reflectivity is intended to be assimilated, beta_s0 should be zero.                                                                         
  if ( beta_s0 > 0.0_r_kind )then
    ! skipped in case of direct reflectivity DA because it works in Envar and hybrid                                                             
    if ( .not.l_use_rw_columntilt .or. .not.l_use_dbz_directDA) then
       do i=1,ndat
          if ( index(dtype(i), 'dbz') /= 0 )then
             write(6,*)'beta_s0 needs to be set to zero in this GSI version, when reflectivity is directly assimilated. &                        
                        Static B extended for radar reflectivity assimilation will be included in future version.'
             call stop2(8888)
          end if
       end do
    end if
  end if
```
A check of `gsiparm.anl` in the run directory shows `beta_s0=0.15`.  Neither `l_use_rw_columntilt` nor `l_use_dbz_directDA` are set in `gsiparm.anl.`.   Thus, these variable have a default value of `.FALSE.` as assigned in `directDA_radaruse_mod.F90`.   Hence the failure.

What's the correct resolution of this problem?

**Comment by RussTreadon-NOAA** [comment]
The first rtma ctest job `rtma_loproc_updat` fails on WCOSS2 (cactus) with a segmentation fault and traceback shown below
```
 ### 2d auto correlation model - subdomain mode ###
GLBSOI: jiter,jiterstart,jiterlast,jiterend=    1    1    2    1
 GENSTATS_GPS:  no profiles to process (nprof_gfs=           0 ), EXIT routine
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
gsi.x              0000000001F8188A  Unknown               Unknown  Unknown
libpthread-2.31.s  000015220E80F8C0  Unknown               Unknown  Unknown
gsi.x              000000000059AF80  gsi_bundlemod_mp_        2355  gsi_bundlemod.F90
gsi.x              0000000000DEAFE2  control2state_ad_         398  control2state_ad.f90
libiomp5.so        00001522106063F3  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        000015221058A937  __kmp_fork_call       Unknown  Unknown
libiomp5.so        000015221054E533  __kmpc_fork_call      Unknown  Unknown
gsi.x              0000000000DE1D41  control2state_ad_         220  control2state_ad.f90
gsi.x              0000000001235486  pcgsoimodpcgsoi_m        1009  pcgsoi.f90
gsi.x              000000000123161F  pcgsoimod_mp_pcgs         295  pcgsoi.f90
gsi.x              0000000001035FCF  glbsoi_                   371  glbsoi.f90
gsi.x              0000000000612E67  gsisub_                   200  gsisub.F90
gsi.x              00000000004133BD  gsimod_mp_gsimain        2266  gsimod.F90
```
The rtma regression test passes on Hera and Orion.  The WCOSS2 failure is the outlier.   How can this be?

One hypothesis is that the WCOSS2 job configuration is not correct.   Another possibility is that additional environment variables need to be set on WCOSS2 in order for `gsi.x` to successfully run to completion in rtma mode.   @hu5970 , we should reach out to the rtma team to learn how they run gsi.x on WCOSS2.    This problem needs to be resolved before we can move forward with this PR.

**Comment by RussTreadon-NOAA** [comment]
Examination of the traceback revealed that pointer `rv_tcamt` in `control2state_ad.f90` was not nullified upon declaration as is done with other pointers.   Update the code to nullify this pointer,
```
 real(r_kind),pointer,dimension(:,:)   :: rv_gust=>NULL(),rv_vis=>NULL(),rv_pblh=>NULL()
-real(r_kind),pointer,dimension(:,:)   :: rv_wspd10m=>NULL(),rv_tcamt,rv_lcbas=>NULL()
+real(r_kind),pointer,dimension(:,:)   :: rv_wspd10m=>NULL(),rv_tcamt=>NULL(),rv_lcbas=>NULL()
 real(r_kind),pointer,dimension(:,:)   :: rv_td2m=>NULL(),rv_mxtm=>NULL(),rv_mitm=>NULL()
```
The same update was made in a working copy of `develop`.   Both the update (this PR) and control (`develop`) codes were recompiled and the rtma ctest rerun.   With this change to `control2state_ad.f90` the rtma ctest passed on WCOSS2 (cactus).

```
russ.treadon@clogin06:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr516/build> ctest -R rtma
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr516/build
    Start 6: rtma
1/1 Test #6: rtma .............................   Passed  1330.12 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 1330.26 sec
```

**Comment by hu5970** [comment]
@RussTreadon-NOAA Thanks for fixing the rtma crash on wcoss2. I have committed this bug fix to the PR.

As for rrfs 3denvar crash, there is a bug in the line your pointed out. In my test, I changed this line but did not commit the change because I think we should not change the code at this stage. This will be fixed in the following PR from OU. But we already has the code change for rtma, so I also changed this line in this PR to fix rrfs case.

**Comment by RussTreadon-NOAA** [comment]
I failed to notice that four new rrfs fix files are locally added in this PR.   I manually copied
```
        anavinfo.rrfs
        convinfo.rrfs
        errtable.rrfs
        hybens_info.rrfs
```
from `/lfs/h2/emc/lam/noscrub/Ming.Hu/code/gsi/GSI/fix/` into my working copy of `regtest_regional`.   

Job rrfs_3denvar_glbens still failed.  

I checked `/lfs/h2/emc/lam/noscrub/Ming.Hu/code/gsi/GSI`.   I found that `src/gsi/gsimod.F90` has a local modification
```
     ! skipped in case of direct reflectivity DA because it works in Envar and hybrid
-    if ( .not.l_use_rw_columntilt .or. .not.l_use_dbz_directDA) then
+    if ( l_use_rw_columntilt .or. l_use_dbz_directDA) then
        do i=1,ndat
```
I added this local modification to my copies of `regtest_regional` and `develop`, recompiled, and reran ctest `rrfs_3denvar_glbens`.       The update job ran to completion.  I expect the other jobs in this test will also run to completion.

@hu5970, if a PR is not ready to be reviewed it should be opened in draft mode.   There are bugs in this PR.  There are new fix files in the PR.   These should be in place before asking others to review this PR.

**Comment by RussTreadon-NOAA** [comment]
With the change to `src/gsi/gsimod.F90`, the `rrfs_3denvar_glbens` test successfully ran to completion on WCOSS2 (cactus)

```
russ.treadon@clogin06:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr516/build> ctest -R rrfs_3denvar_glbens
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr516/build
    Start 7: rrfs_3denvar_glbens
1/1 Test #7: rrfs_3denvar_glbens ..............   Passed  904.87 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 904.88 sec
```

**Comment by RussTreadon-NOAA** [comment]
Compilation of regtest_regional at a0126852 fails with

```
/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr516/src/gsi/control2state_ad.f90(124): error #5082: Syntax error, found '==' when expecting one of: ( , * <END-OF-STATEMENT> ; [ = / =>
real(r_kind),pointer,dimension(:,:)   :: rv_wspd10m=>NULL(),rv_tcamt==>NULL(),rv_lcbas=>NULL()
```
Replace the double `==` with a single `=`.   Compilation runs to completion after making this local change.

**Comment by hu5970** [comment]
@RussTreadon-NOAA I have fixed the bug I introduced and recompiled the code. It works now.

I don't know how to commit the fix files at this stage. Seems we use local fix directory in each machine now until new fix repository committed. Could you also copy those rrfs fix files to your fix directory:
On Hera: /scratch1/BMC/wrfruc/mhu/code/gsi/test2/GSI/fix
On Orion: /work/noaa/wrfruc/mhu/code/gsi/GSI/fix
The fix files I am using on three machines are linked from your local fix directory on each machin.
Thanks,
Ming

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , if the new rrfs regression test needs new fix files, we need to commit them to gerrit:GSI-FIX/rev2.   If you want the stage the new fix files in the central locations on various machines, please contact @KateFriedman-NOAA (EIB).

**Comment by hu5970** [comment]
@RussTreadon-NOAA I can not access gerrit. Could you commit those new fix files?
I will send Kate a email to ask for add new fix files to the central location.

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , since you are on the GSI review team, please restore your access to gerrit.   We have not yet pivoted to the github based GSI-fix.

**Comment by hu5970** [comment]
@RussTreadon-NOAA I will try to restore my access to gerrit. Thanks, Ming

**Comment by RussTreadon-NOAA** [comment]
**Regression test results**
Build `regtest_regional` at 8db5673 on Hera, Orion, and WCOSS2 (cactus).    Do the same for NOAA-EMC/GSI `develop` at ed7ecc76 with local modifications to 
```
        src/gsi/control2state_ad.f90
        src/gsi/gsimod.F90
```
as discussed in this PR.  Run full suite of nine regression tests on each machine with the following results.

**WCOSS2 (cactus) results**
```
russ.treadon@clogin04:/lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr516/build> ctest -j 9
Test project /lfs/h2/emc/da/noscrub/russ.treadon/git/gsi/pr516/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #8: netcdf_fv3_regional ..............   Passed  722.80 sec
2/9 Test #7: rrfs_3denvar_glbens ..............   Passed  725.57 sec
3/9 Test #9: global_enkf ......................   Passed  781.52 sec
4/9 Test #4: hwrf_nmm_d2 ......................   Passed  1088.14 sec
5/9 Test #5: hwrf_nmm_d3 ......................   Passed  1096.57 sec
6/9 Test #2: global_4dvar .....................   Passed  1141.92 sec
7/9 Test #6: rtma .............................   Passed  1568.72 sec
8/9 Test #3: global_4denvar ...................   Passed  1682.22 sec
9/9 Test #1: global_3dvar .....................   Passed  1862.47 sec

100% tests passed, 0 tests failed out of 9

Total Test time (real) = 1862.48 sec
```

**Hera results**
```
Hera(hfe02):/scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr516/build$ ctest -j 9
Test project /scratch1/NCEPDEV/da/Russ.Treadon/git/gsi/pr516/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #7: rrfs_3denvar_glbens ..............   Passed  548.41 sec
2/9 Test #9: global_enkf ......................   Passed  723.88 sec
3/9 Test #8: netcdf_fv3_regional ..............   Passed  725.44 sec
4/9 Test #4: hwrf_nmm_d2 ......................   Passed  789.95 sec
5/9 Test #5: hwrf_nmm_d3 ......................   Passed  861.48 sec
6/9 Test #2: global_4dvar .....................   Passed  1865.08 sec
7/9 Test #3: global_4denvar ...................   Passed  1865.57 sec
8/9 Test #6: rtma .............................   Passed  1873.83 sec
9/9 Test #1: global_3dvar .....................   Passed  2525.81 sec

100% tests passed, 0 tests failed out of 9

Total Test time (real) = 2525.83 sec
```

**Orion results**
```
Orion-login-4:/work/noaa/da/Russ.Treadon/git/gsi/pr516/build$ ctest -j 9
Test project /work/noaa/da/Russ.Treadon/git/gsi/pr516/build
    Start 1: global_3dvar
    Start 2: global_4dvar
    Start 3: global_4denvar
    Start 4: hwrf_nmm_d2
    Start 5: hwrf_nmm_d3
    Start 6: rtma
    Start 7: rrfs_3denvar_glbens
    Start 8: netcdf_fv3_regional
    Start 9: global_enkf
1/9 Test #9: global_enkf ......................   Passed  1142.52 sec
2/9 Test #4: hwrf_nmm_d2 ......................   Passed  1147.76 sec
3/9 Test #8: netcdf_fv3_regional ..............   Passed  1204.23 sec
4/9 Test #7: rrfs_3denvar_glbens ..............***Failed  2111.89 sec
5/9 Test #5: hwrf_nmm_d3 ......................   Passed  2120.05 sec
6/9 Test #2: global_4dvar .....................   Passed  2522.73 sec
7/9 Test #6: rtma .............................   Passed  2589.96 sec
8/9 Test #3: global_4denvar ...................   Passed  2943.07 sec
9/9 Test #1: global_3dvar .....................   Passed  3002.66 sec

89% tests passed, 1 tests failed out of 9

Total Test time (real) = 3002.66 sec

The following tests FAILED:
          7 - rrfs_3denvar_glbens (Failed)
Errors while running CTest
Output from these tests are in: /work/noaa/da/Russ.Treadon/git/gsi/pr516/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

The `rrfs_3denvar_glbens` failure was due to 
```
The runtime for rrfs_3denvar_glbens_hiproc_updat is 348.798303 seconds.  This has exceeded maximum allowable threshold time of 174.742093 seconds,
resulting in Failure of timethresh2 the regression test.
```
A check of the updat (`regtest_regional`) and contrl (`develop`) low and high task/thread count jobs reveals an unusually large `gsi.x` wall time for `rrfs_3denvar_glbens_hiproc_updat`
```
rrfs_3denvar_glbens_hiproc_contrl/stdout:The total amount of wall time                        = 116.494729
rrfs_3denvar_glbens_hiproc_updat/stdout:The total amount of wall time                        = 348.798303
rrfs_3denvar_glbens_loproc_contrl/stdout:The total amount of wall time                        = 181.178099
rrfs_3denvar_glbens_loproc_updat/stdout:The total amount of wall time                        = 193.671354
```
The regression tests run in the `/work` fileset on Orion.  This fileset has been suffering performance issues as noted in other issues (e.g, g-w issue [#1215](https://github.com/NOAA-EMC/global-workflow/issues/1215)).

As a test rerun `rrfs_3denvar_glbens` in the `/work2` fileset.   This time `rrfs_3denvar_glbens` passed.
```
Orion-login-4:/work/noaa/da/Russ.Treadon/git/gsi/pr516/build$ ctest -R rrfs_3denvar_glbens
Test project /work/noaa/da/Russ.Treadon/git/gsi/pr516/build
    Start 7: rrfs_3denvar_glbens
1/1 Test #7: rrfs_3denvar_glbens ..............   Passed  725.48 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 725.60 sec
```
with the following `gsi.x` wall times
```
rrfs_3denvar_glbens_hiproc_contrl/stdout:The total amount of wall time                        = 86.817547
rrfs_3denvar_glbens_hiproc_updat/stdout:The total amount of wall time                        = 86.786889
rrfs_3denvar_glbens_loproc_contrl/stdout:The total amount of wall time                        = 183.079476
rrfs_3denvar_glbens_loproc_updat/stdout:The total amount of wall time                        = 178.646917


```

**Comment by RussTreadon-NOAA** [comment]
@hu5970 , since I have committed changes to the PR we should have another person review these changes.

**Comment by hu5970** [comment]
@RussTreadon-NOAA Yes, I added Shun and Cory as reviewers. Thanks, Ming

**Review by RussTreadon-NOAA — APPROVED** [review]
Source code bug fixes are needed for code to successfully complete all ctests.    Also need to add four new rrfs fix files.    With these changes in place the full suite of nine ctests pass on WCOSS2 (cactus), Hera, and Orion.

My approval is not a _true_ approval since I pushed changes to this PR.

**Review by ShunLiu-NOAA — APPROVED** [review]
This PR's changes were reviewed. The old regression test cases have been removed and the new RRFS test case has been added. Thanks to Russ and Ming for running regression tests on various HPCs and resolving the issues. Russ has already performed regression tests on WCOSS2 and other HPCs. I do not run regression tests on my own. I just went through the script and code changes in the PR.

**Pull request merged**
