### PR TITLE
GitHub Issue NOAA-EMC/GSI#406. Remove observation monitoring tools

### LINKED ISSUE #406: Remove GSI Observation Monitoring Utilities from the GSI repository
The GSI observation monitoring tools have been moved to its own repository at: [NOAA-EMC/GSI-Monitor](https://github.com/NOAA-EMC/GSI-Monitor) as part of the repository separation of concerns.

### PR DESCRIPTION
**Pull request by aerorahul**
closes #406

### CODE REVIEW

**Review by MichaelLueken — COMMENTED** [review]
These changes remove the DA monitoring packages and bring in the changes which have been merged to release/gfsda.v16.3.0.  There is work that is currently out for review, but once that work has been merged, I can move forward with these changes.  However, before doing so, please reduce the number of commits from 2 to 1, as per the directions in the [wiki](https://github.com/NOAA-EMC/GSI/wiki/GSI-GitHub-General-User-Information#preparing-a-pull-request-pr):

1) git reset --soft HEAD~1
2) git commit --amend
3) Please add:
    `GitHub Issue NOAA-EMC/GSI#406.`
to the commit message.
     `GitHub Issue NOAA-EMC/GSI#406. Remove observation monitoring tools`
4) git push origin feature/remove_gsi_monitoring --force

Once these steps are complete, I will be able to merge this after the current work has been merged later this week.

**Comment by aerorahul** [comment]
> These changes remove the DA monitoring packages and bring in the changes which have been merged to release/gfsda.v16.3.0. There is work that is currently out for review, but once that work has been merged, I can move forward with these changes. However, before doing so, please reduce the number of commits from 2 to 1, as per the directions in the [wiki](https://github.com/NOAA-EMC/GSI/wiki/GSI-GitHub-General-User-Information#preparing-a-pull-request-pr):
> 
> 1. git reset --soft HEAD~1
> 2. git commit --amend
> 3. Please add:
>    `GitHub Issue NOAA-EMC/GSI#406.`
>    to the commit message.
>    `GitHub Issue NOAA-EMC/GSI#406. Remove observation monitoring tools`
> 4. git push origin feature/remove_gsi_monitoring --force
> 
> Once these steps are complete, I will be able to merge this after the current work has been merged later this week.

done.

**Comment by MichaelLueken** [comment]
@aerorahul @EdwardSafford-NOAA I'm planning on merging this update to the authoritative `develop` branch tomorrow.  I was wondering what the plan is to bring in the monitoring package moving forward.  Will the `NOAA-EMC/GSI-Monitor` repository be linked to `NOAA-EMC/GSI` through an external, or will each workflow that uses the monitoring packages need to be updated to add a checkout to the new `GSI-Monitor` project?  If an external will be used, should this be included with the removal of the monitoring package from the GSI repository?  I'd like clarification on the path forward before merging this work to the authoritative `develop` branch.

**Comment by aerorahul** [comment]
> @aerorahul @EdwardSafford-NOAA I'm planning on merging this update to the authoritative `develop` branch tomorrow. I was wondering what the plan is to bring in the monitoring package moving forward. Will the `NOAA-EMC/GSI-Monitor` repository be linked to `NOAA-EMC/GSI` through an external, or will each workflow that uses the monitoring packages need to be updated to add a checkout to the new `GSI-Monitor` project? If an external will be used, should this be included with the removal of the monitoring package from the GSI repository? I'd like clarification on the path forward before merging this work to the authoritative `develop` branch.

IMO, the GSI-monitor should be part of the application and not part of the GSI repository.
So adding relevant bits to the workflow to build the monitoring toolset.

**Comment by MichaelLueken** [comment]
Since this update is removing the observation monitoring tools from the authoritative develop branch, I will go ahead and merge these changes to the authoritative develop branch.

**Pull request merged**
